// Code generated by PGN catalog generator; DO NOT EDIT.
// Source schema 2.4.0 version 7.0.0.

package pgn

var generatedBgCatalogDefinitions = map[string]generatedCatalogDefinition{
	pgnDescriptionKey(65330, "B&G: Proprietary"):             {Id: "PgnBGProprietary", Decoder: DecodePgnBGProprietary, Encoder: encodePgnBGProprietaryMsg},
	pgnDescriptionKey(130824, "B&G: key-value data"):         {Id: "PgnBGKeyValueData", Decoder: DecodePgnBGKeyValueData, Encoder: encodePgnBGKeyValueDataMsg},
	pgnDescriptionKey(130833, "B&G: User and Remote rename"): {Id: "PgnBGUserAndRemoteRename", Decoder: DecodePgnBGUserAndRemoteRename, Encoder: encodePgnBGUserAndRemoteRenameMsg},
}

type PgnBGProprietary struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Data             []uint8     `json:"data,omitempty" n2k:"4"`
}

func (m *PgnBGProprietary) PGNNumber() uint32 { return 65330 }
func DecodePgnBGProprietary(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnBGProprietary{Info: Info}
	if err := decodeGeneratedCatalog(generatedCatalogInfo(65330, "B&G: Proprietary"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnBGProprietary(val *PgnBGProprietary) ([]byte, error) {
	return encodeGeneratedCatalog(generatedCatalogInfo(65330, "B&G: Proprietary"), val)
}
func encodePgnBGProprietaryMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnBGProprietary)
	if !ok {
		return nil, generatedCatalogTypeError("PgnBGProprietary", v)
	}
	return EncodePgnBGProprietary(val)
}

type PgnBGKeyValueData struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Key              *uint64     `json:"key,omitempty" n2k:"4"`
	Length           *uint64     `json:"length,omitempty" n2k:"5"`
	Value            []uint8     `json:"value,omitempty" n2k:"6"`
}

func (m *PgnBGKeyValueData) PGNNumber() uint32 { return 130824 }
func DecodePgnBGKeyValueData(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnBGKeyValueData{Info: Info}
	if err := decodeGeneratedCatalog(generatedCatalogInfo(130824, "B&G: key-value data"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnBGKeyValueData(val *PgnBGKeyValueData) ([]byte, error) {
	return encodeGeneratedCatalog(generatedCatalogInfo(130824, "B&G: key-value data"), val)
}
func encodePgnBGKeyValueDataMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnBGKeyValueData)
	if !ok {
		return nil, generatedCatalogTypeError("PgnBGKeyValueData", v)
	}
	return EncodePgnBGKeyValueData(val)
}

type PgnBGUserAndRemoteRename struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	DataType         *uint64     `json:"dataType,omitempty" n2k:"4"`
	Length           *uint64     `json:"length,omitempty" n2k:"5"`
	Decimals         *uint64     `json:"decimals,omitempty" n2k:"7"`
	ShortName        string      `json:"shortName,omitempty" n2k:"8"`
	LongName         string      `json:"longName,omitempty" n2k:"9"`
}

func (m *PgnBGUserAndRemoteRename) PGNNumber() uint32 { return 130833 }
func DecodePgnBGUserAndRemoteRename(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnBGUserAndRemoteRename{Info: Info}
	if err := decodeGeneratedCatalog(generatedCatalogInfo(130833, "B&G: User and Remote rename"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnBGUserAndRemoteRename(val *PgnBGUserAndRemoteRename) ([]byte, error) {
	return encodeGeneratedCatalog(generatedCatalogInfo(130833, "B&G: User and Remote rename"), val)
}
func encodePgnBGUserAndRemoteRenameMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnBGUserAndRemoteRename)
	if !ok {
		return nil, generatedCatalogTypeError("PgnBGUserAndRemoteRename", v)
	}
	return EncodePgnBGUserAndRemoteRename(val)
}
