// Code generated by PGN generator; DO NOT EDIT.
// Source schema 2.5.0 version 7.1.0.

package pgn

type CarlingBreakerCommand struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	MessageType      *uint64     `json:"messageType,omitempty" n2k:"4"`
	BreakerMapping1  *uint64     `json:"breakerMapping1,omitempty" n2k:"5"`
	BreakerMapping2  *uint64     `json:"breakerMapping2,omitempty" n2k:"6"`
	BreakerMapping3  *uint64     `json:"breakerMapping3,omitempty" n2k:"8"`
	BreakerCommand   *uint64     `json:"breakerCommand,omitempty" n2k:"9"`
	DimValue         *uint64     `json:"dimValue,omitempty" n2k:"10"`
}

func (m *CarlingBreakerCommand) PGNNumber() uint32                   { return 61184 }
func (m *CarlingBreakerCommand) MessageInfo() MessageInfo            { return m.Info }
func (m *CarlingBreakerCommand) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *CarlingBreakerCommand) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *CarlingBreakerCommand) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

type CarlingSwitchboardStatus struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	MessageType      *uint64     `json:"messageType,omitempty" n2k:"4"`
	Data             []uint8     `json:"data,omitempty" n2k:"5"`
}

func (m *CarlingSwitchboardStatus) PGNNumber() uint32               { return 65300 }
func (m *CarlingSwitchboardStatus) MessageInfo() MessageInfo        { return m.Info }
func (m *CarlingSwitchboardStatus) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *CarlingSwitchboardStatus) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *CarlingSwitchboardStatus) EncodePayload() ([]uint8, error) { return encodeFields(m) }

type CarlingDcConfigurationCommand struct {
	Info                      MessageInfo `json:"info"`
	ManufacturerCode          *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode              *uint64     `json:"industryCode,omitempty" n2k:"3"`
	MessageType               *uint64     `json:"messageType,omitempty" n2k:"4"`
	BreakerMapping1           *uint64     `json:"breakerMapping1,omitempty" n2k:"5"`
	BreakerMapping2           *uint64     `json:"breakerMapping2,omitempty" n2k:"6"`
	BreakerMapping3           *uint64     `json:"breakerMapping3,omitempty" n2k:"8"`
	InrushDelay               *uint64     `json:"inrushDelay,omitempty" n2k:"9"`
	TripDelay                 *uint64     `json:"tripDelay,omitempty" n2k:"10"`
	ConfigurationFlags        *uint64     `json:"configurationFlags,omitempty" n2k:"11"`
	CurrentRating             *uint64     `json:"currentRating,omitempty" n2k:"12"`
	FactoryMaxRating          *uint64     `json:"factoryMaxRating,omitempty" n2k:"13"`
	ScheduleBLoadShedPriority *uint64     `json:"scheduleBLoadShedPriority,omitempty" n2k:"14"`
	ScheduleALoadShedPriority *uint64     `json:"scheduleALoadShedPriority,omitempty" n2k:"15"`
	DimValue                  *uint64     `json:"dimValue,omitempty" n2k:"16"`
	BreakerGroup              *uint64     `json:"breakerGroup,omitempty" n2k:"17"`
	FlashMapIndex             *uint64     `json:"flashMapIndex,omitempty" n2k:"18"`
}

func (m *CarlingDcConfigurationCommand) PGNNumber() uint32               { return 126720 }
func (m *CarlingDcConfigurationCommand) MessageInfo() MessageInfo        { return m.Info }
func (m *CarlingDcConfigurationCommand) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *CarlingDcConfigurationCommand) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *CarlingDcConfigurationCommand) EncodePayload() ([]uint8, error) { return encodeFields(m) }

type CarlingProprietary struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Data             []uint8     `json:"data,omitempty" n2k:"4"`
}

func (m *CarlingProprietary) PGNNumber() uint32                   { return 130844 }
func (m *CarlingProprietary) MessageInfo() MessageInfo            { return m.Info }
func (m *CarlingProprietary) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *CarlingProprietary) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *CarlingProprietary) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

type CarlingBreakerStatusAndConfiguration struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	MessageType      *uint64     `json:"messageType,omitempty" n2k:"4"`
	Data             []uint8     `json:"data,omitempty" n2k:"5"`
}

func (m *CarlingBreakerStatusAndConfiguration) PGNNumber() uint32               { return 130921 }
func (m *CarlingBreakerStatusAndConfiguration) MessageInfo() MessageInfo        { return m.Info }
func (m *CarlingBreakerStatusAndConfiguration) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *CarlingBreakerStatusAndConfiguration) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *CarlingBreakerStatusAndConfiguration) EncodePayload() ([]uint8, error) {
	return encodeFields(m)
}
