// Code generated by PGN generator; DO NOT EDIT.
// Source schema 2.4.0 version 7.0.0.

package pgn

import (
	"errors"
	"fmt"
)

func DecodePayload(info MessageInfo, payload []uint8) (PGN, error) {
	switch info.PGN {
	case 59392:
		return decodePGNCandidates(info, payload,
			&Message0xe8000xee00StandardizedSingleFrameAddressed{Info: info},
			&IsoAcknowledgement{Info: info},
		)
	case 59904:
		return decodePGNCandidates(info, payload,
			&IsoRequest{Info: info},
		)
	case 60160:
		return decodePGNCandidates(info, payload,
			&IsoTransportProtocolDataTransfer{Info: info},
		)
	case 60416:
		return decodePGNCandidates(info, payload,
			&IsoTransportProtocolConnectionManagementAbort{Info: info},
			&IsoTransportProtocolConnectionManagementBroadcastAnnounce{Info: info},
			&IsoTransportProtocolConnectionManagementClearToSend{Info: info},
			&IsoTransportProtocolConnectionManagementEndOfMessage{Info: info},
			&IsoTransportProtocolConnectionManagementRequestToSend{Info: info},
		)
	case 60928:
		return decodePGNCandidates(info, payload,
			&IsoAddressClaim{Info: info},
		)
	case 61184:
		return decodePGNCandidates(info, payload,
			&Message0xef00ManufacturerProprietarySingleFrameAddressed{Info: info},
			&CarlingBreakerCommand{Info: info},
			&SeatalkWirelessKeypadControl{Info: info},
			&SeatalkWirelessKeypadLightControl{Info: info},
			&VictronVeCanRegister{Info: info},
		)
	case 61440:
		return decodePGNCandidates(info, payload,
			&Message0xf0000xfeffStandardizedSingleFrameNonAddressed{Info: info},
		)
	case 65001:
		return decodePGNCandidates(info, payload,
			&Bus1PhaseCBasicAcQuantities{Info: info},
		)
	case 65002:
		return decodePGNCandidates(info, payload,
			&Bus1PhaseBBasicAcQuantities{Info: info},
		)
	case 65003:
		return decodePGNCandidates(info, payload,
			&Bus1PhaseABasicAcQuantities{Info: info},
		)
	case 65004:
		return decodePGNCandidates(info, payload,
			&Bus1AverageBasicAcQuantities{Info: info},
		)
	case 65005:
		return decodePGNCandidates(info, payload,
			&UtilityTotalAcEnergy{Info: info},
		)
	case 65006:
		return decodePGNCandidates(info, payload,
			&UtilityPhaseCAcReactivePower{Info: info},
		)
	case 65007:
		return decodePGNCandidates(info, payload,
			&UtilityPhaseCAcPower{Info: info},
		)
	case 65008:
		return decodePGNCandidates(info, payload,
			&UtilityPhaseCBasicAcQuantities{Info: info},
		)
	case 65009:
		return decodePGNCandidates(info, payload,
			&UtilityPhaseBAcReactivePower{Info: info},
		)
	case 65010:
		return decodePGNCandidates(info, payload,
			&UtilityPhaseBAcPower{Info: info},
		)
	case 65011:
		return decodePGNCandidates(info, payload,
			&UtilityPhaseBBasicAcQuantities{Info: info},
		)
	case 65012:
		return decodePGNCandidates(info, payload,
			&UtilityPhaseAAcReactivePower{Info: info},
		)
	case 65013:
		return decodePGNCandidates(info, payload,
			&UtilityPhaseAAcPower{Info: info},
		)
	case 65014:
		return decodePGNCandidates(info, payload,
			&UtilityPhaseABasicAcQuantities{Info: info},
		)
	case 65015:
		return decodePGNCandidates(info, payload,
			&UtilityTotalAcReactivePower{Info: info},
		)
	case 65016:
		return decodePGNCandidates(info, payload,
			&UtilityTotalAcPower{Info: info},
		)
	case 65017:
		return decodePGNCandidates(info, payload,
			&UtilityAverageBasicAcQuantities{Info: info},
		)
	case 65018:
		return decodePGNCandidates(info, payload,
			&GeneratorTotalAcEnergy{Info: info},
		)
	case 65019:
		return decodePGNCandidates(info, payload,
			&GeneratorPhaseCAcReactivePower{Info: info},
		)
	case 65020:
		return decodePGNCandidates(info, payload,
			&GeneratorPhaseCAcPower{Info: info},
		)
	case 65021:
		return decodePGNCandidates(info, payload,
			&GeneratorPhaseCBasicAcQuantities{Info: info},
		)
	case 65022:
		return decodePGNCandidates(info, payload,
			&GeneratorPhaseBAcReactivePower{Info: info},
		)
	case 65023:
		return decodePGNCandidates(info, payload,
			&GeneratorPhaseBAcPower{Info: info},
		)
	case 65024:
		return decodePGNCandidates(info, payload,
			&GeneratorPhaseBBasicAcQuantities{Info: info},
		)
	case 65025:
		return decodePGNCandidates(info, payload,
			&GeneratorPhaseAAcReactivePower{Info: info},
		)
	case 65026:
		return decodePGNCandidates(info, payload,
			&GeneratorPhaseAAcPower{Info: info},
		)
	case 65027:
		return decodePGNCandidates(info, payload,
			&GeneratorPhaseABasicAcQuantities{Info: info},
		)
	case 65028:
		return decodePGNCandidates(info, payload,
			&GeneratorTotalAcReactivePower{Info: info},
		)
	case 65029:
		return decodePGNCandidates(info, payload,
			&GeneratorTotalAcPower{Info: info},
		)
	case 65030:
		return decodePGNCandidates(info, payload,
			&GeneratorAverageBasicAcQuantities{Info: info},
		)
	case 65240:
		return decodePGNCandidates(info, payload,
			&IsoCommandedAddress{Info: info},
		)
	case 65280:
		return decodePGNCandidates(info, payload,
			&Message0xff000xffffManufacturerProprietarySingleFrameNonAddressed{Info: info},
			&BepMarineCzoneCircuitControl{Info: info},
			&FurunoHeave{Info: info},
			&HondaEngineData{Info: info},
			&MaretronKeelPosition{Info: info},
			&MercuryEngineData{Info: info},
			&YanmarEngineDataA{Info: info},
		)
	case 65281:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn65281{Info: info},
			&YanmarEngineDataB{Info: info},
		)
	case 65282:
		return decodePGNCandidates(info, payload,
			&BepMarineCzoneAlarmEvent{Info: info},
			&MaretronNumberOfChannels{Info: info},
		)
	case 65283:
		return decodePGNCandidates(info, payload,
			&BepMarineCzoneChannelState{Info: info},
		)
	case 65284:
		return decodePGNCandidates(info, payload,
			&BepMarineCzoneCircuitStatus{Info: info},
			&HondaEngineAlerts{Info: info},
			&MaretronProprietaryDcBreakerCurrent{Info: info},
		)
	case 65285:
		return decodePGNCandidates(info, payload,
			&AirmarBootStateAcknowledgment{Info: info},
			&LowranceTemperature{Info: info},
			&MaretronUniversalConfigurationSf{Info: info},
		)
	case 65286:
		return decodePGNCandidates(info, payload,
			&AirmarBootStateRequest{Info: info},
			&ChetcoDimmer{Info: info},
			&MaretronFluidFlowRate{Info: info},
		)
	case 65287:
		return decodePGNCandidates(info, payload,
			&AirmarAccessLevel{Info: info},
			&MaretronTripVolume{Info: info},
			&SimnetConfigureTemperatureSensor{Info: info},
		)
	case 65288:
		return decodePGNCandidates(info, payload,
			&Maretron420Ma{Info: info},
			&SeatalkAlarm{Info: info},
		)
	case 65289:
		return decodePGNCandidates(info, payload,
			&Maretron010V{Info: info},
			&SimnetTrimTabSensorCalibration{Info: info},
		)
	case 65290:
		return decodePGNCandidates(info, payload,
			&BepMarineCzoneModuleAnnounce{Info: info},
			&MaretronRotationalRate{Info: info},
			&SimnetPaddleWheelSpeedConfiguration{Info: info},
		)
	case 65291:
		return decodePGNCandidates(info, payload,
			&MaretronResistance{Info: info},
		)
	case 65292:
		return decodePGNCandidates(info, payload,
			&MaretronAutomationFunctionMaster{Info: info},
			&SimnetClearFluidLevelWarnings{Info: info},
		)
	case 65293:
		return decodePGNCandidates(info, payload,
			&DiverseYachtServicesLoadCell{Info: info},
			&SimnetLgc2000Configuration{Info: info},
		)
	case 65294:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn65294{Info: info},
		)
	case 65295:
		return decodePGNCandidates(info, payload,
			&BepMarineCzoneAlarm{Info: info},
		)
	case 65296:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn65296{Info: info},
		)
	case 65297:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn65297{Info: info},
		)
	case 65298:
		return decodePGNCandidates(info, payload,
			&SuzukiEngineDataA{Info: info},
		)
	case 65299:
		return decodePGNCandidates(info, payload,
			&BepMarineCzoneAlarmStringRequest{Info: info},
			&SuzukiEngineDataB{Info: info},
		)
	case 65300:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn65300{Info: info},
			&CarlingSwitchboardStatus{Info: info},
			&SuzukiEngineDataC{Info: info},
		)
	case 65301:
		return decodePGNCandidates(info, payload,
			&BepMarineCzone65301{Info: info},
		)
	case 65302:
		return decodePGNCandidates(info, payload,
			&SimnetApUnknown1{Info: info},
		)
	case 65303:
		return decodePGNCandidates(info, payload,
			&SuzukiEngineDataD{Info: info},
		)
	case 65304:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn65304{Info: info},
			&SuzukiEngineDataE{Info: info},
		)
	case 65305:
		return decodePGNCandidates(info, payload,
			&SimnetDeviceModeRequest{Info: info},
			&SimnetDeviceStatus{Info: info},
			&SimnetDeviceStatusRequest{Info: info},
			&SimnetPilotMode{Info: info},
			&SimnetSailingProcessorStatus{Info: info},
		)
	case 65306:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn65306{Info: info},
		)
	case 65308:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn65308{Info: info},
		)
	case 65309:
		return decodePGNCandidates(info, payload,
			&NavicoWirelessBatteryStatus{Info: info},
		)
	case 65310:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn65310{Info: info},
		)
	case 65311:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn65311{Info: info},
		)
	case 65312:
		return decodePGNCandidates(info, payload,
			&NavicoWirelessSignalStatus{Info: info},
		)
	case 65313:
		return decodePGNCandidates(info, payload,
			&NavicoDepthQuality{Info: info},
		)
	case 65314:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn65314{Info: info},
			&YamahaGearStatus{Info: info},
		)
	case 65315:
		return decodePGNCandidates(info, payload,
			&SuzukiTrollModeControl{Info: info},
		)
	case 65316:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn65316{Info: info},
		)
	case 65317:
		return decodePGNCandidates(info, payload,
			&NavicoProprietary2{Info: info},
		)
	case 65323:
		return decodePGNCandidates(info, payload,
			&SimnetApUnknown5{Info: info},
		)
	case 65324:
		return decodePGNCandidates(info, payload,
			&SimnetAnalogTelemetry{Info: info},
		)
	case 65325:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn65325{Info: info},
		)
	case 65329:
		return decodePGNCandidates(info, payload,
			&YamahaEngineDataA{Info: info},
		)
	case 65330:
		return decodePGNCandidates(info, payload,
			&BGProprietary{Info: info},
		)
	case 65332:
		return decodePGNCandidates(info, payload,
			&YanmarEngineDataC{Info: info},
		)
	case 65340:
		return decodePGNCandidates(info, payload,
			&SimnetAutopilotModeState{Info: info},
		)
	case 65341:
		return decodePGNCandidates(info, payload,
			&SimnetAutopilotAngle{Info: info},
		)
	case 65344:
		return decodePGNCandidates(info, payload,
			&YamahaEngineDataB{Info: info},
		)
	case 65345:
		return decodePGNCandidates(info, payload,
			&SeatalkPilotWindDatum{Info: info},
		)
	case 65346:
		return decodePGNCandidates(info, payload,
			&YanmarEngineDataD{Info: info},
		)
	case 65348:
		return decodePGNCandidates(info, payload,
			&YanmarEngineDataE{Info: info},
		)
	case 65349:
		return decodePGNCandidates(info, payload,
			&YanmarEngineDataF{Info: info},
		)
	case 65350:
		return decodePGNCandidates(info, payload,
			&SimnetMagneticField{Info: info},
		)
	case 65359:
		return decodePGNCandidates(info, payload,
			&SeatalkPilotHeading{Info: info},
		)
	case 65360:
		return decodePGNCandidates(info, payload,
			&SeatalkPilotLockedHeading{Info: info},
		)
	case 65361:
		return decodePGNCandidates(info, payload,
			&SeatalkSilenceAlarm{Info: info},
		)
	case 65371:
		return decodePGNCandidates(info, payload,
			&SeatalkKeypadMessage{Info: info},
		)
	case 65374:
		return decodePGNCandidates(info, payload,
			&SeatalkKeypadHeartbeat{Info: info},
		)
	case 65379:
		return decodePGNCandidates(info, payload,
			&SeatalkPilotMode{Info: info},
		)
	case 65403:
		return decodePGNCandidates(info, payload,
			&LumishoreLightStatus{Info: info},
		)
	case 65408:
		return decodePGNCandidates(info, payload,
			&AirmarDepthQualityFactor{Info: info},
		)
	case 65409:
		return decodePGNCandidates(info, payload,
			&AirmarSpeedPulseCount{Info: info},
		)
	case 65410:
		return decodePGNCandidates(info, payload,
			&AirmarDeviceInformation{Info: info},
		)
	case 65420:
		return decodePGNCandidates(info, payload,
			&SimnetApUnknown3{Info: info},
		)
	case 65424:
		return decodePGNCandidates(info, payload,
			&YamahaEngineDataC{Info: info},
		)
	case 65440:
		return decodePGNCandidates(info, payload,
			&NavicoNaviopSwitchStatus{Info: info},
		)
	case 65441:
		return decodePGNCandidates(info, payload,
			&NavicoNaviopSwitchControl{Info: info},
		)
	case 65472:
		return decodePGNCandidates(info, payload,
			&YamahaEngineDataD{Info: info},
		)
	case 65480:
		return decodePGNCandidates(info, payload,
			&SimnetAutopilotMode{Info: info},
		)
	case 126208:
		return decodePGNCandidates(info, payload,
			&Message0x1ed000x1ee00StandardizedFastPacketAddressed{Info: info},
			&NmeaAcknowledgeGroupFunction{Info: info},
			&NmeaCommandGroupFunction{Info: info},
			&NmeaReadFieldsGroupFunction{Info: info},
			&NmeaReadFieldsReplyGroupFunction{Info: info},
			&NmeaRequestGroupFunction{Info: info},
			&NmeaWriteFieldsGroupFunction{Info: info},
			&NmeaWriteFieldsReplyGroupFunction{Info: info},
		)
	case 126464:
		return decodePGNCandidates(info, payload,
			&ParameterGroupNumberListTransmitAndReceive{Info: info},
		)
	case 126720:
		return decodePGNCandidates(info, payload,
			&Message0x1ef00ManufacturerProprietaryFastPacketAddressed{Info: info},
			&AirmarAddressableMultiFrame{Info: info},
			&AirmarAttitudeOffset{Info: info},
			&AirmarCalibrateCompass{Info: info},
			&AirmarCalibrateDepth{Info: info},
			&AirmarCalibrateSpeed{Info: info},
			&AirmarCalibrateTemperature{Info: info},
			&AirmarNmea2000Options{Info: info},
			&AirmarSimulateMode{Info: info},
			&AirmarSpeedFilterIir{Info: info},
			&AirmarSpeedFilterNone{Info: info},
			&AirmarTemperatureFilterIir{Info: info},
			&AirmarTemperatureFilterNone{Info: info},
			&AirmarTrueWindOptions{Info: info},
			&CarlingDcConfigurationCommand{Info: info},
			&FusionMediaControl{Info: info},
			&FusionRequestStatus{Info: info},
			&FusionSetAllVolumes{Info: info},
			&FusionSetMute{Info: info},
			&FusionSetPower{Info: info},
			&FusionSetSource{Info: info},
			&FusionSetZoneVolume{Info: info},
			&FusionSiriusControl{Info: info},
			&GarminAhrsAttCogSourceValidFlag{Info: info},
			&GarminAhrsAttDeviceFlags{Info: info},
			&GarminAhrsAttNonDefaultCalibrationMatrixPresent{Info: info},
			&GarminAhrsAttSetNorthState{Info: info},
			&GarminColorMode{Info: info},
			&GarminDayMode{Info: info},
			&GarminNightMode{Info: info},
			&LumishoreProprietary{Info: info},
			&MaretronDeviationCalibrationResponse{Info: info},
			&MaretronProprietaryConfiguration{Info: info},
			&MaretronSlaveResponse{Info: info},
			&Seatalk1DeviceIdentification{Info: info},
			&Seatalk1DisplayBrightness{Info: info},
			&Seatalk1DisplayColor{Info: info},
			&Seatalk1Keystroke{Info: info},
			&Seatalk1PilotHullType{Info: info},
			&Seatalk1PilotMode{Info: info},
			&SeatalkPilotAutoTurn{Info: info},
		)
	case 126976:
		return decodePGNCandidates(info, payload,
			&Message0x1f0000x1feffStandardizedMixedSingleFastPacketNonAddressed{Info: info},
		)
	case 126983:
		return decodePGNCandidates(info, payload,
			&Alert{Info: info},
		)
	case 126984:
		return decodePGNCandidates(info, payload,
			&AlertResponse{Info: info},
		)
	case 126985:
		return decodePGNCandidates(info, payload,
			&AlertText{Info: info},
		)
	case 126986:
		return decodePGNCandidates(info, payload,
			&AlertConfiguration{Info: info},
		)
	case 126987:
		return decodePGNCandidates(info, payload,
			&AlertThreshold{Info: info},
		)
	case 126988:
		return decodePGNCandidates(info, payload,
			&AlertValue{Info: info},
		)
	case 126992:
		return decodePGNCandidates(info, payload,
			&SystemTime{Info: info},
		)
	case 126993:
		return decodePGNCandidates(info, payload,
			&Heartbeat{Info: info},
		)
	case 126996:
		return decodePGNCandidates(info, payload,
			&ProductInformation{Info: info},
		)
	case 126998:
		return decodePGNCandidates(info, payload,
			&ConfigurationInformation{Info: info},
		)
	case 127233:
		return decodePGNCandidates(info, payload,
			&ManOverboardNotification{Info: info},
		)
	case 127237:
		return decodePGNCandidates(info, payload,
			&HeadingTrackControl{Info: info},
		)
	case 127245:
		return decodePGNCandidates(info, payload,
			&Rudder{Info: info},
		)
	case 127250:
		return decodePGNCandidates(info, payload,
			&VesselHeading{Info: info},
		)
	case 127251:
		return decodePGNCandidates(info, payload,
			&RateOfTurn{Info: info},
		)
	case 127252:
		return decodePGNCandidates(info, payload,
			&Heave{Info: info},
		)
	case 127257:
		return decodePGNCandidates(info, payload,
			&Attitude{Info: info},
		)
	case 127258:
		return decodePGNCandidates(info, payload,
			&MagneticVariation{Info: info},
		)
	case 127488:
		return decodePGNCandidates(info, payload,
			&EngineParametersRapidUpdate{Info: info},
		)
	case 127489:
		return decodePGNCandidates(info, payload,
			&EngineParametersDynamic{Info: info},
		)
	case 127490:
		return decodePGNCandidates(info, payload,
			&ElectricDriveStatusDynamic{Info: info},
		)
	case 127491:
		return decodePGNCandidates(info, payload,
			&ElectricEnergyStorageStatusDynamic{Info: info},
		)
	case 127493:
		return decodePGNCandidates(info, payload,
			&TransmissionParametersDynamic{Info: info},
		)
	case 127494:
		return decodePGNCandidates(info, payload,
			&ElectricDriveInformation{Info: info},
		)
	case 127495:
		return decodePGNCandidates(info, payload,
			&ElectricEnergyStorageInformation{Info: info},
		)
	case 127496:
		return decodePGNCandidates(info, payload,
			&TripParametersVessel{Info: info},
		)
	case 127497:
		return decodePGNCandidates(info, payload,
			&TripParametersEngine{Info: info},
		)
	case 127498:
		return decodePGNCandidates(info, payload,
			&EngineParametersStatic{Info: info},
		)
	case 127500:
		return decodePGNCandidates(info, payload,
			&LoadControllerConnectionStateControl{Info: info},
		)
	case 127501:
		return decodePGNCandidates(info, payload,
			&BinarySwitchBankStatus{Info: info},
		)
	case 127502:
		return decodePGNCandidates(info, payload,
			&SwitchBankControl{Info: info},
		)
	case 127503:
		return decodePGNCandidates(info, payload,
			&AcInputStatus{Info: info},
		)
	case 127504:
		return decodePGNCandidates(info, payload,
			&AcOutputStatus{Info: info},
		)
	case 127505:
		return decodePGNCandidates(info, payload,
			&FluidLevel{Info: info},
		)
	case 127506:
		return decodePGNCandidates(info, payload,
			&DcDetailedStatus{Info: info},
		)
	case 127507:
		return decodePGNCandidates(info, payload,
			&ChargerStatus{Info: info},
		)
	case 127508:
		return decodePGNCandidates(info, payload,
			&BatteryStatus{Info: info},
		)
	case 127509:
		return decodePGNCandidates(info, payload,
			&InverterStatus{Info: info},
		)
	case 127510:
		return decodePGNCandidates(info, payload,
			&ChargerConfigurationStatus{Info: info},
		)
	case 127511:
		return decodePGNCandidates(info, payload,
			&InverterConfigurationStatus{Info: info},
		)
	case 127512:
		return decodePGNCandidates(info, payload,
			&AgsConfigurationStatus{Info: info},
		)
	case 127513:
		return decodePGNCandidates(info, payload,
			&BatteryConfigurationStatus{Info: info},
		)
	case 127514:
		return decodePGNCandidates(info, payload,
			&AgsStatus{Info: info},
		)
	case 127744:
		return decodePGNCandidates(info, payload,
			&AcPowerCurrentPhaseA{Info: info},
		)
	case 127745:
		return decodePGNCandidates(info, payload,
			&AcPowerCurrentPhaseB{Info: info},
		)
	case 127746:
		return decodePGNCandidates(info, payload,
			&AcPowerCurrentPhaseC{Info: info},
		)
	case 127747:
		return decodePGNCandidates(info, payload,
			&AcVoltageFrequencyPhaseA{Info: info},
		)
	case 127748:
		return decodePGNCandidates(info, payload,
			&AcVoltageFrequencyPhaseB{Info: info},
		)
	case 127749:
		return decodePGNCandidates(info, payload,
			&AcVoltageFrequencyPhaseC{Info: info},
		)
	case 127750:
		return decodePGNCandidates(info, payload,
			&ConverterStatus{Info: info},
		)
	case 127751:
		return decodePGNCandidates(info, payload,
			&DcVoltageCurrent{Info: info},
		)
	case 128000:
		return decodePGNCandidates(info, payload,
			&LeewayAngle{Info: info},
		)
	case 128001:
		return decodePGNCandidates(info, payload,
			&VesselAcceleration{Info: info},
		)
	case 128002:
		return decodePGNCandidates(info, payload,
			&ElectricDriveStatusRapidUpdate{Info: info},
		)
	case 128003:
		return decodePGNCandidates(info, payload,
			&ElectricEnergyStorageStatusRapidUpdate{Info: info},
		)
	case 128006:
		return decodePGNCandidates(info, payload,
			&ThrusterControlStatus{Info: info},
		)
	case 128007:
		return decodePGNCandidates(info, payload,
			&ThrusterInformation{Info: info},
		)
	case 128008:
		return decodePGNCandidates(info, payload,
			&ThrusterMotorStatus{Info: info},
		)
	case 128259:
		return decodePGNCandidates(info, payload,
			&Speed{Info: info},
		)
	case 128267:
		return decodePGNCandidates(info, payload,
			&WaterDepth{Info: info},
		)
	case 128275:
		return decodePGNCandidates(info, payload,
			&DistanceLog{Info: info},
		)
	case 128520:
		return decodePGNCandidates(info, payload,
			&TrackedTargetData{Info: info},
		)
	case 128538:
		return decodePGNCandidates(info, payload,
			&ElevatorCarStatus{Info: info},
		)
	case 128768:
		return decodePGNCandidates(info, payload,
			&ElevatorMotorControl{Info: info},
		)
	case 128769:
		return decodePGNCandidates(info, payload,
			&ElevatorDeckPushButton{Info: info},
		)
	case 128776:
		return decodePGNCandidates(info, payload,
			&WindlassControlStatus{Info: info},
		)
	case 128777:
		return decodePGNCandidates(info, payload,
			&AnchorWindlassOperatingStatus{Info: info},
		)
	case 128778:
		return decodePGNCandidates(info, payload,
			&AnchorWindlassMonitoringStatus{Info: info},
		)
	case 128780:
		return decodePGNCandidates(info, payload,
			&LinearActuatorControlStatus{Info: info},
		)
	case 129025:
		return decodePGNCandidates(info, payload,
			&PositionRapidUpdate{Info: info},
		)
	case 129026:
		return decodePGNCandidates(info, payload,
			&CogSogRapidUpdate{Info: info},
		)
	case 129027:
		return decodePGNCandidates(info, payload,
			&PositionDeltaRapidUpdate{Info: info},
		)
	case 129028:
		return decodePGNCandidates(info, payload,
			&AltitudeDeltaRapidUpdate{Info: info},
		)
	case 129029:
		return decodePGNCandidates(info, payload,
			&GnssPositionData{Info: info},
		)
	case 129033:
		return decodePGNCandidates(info, payload,
			&TimeDate{Info: info},
		)
	case 129038:
		return decodePGNCandidates(info, payload,
			&AisClassAPositionReport{Info: info},
		)
	case 129039:
		return decodePGNCandidates(info, payload,
			&AisClassBPositionReport{Info: info},
		)
	case 129040:
		return decodePGNCandidates(info, payload,
			&AisClassBExtendedPositionReport{Info: info},
		)
	case 129041:
		return decodePGNCandidates(info, payload,
			&AisAidsToNavigationAtonReport{Info: info},
		)
	case 129044:
		return decodePGNCandidates(info, payload,
			&Datum{Info: info},
		)
	case 129045:
		return decodePGNCandidates(info, payload,
			&UserDatum{Info: info},
		)
	case 129283:
		return decodePGNCandidates(info, payload,
			&CrossTrackError{Info: info},
		)
	case 129284:
		return decodePGNCandidates(info, payload,
			&NavigationData{Info: info},
		)
	case 129285:
		return decodePGNCandidates(info, payload,
			&NavigationRouteWpInformation{Info: info},
		)
	case 129291:
		return decodePGNCandidates(info, payload,
			&SetDriftRapidUpdate{Info: info},
		)
	case 129301:
		return decodePGNCandidates(info, payload,
			&NavigationRouteTimeToFromMark{Info: info},
		)
	case 129302:
		return decodePGNCandidates(info, payload,
			&BearingAndDistanceBetweenTwoMarks{Info: info},
		)
	case 129538:
		return decodePGNCandidates(info, payload,
			&GnssControlStatus{Info: info},
		)
	case 129539:
		return decodePGNCandidates(info, payload,
			&GnssDops{Info: info},
		)
	case 129540:
		return decodePGNCandidates(info, payload,
			&GnssSatsInView{Info: info},
		)
	case 129541:
		return decodePGNCandidates(info, payload,
			&GpsAlmanacData{Info: info},
		)
	case 129542:
		return decodePGNCandidates(info, payload,
			&GnssPseudorangeNoiseStatistics{Info: info},
		)
	case 129545:
		return decodePGNCandidates(info, payload,
			&GnssRaimOutput{Info: info},
		)
	case 129546:
		return decodePGNCandidates(info, payload,
			&GnssRaimSettings{Info: info},
		)
	case 129547:
		return decodePGNCandidates(info, payload,
			&GnssPseudorangeErrorStatistics{Info: info},
		)
	case 129549:
		return decodePGNCandidates(info, payload,
			&DgnssCorrections{Info: info},
		)
	case 129550:
		return decodePGNCandidates(info, payload,
			&GnssDifferentialCorrectionReceiverInterface{Info: info},
		)
	case 129551:
		return decodePGNCandidates(info, payload,
			&GnssDifferentialCorrectionReceiverSignal{Info: info},
		)
	case 129556:
		return decodePGNCandidates(info, payload,
			&GlonassAlmanacData{Info: info},
		)
	case 129792:
		return decodePGNCandidates(info, payload,
			&AisDgnssBroadcastBinaryMessage{Info: info},
		)
	case 129793:
		return decodePGNCandidates(info, payload,
			&AisUtcAndDateReport{Info: info},
		)
	case 129794:
		return decodePGNCandidates(info, payload,
			&AisClassAStaticAndVoyageRelatedData{Info: info},
		)
	case 129795:
		return decodePGNCandidates(info, payload,
			&AisAddressedBinaryMessage{Info: info},
		)
	case 129796:
		return decodePGNCandidates(info, payload,
			&AisAcknowledge{Info: info},
		)
	case 129797:
		return decodePGNCandidates(info, payload,
			&AisBinaryBroadcastMessage{Info: info},
		)
	case 129798:
		return decodePGNCandidates(info, payload,
			&AisSarAircraftPositionReport{Info: info},
		)
	case 129799:
		return decodePGNCandidates(info, payload,
			&RadioFrequencyModePower{Info: info},
		)
	case 129800:
		return decodePGNCandidates(info, payload,
			&AisUtcDateInquiry{Info: info},
		)
	case 129801:
		return decodePGNCandidates(info, payload,
			&AisAddressedSafetyRelatedMessage{Info: info},
		)
	case 129802:
		return decodePGNCandidates(info, payload,
			&AisSafetyRelatedBroadcastMessage{Info: info},
		)
	case 129803:
		return decodePGNCandidates(info, payload,
			&AisInterrogation{Info: info},
		)
	case 129804:
		return decodePGNCandidates(info, payload,
			&AisAssignmentModeCommand{Info: info},
		)
	case 129805:
		return decodePGNCandidates(info, payload,
			&AisDataLinkManagementMessage{Info: info},
		)
	case 129806:
		return decodePGNCandidates(info, payload,
			&AisChannelManagement{Info: info},
		)
	case 129807:
		return decodePGNCandidates(info, payload,
			&AisClassBGroupAssignment{Info: info},
		)
	case 129808:
		return decodePGNCandidates(info, payload,
			&DscCallInformation{Info: info},
			&DscDistressCallInformation{Info: info},
		)
	case 129809:
		return decodePGNCandidates(info, payload,
			&AisClassBStaticDataMsg24PartA{Info: info},
		)
	case 129810:
		return decodePGNCandidates(info, payload,
			&AisClassBStaticDataMsg24PartB{Info: info},
		)
	case 129811:
		return decodePGNCandidates(info, payload,
			&AisSingleSlotBinaryMessageDeprecated{Info: info},
		)
	case 129812:
		return decodePGNCandidates(info, payload,
			&AisMultiSlotBinaryMessageDeprecated{Info: info},
		)
	case 129813:
		return decodePGNCandidates(info, payload,
			&AisLongRangeBroadcastMessage{Info: info},
		)
	case 129814:
		return decodePGNCandidates(info, payload,
			&AisSingleSlotBinaryMessage{Info: info},
		)
	case 129815:
		return decodePGNCandidates(info, payload,
			&AisMultiSlotBinaryMessage{Info: info},
		)
	case 129816:
		return decodePGNCandidates(info, payload,
			&AisAcknowledgeBinary{Info: info},
		)
	case 130052:
		return decodePGNCandidates(info, payload,
			&LoranCTdData{Info: info},
		)
	case 130053:
		return decodePGNCandidates(info, payload,
			&LoranCRangeData{Info: info},
		)
	case 130054:
		return decodePGNCandidates(info, payload,
			&LoranCSignalData{Info: info},
		)
	case 130060:
		return decodePGNCandidates(info, payload,
			&Label{Info: info},
		)
	case 130061:
		return decodePGNCandidates(info, payload,
			&ChannelSourceConfiguration{Info: info},
		)
	case 130064:
		return decodePGNCandidates(info, payload,
			&RouteAndWpServiceDatabaseList{Info: info},
		)
	case 130065:
		return decodePGNCandidates(info, payload,
			&RouteAndWpServiceRouteList{Info: info},
		)
	case 130066:
		return decodePGNCandidates(info, payload,
			&RouteAndWpServiceRouteWpListAttributes{Info: info},
		)
	case 130067:
		return decodePGNCandidates(info, payload,
			&RouteAndWpServiceRouteWpNamePosition{Info: info},
		)
	case 130068:
		return decodePGNCandidates(info, payload,
			&RouteAndWpServiceRouteWpName{Info: info},
		)
	case 130069:
		return decodePGNCandidates(info, payload,
			&RouteAndWpServiceXteLimitNavigationMethod{Info: info},
		)
	case 130070:
		return decodePGNCandidates(info, payload,
			&RouteAndWpServiceWpComment{Info: info},
		)
	case 130071:
		return decodePGNCandidates(info, payload,
			&RouteAndWpServiceRouteComment{Info: info},
		)
	case 130072:
		return decodePGNCandidates(info, payload,
			&RouteAndWpServiceDatabaseComment{Info: info},
		)
	case 130073:
		return decodePGNCandidates(info, payload,
			&RouteAndWpServiceRadiusOfTurn{Info: info},
		)
	case 130074:
		return decodePGNCandidates(info, payload,
			&RouteAndWpServiceWpListWpNamePosition{Info: info},
		)
	case 130306:
		return decodePGNCandidates(info, payload,
			&WindData{Info: info},
		)
	case 130310:
		return decodePGNCandidates(info, payload,
			&EnvironmentalParametersObsolete{Info: info},
		)
	case 130311:
		return decodePGNCandidates(info, payload,
			&EnvironmentalParameters{Info: info},
		)
	case 130312:
		return decodePGNCandidates(info, payload,
			&Temperature{Info: info},
		)
	case 130313:
		return decodePGNCandidates(info, payload,
			&Humidity{Info: info},
		)
	case 130314:
		return decodePGNCandidates(info, payload,
			&ActualPressure{Info: info},
		)
	case 130315:
		return decodePGNCandidates(info, payload,
			&SetPressure{Info: info},
		)
	case 130316:
		return decodePGNCandidates(info, payload,
			&TemperatureExtendedRange{Info: info},
		)
	case 130320:
		return decodePGNCandidates(info, payload,
			&TideStationData{Info: info},
		)
	case 130321:
		return decodePGNCandidates(info, payload,
			&SalinityStationData{Info: info},
		)
	case 130322:
		return decodePGNCandidates(info, payload,
			&CurrentStationData{Info: info},
		)
	case 130323:
		return decodePGNCandidates(info, payload,
			&MeteorologicalStationData{Info: info},
		)
	case 130324:
		return decodePGNCandidates(info, payload,
			&MooredBuoyStationData{Info: info},
		)
	case 130329:
		return decodePGNCandidates(info, payload,
			&HvacStatus{Info: info},
		)
	case 130330:
		return decodePGNCandidates(info, payload,
			&LightingSystemSettings{Info: info},
		)
	case 130560:
		return decodePGNCandidates(info, payload,
			&PayloadMass{Info: info},
		)
	case 130561:
		return decodePGNCandidates(info, payload,
			&LightingZone{Info: info},
		)
	case 130562:
		return decodePGNCandidates(info, payload,
			&LightingScene{Info: info},
		)
	case 130563:
		return decodePGNCandidates(info, payload,
			&LightingDevice{Info: info},
		)
	case 130564:
		return decodePGNCandidates(info, payload,
			&LightingDeviceEnumeration{Info: info},
		)
	case 130565:
		return decodePGNCandidates(info, payload,
			&LightingColorSequence{Info: info},
		)
	case 130566:
		return decodePGNCandidates(info, payload,
			&LightingProgram{Info: info},
		)
	case 130567:
		return decodePGNCandidates(info, payload,
			&WatermakerInputSettingAndStatus{Info: info},
		)
	case 130568:
		return decodePGNCandidates(info, payload,
			&EntertainmentDiagnosticStatus{Info: info},
		)
	case 130569:
		return decodePGNCandidates(info, payload,
			&CurrentStatusAndFile{Info: info},
		)
	case 130570:
		return decodePGNCandidates(info, payload,
			&LibraryDataFile{Info: info},
		)
	case 130571:
		return decodePGNCandidates(info, payload,
			&LibraryDataGroup{Info: info},
		)
	case 130572:
		return decodePGNCandidates(info, payload,
			&LibraryDataSearch{Info: info},
		)
	case 130573:
		return decodePGNCandidates(info, payload,
			&SupportedSourceData{Info: info},
		)
	case 130574:
		return decodePGNCandidates(info, payload,
			&SupportedZoneData{Info: info},
		)
	case 130575:
		return decodePGNCandidates(info, payload,
			&EntertainmentParentalControlStatus{Info: info},
		)
	case 130576:
		return decodePGNCandidates(info, payload,
			&SmallCraftStatus{Info: info},
		)
	case 130577:
		return decodePGNCandidates(info, payload,
			&DirectionData{Info: info},
		)
	case 130578:
		return decodePGNCandidates(info, payload,
			&VesselSpeedComponents{Info: info},
		)
	case 130579:
		return decodePGNCandidates(info, payload,
			&SystemConfiguration{Info: info},
		)
	case 130580:
		return decodePGNCandidates(info, payload,
			&SystemConfigurationDeprecated{Info: info},
		)
	case 130581:
		return decodePGNCandidates(info, payload,
			&ZoneConfigurationDeprecated{Info: info},
		)
	case 130582:
		return decodePGNCandidates(info, payload,
			&ZoneVolume{Info: info},
		)
	case 130583:
		return decodePGNCandidates(info, payload,
			&AvailableAudioEqPresets{Info: info},
		)
	case 130584:
		return decodePGNCandidates(info, payload,
			&AvailableBluetoothAddresses{Info: info},
		)
	case 130585:
		return decodePGNCandidates(info, payload,
			&BluetoothSourceStatus{Info: info},
		)
	case 130586:
		return decodePGNCandidates(info, payload,
			&ZoneConfiguration{Info: info},
		)
	case 130816:
		return decodePGNCandidates(info, payload,
			&Message0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed{Info: info},
			&BepMarineCzoneZcfBusDistribution{Info: info},
			&FurunoStatusAndVersionReport{Info: info},
			&HondaEngineStatus{Info: info},
			&SeaRecoveryWatermakerStatus{Info: info},
			&SimradTextMessage{Info: info},
			&SonichubAmRadio{Info: info},
			&SonichubAlbum{Info: info},
			&SonichubArtist{Info: info},
			&SonichubControl{Info: info},
			&SonichubFmRadio{Info: info},
			&SonichubInit1{Info: info},
			&SonichubInit2{Info: info},
			&SonichubInit3{Info: info},
			&SonichubMaxVolume{Info: info},
			&SonichubMenuItem{Info: info},
			&SonichubPlaylist{Info: info},
			&SonichubPosition{Info: info},
			&SonichubSource{Info: info},
			&SonichubSourceList{Info: info},
			&SonichubTrack{Info: info},
			&SonichubVolume{Info: info},
			&SonichubZoneInfo{Info: info},
			&SonichubZones{Info: info},
		)
	case 130817:
		return decodePGNCandidates(info, payload,
			&BepMarineCzoneStatusExtended{Info: info},
			&FurunoSvControl{Info: info},
			&LowranceProductInformation{Info: info},
			&MaretronAnnunciatorCapabilities{Info: info},
			&NavicoUnknown{Info: info},
		)
	case 130818:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn130818{Info: info},
			&FurunoSensorSetup{Info: info},
			&MaretronLabel{Info: info},
			&SimnetReprogramData{Info: info},
			&WebastoStatus2{Info: info},
		)
	case 130819:
		return decodePGNCandidates(info, payload,
			&BepMarineCzone130819{Info: info},
			&FurunoDeadReckoningConfiguration{Info: info},
			&MaretronAlertTransmission{Info: info},
			&SimnetRequestReprogram{Info: info},
			&WebastoHvacCommand{Info: info},
		)
	case 130820:
		return decodePGNCandidates(info, payload,
			&BepMarineCzoneAlarmStringResponse{Info: info},
			&BepMarineProprietaryPgn130820{Info: info},
			&FurunoUnknown130820{Info: info},
			&FusionAlbumName{Info: info},
			&FusionArtistName{Info: info},
			&FusionAuxGain{Info: info},
			&FusionBalance{Info: info},
			&FusionCapabilities{Info: info},
			&FusionDeviceName{Info: info},
			&FusionEq{Info: info},
			&FusionIgnitionSwitchState{Info: info},
			&FusionLineLevelControl{Info: info},
			&FusionLowPassFilter{Info: info},
			&FusionMarineTuner{Info: info},
			&FusionMarineScanMode{Info: info},
			&FusionMarineSquelch{Info: info},
			&FusionMedia{Info: info},
			&FusionMenuItem{Info: info},
			&FusionMenuLockId{Info: info},
			&FusionMono{Info: info},
			&FusionMultiroom{Info: info},
			&FusionMultiroomStatus{Info: info},
			&FusionMute{Info: info},
			&FusionPowerState{Info: info},
			&FusionProcessingBypass{Info: info},
			&FusionRdsData{Info: info},
			&FusionSetting{Info: info},
			&FusionSettings{Info: info},
			&FusionSiriusxm{Info: info},
			&FusionSiriusxmArtist{Info: info},
			&FusionSiriusxmCategory{Info: info},
			&FusionSiriusxmChannel{Info: info},
			&FusionSiriusxmContentInfo{Info: info},
			&FusionSiriusxmPresets{Info: info},
			&FusionSiriusxmSignal{Info: info},
			&FusionSiriusxmTitle{Info: info},
			&FusionSource{Info: info},
			&FusionSourceCount{Info: info},
			&FusionSpeedVolumeCurrentSpeed{Info: info},
			&FusionSublevels{Info: info},
			&FusionTrackName{Info: info},
			&FusionTrackPosition{Info: info},
			&FusionTuner{Info: info},
			&FusionUsbRepeatStatus{Info: info},
			&FusionVersions{Info: info},
			&FusionVolumeLimits{Info: info},
			&FusionVolumes{Info: info},
			&FusionZoneName{Info: info},
			&MaretronAlertResponse{Info: info},
			&SimnetReprogramStatus{Info: info},
		)
	case 130821:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn130821{Info: info},
			&FurunoUnknown130821{Info: info},
			&MaretronAlertText{Info: info},
			&NavicoAsciiData{Info: info},
		)
	case 130822:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn130822{Info: info},
			&MaretronAlertControl{Info: info},
			&MercuryEngineTelemetryLowSpeed{Info: info},
			&NavicoUdbDatabaseBulkReport2{Info: info},
			&NavicoUdbDatabaseBulkReport3{Info: info},
			&NavicoUdbDatabaseBulkReport4{Info: info},
			&NavicoUdbDatabaseObjectDump{Info: info},
			&NavicoUdbDatabaseObjectPing{Info: info},
			&NavicoUdbDatabaseShortReport5{Info: info},
			&NavicoUdbDatabaseShortReport7{Info: info},
			&NavicoUdbDatabaseSourceReport{Info: info},
		)
	case 130823:
		return decodePGNCandidates(info, payload,
			&MaretronProprietaryTemperatureHighRange{Info: info},
		)
	case 130824:
		return decodePGNCandidates(info, payload,
			&BGKeyValueData{Info: info},
			&MaretronAnnunciator{Info: info},
			&MercuryEngineKeyValueData{Info: info},
		)
	case 130825:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn130825{Info: info},
			&MaretronDataInstanceChannelCorrelation{Info: info},
			&MercuryCommandResponse{Info: info},
			&MercuryCruiseControlData{Info: info},
			&NavicoAlarm{Info: info},
		)
	case 130826:
		return decodePGNCandidates(info, payload,
			&BepMarineProprietaryPgn130826{Info: info},
			&MaretronSwitchIndicatorStatus{Info: info},
			&MercuryBamDigitalDataProxy{Info: info},
		)
	case 130827:
		return decodePGNCandidates(info, payload,
			&LowranceUnknown{Info: info},
		)
	case 130828:
		return decodePGNCandidates(info, payload,
			&MaretronDometicHvacControlStatus{Info: info},
			&SimnetSetSerialNumber{Info: info},
		)
	case 130829:
		return decodePGNCandidates(info, payload,
			&MercuryEngineStatus{Info: info},
		)
	case 130830:
		return decodePGNCandidates(info, payload,
			&MaretronDometicHvacStatus{Info: info},
			&SuzukiEngineData{Info: info},
		)
	case 130831:
		return decodePGNCandidates(info, payload,
			&MaretronUniversalConfigurationFp{Info: info},
			&SuzukiEngineAndStorageDeviceConfig{Info: info},
		)
	case 130832:
		return decodePGNCandidates(info, payload,
			&MaretronVesselOperatingMode{Info: info},
			&SimnetFuelUsedHighResolution{Info: info},
		)
	case 130833:
		return decodePGNCandidates(info, payload,
			&BGUserAndRemoteRename{Info: info},
			&FurunoShipParametersAndAntennaPosition{Info: info},
			&MaretronVesselDataRecorderStatus{Info: info},
		)
	case 130834:
		return decodePGNCandidates(info, payload,
			&FurunoSpeedCalculationPosition{Info: info},
			&MaretronSmsStatus{Info: info},
			&SimnetEngineAndTankConfiguration{Info: info},
		)
	case 130835:
		return decodePGNCandidates(info, payload,
			&MaretronSmsTextMessage{Info: info},
			&SimnetSetEngineAndTankConfiguration{Info: info},
		)
	case 130836:
		return decodePGNCandidates(info, payload,
			&MaretronSwitchStatusCounter{Info: info},
			&SimnetFluidLevelSensorConfiguration{Info: info},
		)
	case 130837:
		return decodePGNCandidates(info, payload,
			&MaretronSwitchStatusTimer{Info: info},
			&SimnetFuelFlowTurbineConfiguration{Info: info},
			&SuzukiEngineSensorData{Info: info},
		)
	case 130838:
		return decodePGNCandidates(info, payload,
			&MaretronBnwas{Info: info},
			&SimnetFluidLevelWarning{Info: info},
			&SuzukiFuelManagement{Info: info},
		)
	case 130839:
		return decodePGNCandidates(info, payload,
			&SimnetPressureSensorConfiguration{Info: info},
		)
	case 130840:
		return decodePGNCandidates(info, payload,
			&MaretronGenericSensor{Info: info},
			&SimnetDataSourceSelection{Info: info},
		)
	case 130841:
		return decodePGNCandidates(info, payload,
			&MaretronCanFrameForwarding{Info: info},
		)
	case 130842:
		return decodePGNCandidates(info, payload,
			&FurunoSixDegreesOfFreedomMovement{Info: info},
			&MaretronWindlassOperatingStatus{Info: info},
			&SimnetAisClassBStaticDataMsg24PartA{Info: info},
			&SimnetAisClassBStaticDataMsg24PartB{Info: info},
		)
	case 130843:
		return decodePGNCandidates(info, payload,
			&FurunoHeelAngleRollInformation{Info: info},
			&MaretronWindlassControlCommand{Info: info},
			&SimnetSonarStatusFrequencyAndDspVoltage{Info: info},
		)
	case 130844:
		return decodePGNCandidates(info, payload,
			&CarlingProprietary{Info: info},
		)
	case 130845:
		return decodePGNCandidates(info, payload,
			&FurunoMultiSatsInViewExtended{Info: info},
			&MaretronDcEnergy{Info: info},
			&SimnetKeyValue{Info: info},
		)
	case 130846:
		return decodePGNCandidates(info, payload,
			&FurunoMotionSensorStatusExtended{Info: info},
			&MaretronBatteryAmpHourRecord{Info: info},
			&SimnetParameterSet{Info: info},
		)
	case 130847:
		return decodePGNCandidates(info, payload,
			&NavicoAsciiIdentifier{Info: info},
			&SeatalkNodeStatistics{Info: info},
		)
	case 130848:
		return decodePGNCandidates(info, payload,
			&SeatalkWaypointInformation{Info: info},
		)
	case 130849:
		return decodePGNCandidates(info, payload,
			&NavicoProprietaryFp{Info: info},
		)
	case 130850:
		return decodePGNCandidates(info, payload,
			&SimnetApCommand{Info: info},
			&SimnetAlarm{Info: info},
			&SimnetCommandApChangeCourse{Info: info},
			&SimnetCommandApFollowUp{Info: info},
			&SimnetCommandApHeading{Info: info},
			&SimnetCommandApNav{Info: info},
			&SimnetCommandApNodrift{Info: info},
			&SimnetCommandApStandby{Info: info},
			&SimnetCommandApTack{Info: info},
			&SimnetCommandApWind{Info: info},
			&SimnetEvent{Info: info},
			&SimnetEventCommandTimer{Info: info},
		)
	case 130851:
		return decodePGNCandidates(info, payload,
			&SimnetApCommandReply{Info: info},
			&SimnetApCommandReplyChangeCourse{Info: info},
		)
	case 130852:
		return decodePGNCandidates(info, payload,
			&NavicoProprietary2Fp{Info: info},
		)
	case 130856:
		return decodePGNCandidates(info, payload,
			&SimnetAlarmMessage{Info: info},
		)
	case 130860:
		return decodePGNCandidates(info, payload,
			&SimnetApUnknown4{Info: info},
		)
	case 130861:
		return decodePGNCandidates(info, payload,
			&SimradEngineData{Info: info},
		)
	case 130880:
		return decodePGNCandidates(info, payload,
			&AirmarAdditionalWeatherData{Info: info},
		)
	case 130881:
		return decodePGNCandidates(info, payload,
			&AirmarHeaterControl{Info: info},
		)
	case 130900:
		return decodePGNCandidates(info, payload,
			&XantrexAcStatus{Info: info},
		)
	case 130910:
		return decodePGNCandidates(info, payload,
			&XantrexDcSourceConfigurationStatus{Info: info},
		)
	case 130911:
		return decodePGNCandidates(info, payload,
			&XantrexAcOutputConfigurationStatus{Info: info},
		)
	case 130912:
		return decodePGNCandidates(info, payload,
			&XantrexChargerConfigurationStatus{Info: info},
		)
	case 130913:
		return decodePGNCandidates(info, payload,
			&XantrexAcInputConfigurationStatus{Info: info},
		)
	case 130918:
		return decodePGNCandidates(info, payload,
			&SeatalkRouteInformation{Info: info},
		)
	case 130921:
		return decodePGNCandidates(info, payload,
			&CarlingBreakerStatusAndConfiguration{Info: info},
		)
	case 130939:
		return decodePGNCandidates(info, payload,
			&LumishoreLightControl{Info: info},
		)
	case 130944:
		return decodePGNCandidates(info, payload,
			&AirmarPost{Info: info},
		)
	case 130945:
		return decodePGNCandidates(info, payload,
			&YamahaEngineData{Info: info},
		)
	case 130946:
		return decodePGNCandidates(info, payload,
			&YamahaEngineData2{Info: info},
		)
	case 130947:
		return decodePGNCandidates(info, payload,
			&YamahaEngineData3{Info: info},
		)
	case 130951:
		return decodePGNCandidates(info, payload,
			&YamahaEngineData4{Info: info},
		)
	case 131008:
		return decodePGNCandidates(info, payload,
			&YamahaEngineData5{Info: info},
		)
	case 131011:
		return decodePGNCandidates(info, payload,
			&YamahaEngineData6{Info: info},
		)
	case 131012:
		return decodePGNCandidates(info, payload,
			&YamahaEngineData7{Info: info},
		)
	default:
		return nil, fmt.Errorf("no PGN struct for %d", info.PGN)
	}
}

func decodePGNCandidates(info MessageInfo, payload []uint8, candidates ...PGN) (PGN, error) {
	var errs []error
	for _, candidate := range candidates {
		candidate.SetMessageInfo(info)
		if err := candidate.DecodePayload(payload); err != nil {
			errs = append(errs, err)
			continue
		}
		return candidate, nil
	}
	if len(errs) == 0 {
		return nil, fmt.Errorf("no PGN struct for %d", info.PGN)
	}
	return nil, fmt.Errorf("no matching PGN struct for %d: %w", info.PGN, errors.Join(errs...))
}
