// Code generated by PGN generator; DO NOT EDIT.
// Source schema 2.5.0 version 7.1.0.

package pgn

type DiverseYachtServicesLoadCell struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Instance         *uint64     `json:"instance,omitempty" n2k:"4"`
	LoadCell         *uint64     `json:"loadCell,omitempty" n2k:"6"`
}

func (m *DiverseYachtServicesLoadCell) PGNNumber() uint32               { return 65293 }
func (m *DiverseYachtServicesLoadCell) MessageInfo() MessageInfo        { return m.Info }
func (m *DiverseYachtServicesLoadCell) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *DiverseYachtServicesLoadCell) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *DiverseYachtServicesLoadCell) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *DiverseYachtServicesLoadCell) Clone() Message {
	if m == nil {
		return (*DiverseYachtServicesLoadCell)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Instance = clonePointer(m.Instance)
	copy.LoadCell = clonePointer(m.LoadCell)
	return &copy
}
