// Code generated by PGN catalog generator; DO NOT EDIT.
// Source schema 2.4.0 version 6.2.2.

package pgn

var generatedEnvironmentalConcreteDefinitions = map[string]generatedConcreteDefinition{
	pgnDescriptionKey(128267, "Water Depth"):                                                      {Id: "PgnWaterDepth", Decoder: DecodePgnWaterDepth, Encoder: encodePgnWaterDepthMsg},
	pgnDescriptionKey(128776, "Windlass Control Status"):                                          {Id: "PgnWindlassControlStatus", Decoder: DecodePgnWindlassControlStatus, Encoder: encodePgnWindlassControlStatusMsg},
	pgnDescriptionKey(128777, "Anchor Windlass Operating Status"):                                 {Id: "PgnAnchorWindlassOperatingStatus", Decoder: DecodePgnAnchorWindlassOperatingStatus, Encoder: encodePgnAnchorWindlassOperatingStatusMsg},
	pgnDescriptionKey(128778, "Anchor Windlass Monitoring Status"):                                {Id: "PgnAnchorWindlassMonitoringStatus", Decoder: DecodePgnAnchorWindlassMonitoringStatus, Encoder: encodePgnAnchorWindlassMonitoringStatusMsg},
	pgnDescriptionKey(129291, "Set & Drift, Rapid Update"):                                        {Id: "PgnSetDriftRapidUpdate", Decoder: DecodePgnSetDriftRapidUpdate, Encoder: encodePgnSetDriftRapidUpdateMsg},
	pgnDescriptionKey(130060, "Label"):                                                            {Id: "PgnLabel", Decoder: DecodePgnLabel, Encoder: encodePgnLabelMsg},
	pgnDescriptionKey(130061, "Channel Source Configuration"):                                     {Id: "PgnChannelSourceConfiguration", Decoder: DecodePgnChannelSourceConfiguration, Encoder: encodePgnChannelSourceConfigurationMsg},
	pgnDescriptionKey(130306, "Wind Data"):                                                        {Id: "PgnWindData", Decoder: DecodePgnWindData, Encoder: encodePgnWindDataMsg},
	pgnDescriptionKey(130310, "Environmental Parameters (obsolete)"):                              {Id: "PgnEnvironmentalParametersObsolete", Decoder: DecodePgnEnvironmentalParametersObsolete, Encoder: encodePgnEnvironmentalParametersObsoleteMsg},
	pgnDescriptionKey(130311, "Environmental Parameters"):                                         {Id: "PgnEnvironmentalParameters", Decoder: DecodePgnEnvironmentalParameters, Encoder: encodePgnEnvironmentalParametersMsg},
	pgnDescriptionKey(130312, "Temperature"):                                                      {Id: "PgnTemperature", Decoder: DecodePgnTemperature, Encoder: encodePgnTemperatureMsg},
	pgnDescriptionKey(130313, "Humidity"):                                                         {Id: "PgnHumidity", Decoder: DecodePgnHumidity, Encoder: encodePgnHumidityMsg},
	pgnDescriptionKey(130314, "Actual Pressure"):                                                  {Id: "PgnActualPressure", Decoder: DecodePgnActualPressure, Encoder: encodePgnActualPressureMsg},
	pgnDescriptionKey(130315, "Set Pressure"):                                                     {Id: "PgnSetPressure", Decoder: DecodePgnSetPressure, Encoder: encodePgnSetPressureMsg},
	pgnDescriptionKey(130316, "Temperature Extended Range"):                                       {Id: "PgnTemperatureExtendedRange", Decoder: DecodePgnTemperatureExtendedRange, Encoder: encodePgnTemperatureExtendedRangeMsg},
	pgnDescriptionKey(130320, "Tide Station Data"):                                                {Id: "PgnTideStationData", Decoder: DecodePgnTideStationData, Encoder: encodePgnTideStationDataMsg},
	pgnDescriptionKey(130321, "Salinity Station Data"):                                            {Id: "PgnSalinityStationData", Decoder: DecodePgnSalinityStationData, Encoder: encodePgnSalinityStationDataMsg},
	pgnDescriptionKey(130322, "Current Station Data"):                                             {Id: "PgnCurrentStationData", Decoder: DecodePgnCurrentStationData, Encoder: encodePgnCurrentStationDataMsg},
	pgnDescriptionKey(130323, "Meteorological Station Data"):                                      {Id: "PgnMeteorologicalStationData", Decoder: DecodePgnMeteorologicalStationData, Encoder: encodePgnMeteorologicalStationDataMsg},
	pgnDescriptionKey(130324, "Moored Buoy Station Data"):                                         {Id: "PgnMooredBuoyStationData", Decoder: DecodePgnMooredBuoyStationData, Encoder: encodePgnMooredBuoyStationDataMsg},
	pgnDescriptionKey(130568, "Entertainment - Diagnostic Status"):                                {Id: "PgnEntertainmentDiagnosticStatus", Decoder: DecodePgnEntertainmentDiagnosticStatus, Encoder: encodePgnEntertainmentDiagnosticStatusMsg},
	pgnDescriptionKey(130570, "Library Data File"):                                                {Id: "PgnLibraryDataFile", Decoder: DecodePgnLibraryDataFile, Encoder: encodePgnLibraryDataFileMsg},
	pgnDescriptionKey(130571, "Library Data Group"):                                               {Id: "PgnLibraryDataGroup", Decoder: DecodePgnLibraryDataGroup, Encoder: encodePgnLibraryDataGroupMsg},
	pgnDescriptionKey(130572, "Library Data Search"):                                              {Id: "PgnLibraryDataSearch", Decoder: DecodePgnLibraryDataSearch, Encoder: encodePgnLibraryDataSearchMsg},
	pgnDescriptionKey(130573, "Supported Source Data"):                                            {Id: "PgnSupportedSourceData", Decoder: DecodePgnSupportedSourceData, Encoder: encodePgnSupportedSourceDataMsg},
	pgnDescriptionKey(130574, "Supported Zone Data"):                                              {Id: "PgnSupportedZoneData", Decoder: DecodePgnSupportedZoneData, Encoder: encodePgnSupportedZoneDataMsg},
	pgnDescriptionKey(130575, "Entertainment - Parental Control Status"):                          {Id: "PgnEntertainmentParentalControlStatus", Decoder: DecodePgnEntertainmentParentalControlStatus, Encoder: encodePgnEntertainmentParentalControlStatusMsg},
	pgnDescriptionKey(130576, "Small Craft Status"):                                               {Id: "PgnSmallCraftStatus", Decoder: DecodePgnSmallCraftStatus, Encoder: encodePgnSmallCraftStatusMsg},
	pgnDescriptionKey(130578, "Vessel Speed Components"):                                          {Id: "PgnVesselSpeedComponents", Decoder: DecodePgnVesselSpeedComponents, Encoder: encodePgnVesselSpeedComponentsMsg},
	pgnDescriptionKey(130579, "System Configuration"):                                             {Id: "PgnSystemConfiguration", Decoder: DecodePgnSystemConfiguration, Encoder: encodePgnSystemConfigurationMsg},
	pgnDescriptionKey(130580, "System Configuration (deprecated)"):                                {Id: "PgnSystemConfigurationDeprecated", Decoder: DecodePgnSystemConfigurationDeprecated, Encoder: encodePgnSystemConfigurationDeprecatedMsg},
	pgnDescriptionKey(130581, "Zone Configuration (deprecated)"):                                  {Id: "PgnZoneConfigurationDeprecated", Decoder: DecodePgnZoneConfigurationDeprecated, Encoder: encodePgnZoneConfigurationDeprecatedMsg},
	pgnDescriptionKey(130582, "Zone Volume"):                                                      {Id: "PgnZoneVolume", Decoder: DecodePgnZoneVolume, Encoder: encodePgnZoneVolumeMsg},
	pgnDescriptionKey(130583, "Available Audio EQ presets"):                                       {Id: "PgnAvailableAudioEqPresets", Decoder: DecodePgnAvailableAudioEqPresets, Encoder: encodePgnAvailableAudioEqPresetsMsg},
	pgnDescriptionKey(130584, "Available Bluetooth addresses"):                                    {Id: "PgnAvailableBluetoothAddresses", Decoder: DecodePgnAvailableBluetoothAddresses, Encoder: encodePgnAvailableBluetoothAddressesMsg},
	pgnDescriptionKey(130585, "Bluetooth source status"):                                          {Id: "PgnBluetoothSourceStatus", Decoder: DecodePgnBluetoothSourceStatus, Encoder: encodePgnBluetoothSourceStatusMsg},
	pgnDescriptionKey(130586, "Zone Configuration"):                                               {Id: "PgnZoneConfiguration", Decoder: DecodePgnZoneConfiguration, Encoder: encodePgnZoneConfigurationMsg},
	pgnDescriptionKey(130816, "0x1FF00-0x1FFFF: Manufacturer Specific fast-packet non-addressed"): {Id: "PgnPgn0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed", Decoder: DecodePgnPgn0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed, Encoder: encodePgnPgn0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressedMsg},
}

type PgnWaterDepth struct {
	Info   MessageInfo `json:"info"`
	Sid    *uint64     `json:"sid,omitempty" n2k:"1"`
	Depth  *uint64     `json:"depth,omitempty" n2k:"2"`
	Offset *int64      `json:"offset,omitempty" n2k:"3"`
	Range  *uint64     `json:"range,omitempty" n2k:"4"`
}

func (m *PgnWaterDepth) PGNNumber() uint32 { return 128267 }
func DecodePgnWaterDepth(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnWaterDepth{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(128267, "Water Depth"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnWaterDepth(val *PgnWaterDepth) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(128267, "Water Depth"), val)
}
func encodePgnWaterDepthMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnWaterDepth)
	if !ok {
		return nil, generatedConcreteTypeError("PgnWaterDepth", v)
	}
	return EncodePgnWaterDepth(val)
}

type PgnWindlassControlStatus struct {
	Info                     MessageInfo `json:"info"`
	Sid                      *uint64     `json:"sid,omitempty" n2k:"1"`
	WindlassId               *uint64     `json:"windlassId,omitempty" n2k:"2"`
	WindlassDirectionControl *uint64     `json:"windlassDirectionControl,omitempty" n2k:"3"`
	AnchorDockingControl     *uint64     `json:"anchorDockingControl,omitempty" n2k:"4"`
	SpeedControlType         *uint64     `json:"speedControlType,omitempty" n2k:"5"`
	SpeedControl             []uint8     `json:"speedControl,omitempty" n2k:"7"`
	PowerEnable              *uint64     `json:"powerEnable,omitempty" n2k:"8"`
	MechanicalLock           *uint64     `json:"mechanicalLock,omitempty" n2k:"9"`
	DeckAndAnchorWash        *uint64     `json:"deckAndAnchorWash,omitempty" n2k:"10"`
	AnchorLight              *uint64     `json:"anchorLight,omitempty" n2k:"11"`
	CommandTimeout           *uint64     `json:"commandTimeout,omitempty" n2k:"12"`
	WindlassControlEvents    *uint64     `json:"windlassControlEvents,omitempty" n2k:"13"`
}

func (m *PgnWindlassControlStatus) PGNNumber() uint32 { return 128776 }
func DecodePgnWindlassControlStatus(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnWindlassControlStatus{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(128776, "Windlass Control Status"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnWindlassControlStatus(val *PgnWindlassControlStatus) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(128776, "Windlass Control Status"), val)
}
func encodePgnWindlassControlStatusMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnWindlassControlStatus)
	if !ok {
		return nil, generatedConcreteTypeError("PgnWindlassControlStatus", v)
	}
	return EncodePgnWindlassControlStatus(val)
}

type PgnAnchorWindlassOperatingStatus struct {
	Info                     MessageInfo `json:"info"`
	Sid                      *uint64     `json:"sid,omitempty" n2k:"1"`
	WindlassId               *uint64     `json:"windlassId,omitempty" n2k:"2"`
	WindlassDirectionControl *uint64     `json:"windlassDirectionControl,omitempty" n2k:"3"`
	WindlassMotionStatus     *uint64     `json:"windlassMotionStatus,omitempty" n2k:"4"`
	RodeTypeStatus           *uint64     `json:"rodeTypeStatus,omitempty" n2k:"5"`
	RodeCounterValue         *uint64     `json:"rodeCounterValue,omitempty" n2k:"7"`
	WindlassLineSpeed        *uint64     `json:"windlassLineSpeed,omitempty" n2k:"8"`
	AnchorDockingStatus      *uint64     `json:"anchorDockingStatus,omitempty" n2k:"9"`
	WindlassOperatingEvents  *uint64     `json:"windlassOperatingEvents,omitempty" n2k:"10"`
}

func (m *PgnAnchorWindlassOperatingStatus) PGNNumber() uint32 { return 128777 }
func DecodePgnAnchorWindlassOperatingStatus(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnAnchorWindlassOperatingStatus{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(128777, "Anchor Windlass Operating Status"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnAnchorWindlassOperatingStatus(val *PgnAnchorWindlassOperatingStatus) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(128777, "Anchor Windlass Operating Status"), val)
}
func encodePgnAnchorWindlassOperatingStatusMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnAnchorWindlassOperatingStatus)
	if !ok {
		return nil, generatedConcreteTypeError("PgnAnchorWindlassOperatingStatus", v)
	}
	return EncodePgnAnchorWindlassOperatingStatus(val)
}

type PgnAnchorWindlassMonitoringStatus struct {
	Info                     MessageInfo `json:"info"`
	Sid                      *uint64     `json:"sid,omitempty" n2k:"1"`
	WindlassId               *uint64     `json:"windlassId,omitempty" n2k:"2"`
	WindlassMonitoringEvents *uint64     `json:"windlassMonitoringEvents,omitempty" n2k:"3"`
	ControllerVoltage        *uint64     `json:"controllerVoltage,omitempty" n2k:"4"`
	MotorCurrent             *uint64     `json:"motorCurrent,omitempty" n2k:"5"`
	TotalMotorTime           *uint64     `json:"totalMotorTime,omitempty" n2k:"6"`
}

func (m *PgnAnchorWindlassMonitoringStatus) PGNNumber() uint32 { return 128778 }
func DecodePgnAnchorWindlassMonitoringStatus(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnAnchorWindlassMonitoringStatus{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(128778, "Anchor Windlass Monitoring Status"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnAnchorWindlassMonitoringStatus(val *PgnAnchorWindlassMonitoringStatus) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(128778, "Anchor Windlass Monitoring Status"), val)
}
func encodePgnAnchorWindlassMonitoringStatusMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnAnchorWindlassMonitoringStatus)
	if !ok {
		return nil, generatedConcreteTypeError("PgnAnchorWindlassMonitoringStatus", v)
	}
	return EncodePgnAnchorWindlassMonitoringStatus(val)
}

type PgnSetDriftRapidUpdate struct {
	Info         MessageInfo `json:"info"`
	Sid          *uint64     `json:"sid,omitempty" n2k:"1"`
	SetReference *uint64     `json:"setReference,omitempty" n2k:"2"`
	Set          *uint64     `json:"set,omitempty" n2k:"4"`
	Drift        *uint64     `json:"drift,omitempty" n2k:"5"`
}

func (m *PgnSetDriftRapidUpdate) PGNNumber() uint32 { return 129291 }
func DecodePgnSetDriftRapidUpdate(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnSetDriftRapidUpdate{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(129291, "Set & Drift, Rapid Update"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnSetDriftRapidUpdate(val *PgnSetDriftRapidUpdate) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(129291, "Set & Drift, Rapid Update"), val)
}
func encodePgnSetDriftRapidUpdateMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnSetDriftRapidUpdate)
	if !ok {
		return nil, generatedConcreteTypeError("PgnSetDriftRapidUpdate", v)
	}
	return EncodePgnSetDriftRapidUpdate(val)
}

type PgnLabel struct {
	Info                            MessageInfo `json:"info"`
	HardwareChannelId               *uint64     `json:"hardwareChannelId,omitempty" n2k:"1"`
	Pgn                             *uint64     `json:"pgn,omitempty" n2k:"2"`
	DataSourceInstanceFieldNumber   *uint64     `json:"dataSourceInstanceFieldNumber,omitempty" n2k:"3"`
	DataSourceInstanceValue         *uint64     `json:"dataSourceInstanceValue,omitempty" n2k:"4"`
	SecondaryEnumerationFieldNumber *uint64     `json:"secondaryEnumerationFieldNumber,omitempty" n2k:"5"`
	SecondaryEnumerationFieldValue  *uint64     `json:"secondaryEnumerationFieldValue,omitempty" n2k:"6"`
	ParameterFieldNumber            *uint64     `json:"parameterFieldNumber,omitempty" n2k:"7"`
	Label                           string      `json:"label,omitempty" n2k:"8"`
}

func (m *PgnLabel) PGNNumber() uint32 { return 130060 }
func DecodePgnLabel(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnLabel{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130060, "Label"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnLabel(val *PgnLabel) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130060, "Label"), val)
}
func encodePgnLabelMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnLabel)
	if !ok {
		return nil, generatedConcreteTypeError("PgnLabel", v)
	}
	return EncodePgnLabel(val)
}

type PgnChannelSourceConfiguration struct {
	Info                            MessageInfo `json:"info"`
	DataSourceChannelId             *uint64     `json:"dataSourceChannelId,omitempty" n2k:"1"`
	SourceSelectionStatus           *uint64     `json:"sourceSelectionStatus,omitempty" n2k:"2"`
	NameSelectionCriteriaMask       []uint8     `json:"nameSelectionCriteriaMask,omitempty" n2k:"4"`
	SourceName                      *uint64     `json:"sourceName,omitempty" n2k:"5"`
	Pgn                             *uint64     `json:"pgn,omitempty" n2k:"6"`
	DataSourceInstanceFieldNumber   *uint64     `json:"dataSourceInstanceFieldNumber,omitempty" n2k:"7"`
	DataSourceInstanceValue         *uint64     `json:"dataSourceInstanceValue,omitempty" n2k:"8"`
	SecondaryEnumerationFieldNumber *uint64     `json:"secondaryEnumerationFieldNumber,omitempty" n2k:"9"`
	SecondaryEnumerationFieldValue  *uint64     `json:"secondaryEnumerationFieldValue,omitempty" n2k:"10"`
	ParameterFieldNumber            *uint64     `json:"parameterFieldNumber,omitempty" n2k:"11"`
}

func (m *PgnChannelSourceConfiguration) PGNNumber() uint32 { return 130061 }
func DecodePgnChannelSourceConfiguration(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnChannelSourceConfiguration{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130061, "Channel Source Configuration"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnChannelSourceConfiguration(val *PgnChannelSourceConfiguration) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130061, "Channel Source Configuration"), val)
}
func encodePgnChannelSourceConfigurationMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnChannelSourceConfiguration)
	if !ok {
		return nil, generatedConcreteTypeError("PgnChannelSourceConfiguration", v)
	}
	return EncodePgnChannelSourceConfiguration(val)
}

type PgnWindData struct {
	Info      MessageInfo `json:"info"`
	Sid       *uint64     `json:"sid,omitempty" n2k:"1"`
	WindSpeed *uint64     `json:"windSpeed,omitempty" n2k:"2"`
	WindAngle *uint64     `json:"windAngle,omitempty" n2k:"3"`
	Reference *uint64     `json:"reference,omitempty" n2k:"4"`
}

func (m *PgnWindData) PGNNumber() uint32 { return 130306 }
func DecodePgnWindData(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnWindData{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130306, "Wind Data"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnWindData(val *PgnWindData) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130306, "Wind Data"), val)
}
func encodePgnWindDataMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnWindData)
	if !ok {
		return nil, generatedConcreteTypeError("PgnWindData", v)
	}
	return EncodePgnWindData(val)
}

type PgnEnvironmentalParametersObsolete struct {
	Info                         MessageInfo `json:"info"`
	Sid                          *uint64     `json:"sid,omitempty" n2k:"1"`
	WaterTemperature             *uint64     `json:"waterTemperature,omitempty" n2k:"2"`
	OutsideAmbientAirTemperature *uint64     `json:"outsideAmbientAirTemperature,omitempty" n2k:"3"`
	AtmosphericPressure          *uint64     `json:"atmosphericPressure,omitempty" n2k:"4"`
}

func (m *PgnEnvironmentalParametersObsolete) PGNNumber() uint32 { return 130310 }
func DecodePgnEnvironmentalParametersObsolete(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnEnvironmentalParametersObsolete{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130310, "Environmental Parameters (obsolete)"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnEnvironmentalParametersObsolete(val *PgnEnvironmentalParametersObsolete) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130310, "Environmental Parameters (obsolete)"), val)
}
func encodePgnEnvironmentalParametersObsoleteMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnEnvironmentalParametersObsolete)
	if !ok {
		return nil, generatedConcreteTypeError("PgnEnvironmentalParametersObsolete", v)
	}
	return EncodePgnEnvironmentalParametersObsolete(val)
}

type PgnEnvironmentalParameters struct {
	Info                MessageInfo `json:"info"`
	Sid                 *uint64     `json:"sid,omitempty" n2k:"1"`
	TemperatureSource   *uint64     `json:"temperatureSource,omitempty" n2k:"2"`
	HumiditySource      *uint64     `json:"humiditySource,omitempty" n2k:"3"`
	Temperature         *uint64     `json:"temperature,omitempty" n2k:"4"`
	Humidity            *int64      `json:"humidity,omitempty" n2k:"5"`
	AtmosphericPressure *uint64     `json:"atmosphericPressure,omitempty" n2k:"6"`
}

func (m *PgnEnvironmentalParameters) PGNNumber() uint32 { return 130311 }
func DecodePgnEnvironmentalParameters(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnEnvironmentalParameters{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130311, "Environmental Parameters"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnEnvironmentalParameters(val *PgnEnvironmentalParameters) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130311, "Environmental Parameters"), val)
}
func encodePgnEnvironmentalParametersMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnEnvironmentalParameters)
	if !ok {
		return nil, generatedConcreteTypeError("PgnEnvironmentalParameters", v)
	}
	return EncodePgnEnvironmentalParameters(val)
}

type PgnTemperature struct {
	Info              MessageInfo `json:"info"`
	Sid               *uint64     `json:"sid,omitempty" n2k:"1"`
	Instance          *uint64     `json:"instance,omitempty" n2k:"2"`
	Source            *uint64     `json:"source,omitempty" n2k:"3"`
	ActualTemperature *uint64     `json:"actualTemperature,omitempty" n2k:"4"`
	SetTemperature    *uint64     `json:"setTemperature,omitempty" n2k:"5"`
}

func (m *PgnTemperature) PGNNumber() uint32 { return 130312 }
func DecodePgnTemperature(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnTemperature{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130312, "Temperature"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnTemperature(val *PgnTemperature) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130312, "Temperature"), val)
}
func encodePgnTemperatureMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnTemperature)
	if !ok {
		return nil, generatedConcreteTypeError("PgnTemperature", v)
	}
	return EncodePgnTemperature(val)
}

type PgnHumidity struct {
	Info           MessageInfo `json:"info"`
	Sid            *uint64     `json:"sid,omitempty" n2k:"1"`
	Instance       *uint64     `json:"instance,omitempty" n2k:"2"`
	Source         *uint64     `json:"source,omitempty" n2k:"3"`
	ActualHumidity *int64      `json:"actualHumidity,omitempty" n2k:"4"`
	SetHumidity    *int64      `json:"setHumidity,omitempty" n2k:"5"`
}

func (m *PgnHumidity) PGNNumber() uint32 { return 130313 }
func DecodePgnHumidity(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnHumidity{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130313, "Humidity"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnHumidity(val *PgnHumidity) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130313, "Humidity"), val)
}
func encodePgnHumidityMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnHumidity)
	if !ok {
		return nil, generatedConcreteTypeError("PgnHumidity", v)
	}
	return EncodePgnHumidity(val)
}

type PgnActualPressure struct {
	Info     MessageInfo `json:"info"`
	Sid      *uint64     `json:"sid,omitempty" n2k:"1"`
	Instance *uint64     `json:"instance,omitempty" n2k:"2"`
	Source   *uint64     `json:"source,omitempty" n2k:"3"`
	Pressure *int64      `json:"pressure,omitempty" n2k:"4"`
}

func (m *PgnActualPressure) PGNNumber() uint32 { return 130314 }
func DecodePgnActualPressure(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnActualPressure{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130314, "Actual Pressure"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnActualPressure(val *PgnActualPressure) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130314, "Actual Pressure"), val)
}
func encodePgnActualPressureMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnActualPressure)
	if !ok {
		return nil, generatedConcreteTypeError("PgnActualPressure", v)
	}
	return EncodePgnActualPressure(val)
}

type PgnSetPressure struct {
	Info     MessageInfo `json:"info"`
	Sid      *uint64     `json:"sid,omitempty" n2k:"1"`
	Instance *uint64     `json:"instance,omitempty" n2k:"2"`
	Source   *uint64     `json:"source,omitempty" n2k:"3"`
	Pressure *int64      `json:"pressure,omitempty" n2k:"4"`
}

func (m *PgnSetPressure) PGNNumber() uint32 { return 130315 }
func DecodePgnSetPressure(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnSetPressure{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130315, "Set Pressure"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnSetPressure(val *PgnSetPressure) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130315, "Set Pressure"), val)
}
func encodePgnSetPressureMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnSetPressure)
	if !ok {
		return nil, generatedConcreteTypeError("PgnSetPressure", v)
	}
	return EncodePgnSetPressure(val)
}

type PgnTemperatureExtendedRange struct {
	Info           MessageInfo `json:"info"`
	Sid            *uint64     `json:"sid,omitempty" n2k:"1"`
	Instance       *uint64     `json:"instance,omitempty" n2k:"2"`
	Source         *uint64     `json:"source,omitempty" n2k:"3"`
	Temperature    *uint64     `json:"temperature,omitempty" n2k:"4"`
	SetTemperature *uint64     `json:"setTemperature,omitempty" n2k:"5"`
}

func (m *PgnTemperatureExtendedRange) PGNNumber() uint32 { return 130316 }
func DecodePgnTemperatureExtendedRange(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnTemperatureExtendedRange{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130316, "Temperature Extended Range"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnTemperatureExtendedRange(val *PgnTemperatureExtendedRange) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130316, "Temperature Extended Range"), val)
}
func encodePgnTemperatureExtendedRangeMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnTemperatureExtendedRange)
	if !ok {
		return nil, generatedConcreteTypeError("PgnTemperatureExtendedRange", v)
	}
	return EncodePgnTemperatureExtendedRange(val)
}

type PgnTideStationData struct {
	Info                       MessageInfo `json:"info"`
	Mode                       *uint64     `json:"mode,omitempty" n2k:"1"`
	TideTendency               *uint64     `json:"tideTendency,omitempty" n2k:"2"`
	MeasurementDate            *uint64     `json:"measurementDate,omitempty" n2k:"4"`
	MeasurementTime            *uint64     `json:"measurementTime,omitempty" n2k:"5"`
	StationLatitude            *int64      `json:"stationLatitude,omitempty" n2k:"6"`
	StationLongitude           *int64      `json:"stationLongitude,omitempty" n2k:"7"`
	TideLevel                  *int64      `json:"tideLevel,omitempty" n2k:"8"`
	TideLevelStandardDeviation *uint64     `json:"tideLevelStandardDeviation,omitempty" n2k:"9"`
	StationId                  string      `json:"stationId,omitempty" n2k:"10"`
	StationName                string      `json:"stationName,omitempty" n2k:"11"`
}

func (m *PgnTideStationData) PGNNumber() uint32 { return 130320 }
func DecodePgnTideStationData(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnTideStationData{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130320, "Tide Station Data"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnTideStationData(val *PgnTideStationData) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130320, "Tide Station Data"), val)
}
func encodePgnTideStationDataMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnTideStationData)
	if !ok {
		return nil, generatedConcreteTypeError("PgnTideStationData", v)
	}
	return EncodePgnTideStationData(val)
}

type PgnSalinityStationData struct {
	Info             MessageInfo `json:"info"`
	Mode             *uint64     `json:"mode,omitempty" n2k:"1"`
	MeasurementDate  *uint64     `json:"measurementDate,omitempty" n2k:"3"`
	MeasurementTime  *uint64     `json:"measurementTime,omitempty" n2k:"4"`
	StationLatitude  *int64      `json:"stationLatitude,omitempty" n2k:"5"`
	StationLongitude *int64      `json:"stationLongitude,omitempty" n2k:"6"`
	Salinity         *float32    `json:"salinity,omitempty" n2k:"7"`
	WaterTemperature *uint64     `json:"waterTemperature,omitempty" n2k:"8"`
	StationId        string      `json:"stationId,omitempty" n2k:"9"`
	StationName      string      `json:"stationName,omitempty" n2k:"10"`
}

func (m *PgnSalinityStationData) PGNNumber() uint32 { return 130321 }
func DecodePgnSalinityStationData(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnSalinityStationData{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130321, "Salinity Station Data"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnSalinityStationData(val *PgnSalinityStationData) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130321, "Salinity Station Data"), val)
}
func encodePgnSalinityStationDataMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnSalinityStationData)
	if !ok {
		return nil, generatedConcreteTypeError("PgnSalinityStationData", v)
	}
	return EncodePgnSalinityStationData(val)
}

type PgnCurrentStationData struct {
	Info                 MessageInfo `json:"info"`
	Mode                 *uint64     `json:"mode,omitempty" n2k:"1"`
	State                *uint64     `json:"state,omitempty" n2k:"2"`
	MeasurementDate      *uint64     `json:"measurementDate,omitempty" n2k:"4"`
	MeasurementTime      *uint64     `json:"measurementTime,omitempty" n2k:"5"`
	StationLatitude      *int64      `json:"stationLatitude,omitempty" n2k:"6"`
	StationLongitude     *int64      `json:"stationLongitude,omitempty" n2k:"7"`
	MeasurementDepth     *uint64     `json:"measurementDepth,omitempty" n2k:"8"`
	CurrentSpeed         *uint64     `json:"currentSpeed,omitempty" n2k:"9"`
	CurrentFlowDirection *uint64     `json:"currentFlowDirection,omitempty" n2k:"10"`
	WaterTemperature     *uint64     `json:"waterTemperature,omitempty" n2k:"11"`
	StationId            string      `json:"stationId,omitempty" n2k:"12"`
	StationName          string      `json:"stationName,omitempty" n2k:"13"`
}

func (m *PgnCurrentStationData) PGNNumber() uint32 { return 130322 }
func DecodePgnCurrentStationData(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnCurrentStationData{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130322, "Current Station Data"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnCurrentStationData(val *PgnCurrentStationData) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130322, "Current Station Data"), val)
}
func encodePgnCurrentStationDataMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnCurrentStationData)
	if !ok {
		return nil, generatedConcreteTypeError("PgnCurrentStationData", v)
	}
	return EncodePgnCurrentStationData(val)
}

type PgnMeteorologicalStationData struct {
	Info                MessageInfo `json:"info"`
	Mode                *uint64     `json:"mode,omitempty" n2k:"1"`
	MeasurementDate     *uint64     `json:"measurementDate,omitempty" n2k:"3"`
	MeasurementTime     *uint64     `json:"measurementTime,omitempty" n2k:"4"`
	StationLatitude     *int64      `json:"stationLatitude,omitempty" n2k:"5"`
	StationLongitude    *int64      `json:"stationLongitude,omitempty" n2k:"6"`
	WindSpeed           *uint64     `json:"windSpeed,omitempty" n2k:"7"`
	WindDirection       *uint64     `json:"windDirection,omitempty" n2k:"8"`
	WindReference       *uint64     `json:"windReference,omitempty" n2k:"9"`
	WindGusts           *uint64     `json:"windGusts,omitempty" n2k:"11"`
	AtmosphericPressure *uint64     `json:"atmosphericPressure,omitempty" n2k:"12"`
	AmbientTemperature  *uint64     `json:"ambientTemperature,omitempty" n2k:"13"`
	StationId           string      `json:"stationId,omitempty" n2k:"14"`
	StationName         string      `json:"stationName,omitempty" n2k:"15"`
}

func (m *PgnMeteorologicalStationData) PGNNumber() uint32 { return 130323 }
func DecodePgnMeteorologicalStationData(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnMeteorologicalStationData{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130323, "Meteorological Station Data"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnMeteorologicalStationData(val *PgnMeteorologicalStationData) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130323, "Meteorological Station Data"), val)
}
func encodePgnMeteorologicalStationDataMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnMeteorologicalStationData)
	if !ok {
		return nil, generatedConcreteTypeError("PgnMeteorologicalStationData", v)
	}
	return EncodePgnMeteorologicalStationData(val)
}

type PgnMooredBuoyStationData struct {
	Info                 MessageInfo `json:"info"`
	Mode                 *uint64     `json:"mode,omitempty" n2k:"1"`
	MeasurementDate      *uint64     `json:"measurementDate,omitempty" n2k:"3"`
	MeasurementTime      *uint64     `json:"measurementTime,omitempty" n2k:"4"`
	StationLatitude      *int64      `json:"stationLatitude,omitempty" n2k:"5"`
	StationLongitude     *int64      `json:"stationLongitude,omitempty" n2k:"6"`
	WindSpeed            *uint64     `json:"windSpeed,omitempty" n2k:"7"`
	WindDirection        *uint64     `json:"windDirection,omitempty" n2k:"8"`
	WindReference        *uint64     `json:"windReference,omitempty" n2k:"9"`
	WindGusts            *uint64     `json:"windGusts,omitempty" n2k:"11"`
	WaveHeight           *uint64     `json:"waveHeight,omitempty" n2k:"12"`
	DominantWavePeriod   *uint64     `json:"dominantWavePeriod,omitempty" n2k:"13"`
	AtmosphericPressure  *uint64     `json:"atmosphericPressure,omitempty" n2k:"14"`
	PressureTendencyRate *int64      `json:"pressureTendencyRate,omitempty" n2k:"15"`
	AirTemperature       *uint64     `json:"airTemperature,omitempty" n2k:"16"`
	WaterTemperature     *uint64     `json:"waterTemperature,omitempty" n2k:"17"`
	StationId            string      `json:"stationId,omitempty" n2k:"18"`
}

func (m *PgnMooredBuoyStationData) PGNNumber() uint32 { return 130324 }
func DecodePgnMooredBuoyStationData(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnMooredBuoyStationData{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130324, "Moored Buoy Station Data"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnMooredBuoyStationData(val *PgnMooredBuoyStationData) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130324, "Moored Buoy Station Data"), val)
}
func encodePgnMooredBuoyStationDataMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnMooredBuoyStationData)
	if !ok {
		return nil, generatedConcreteTypeError("PgnMooredBuoyStationData", v)
	}
	return EncodePgnMooredBuoyStationData(val)
}

type PgnEntertainmentDiagnosticStatus struct {
	Info           MessageInfo `json:"info"`
	Source         *uint64     `json:"source,omitempty" n2k:"1"`
	Number         *uint64     `json:"number,omitempty" n2k:"2"`
	DiagnosticMode *uint64     `json:"diagnosticMode,omitempty" n2k:"3"`
	DiagnosticData string      `json:"diagnosticData,omitempty" n2k:"5"`
}

func (m *PgnEntertainmentDiagnosticStatus) PGNNumber() uint32 { return 130568 }
func DecodePgnEntertainmentDiagnosticStatus(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnEntertainmentDiagnosticStatus{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130568, "Entertainment - Diagnostic Status"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnEntertainmentDiagnosticStatus(val *PgnEntertainmentDiagnosticStatus) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130568, "Entertainment - Diagnostic Status"), val)
}
func encodePgnEntertainmentDiagnosticStatusMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnEntertainmentDiagnosticStatus)
	if !ok {
		return nil, generatedConcreteTypeError("PgnEntertainmentDiagnosticStatus", v)
	}
	return EncodePgnEntertainmentDiagnosticStatus(val)
}

type PgnLibraryDataFile struct {
	Info           MessageInfo `json:"info"`
	Source         *uint64     `json:"source,omitempty" n2k:"1"`
	Number         *uint64     `json:"number,omitempty" n2k:"2"`
	Id             *uint64     `json:"id,omitempty" n2k:"3"`
	Type           *uint64     `json:"type,omitempty" n2k:"4"`
	Name           string      `json:"name,omitempty" n2k:"5"`
	Track          *uint64     `json:"track,omitempty" n2k:"6"`
	Station        *uint64     `json:"station,omitempty" n2k:"7"`
	Favorite       *uint64     `json:"favorite,omitempty" n2k:"8"`
	RadioFrequency *uint64     `json:"radioFrequency,omitempty" n2k:"9"`
	HdFrequency    *uint64     `json:"hdFrequency,omitempty" n2k:"10"`
	Zone           *uint64     `json:"zone,omitempty" n2k:"11"`
	InPlayQueue    *uint64     `json:"inPlayQueue,omitempty" n2k:"12"`
	Locked         *uint64     `json:"locked,omitempty" n2k:"13"`
	ArtistName     string      `json:"artistName,omitempty" n2k:"15"`
	AlbumName      string      `json:"albumName,omitempty" n2k:"16"`
	StationName    string      `json:"stationName,omitempty" n2k:"17"`
}

func (m *PgnLibraryDataFile) PGNNumber() uint32 { return 130570 }
func DecodePgnLibraryDataFile(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnLibraryDataFile{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130570, "Library Data File"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnLibraryDataFile(val *PgnLibraryDataFile) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130570, "Library Data File"), val)
}
func encodePgnLibraryDataFileMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnLibraryDataFile)
	if !ok {
		return nil, generatedConcreteTypeError("PgnLibraryDataFile", v)
	}
	return EncodePgnLibraryDataFile(val)
}

type PgnLibraryDataGroup struct {
	Info         MessageInfo `json:"info"`
	Source       *uint64     `json:"source,omitempty" n2k:"1"`
	Number       *uint64     `json:"number,omitempty" n2k:"2"`
	Type         *uint64     `json:"type,omitempty" n2k:"3"`
	Zone         *uint64     `json:"zone,omitempty" n2k:"4"`
	GroupId      *uint64     `json:"groupId,omitempty" n2k:"5"`
	IdOffset     *uint64     `json:"idOffset,omitempty" n2k:"6"`
	IdCount      *uint64     `json:"idCount,omitempty" n2k:"7"`
	TotalIdCount *uint64     `json:"totalIdCount,omitempty" n2k:"8"`
	IdType       *uint64     `json:"idType,omitempty" n2k:"9"`
	Id           *uint64     `json:"id,omitempty" n2k:"10"`
	Name         string      `json:"name,omitempty" n2k:"11"`
	Artist       string      `json:"artist,omitempty" n2k:"12"`
}

func (m *PgnLibraryDataGroup) PGNNumber() uint32 { return 130571 }
func DecodePgnLibraryDataGroup(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnLibraryDataGroup{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130571, "Library Data Group"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnLibraryDataGroup(val *PgnLibraryDataGroup) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130571, "Library Data Group"), val)
}
func encodePgnLibraryDataGroupMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnLibraryDataGroup)
	if !ok {
		return nil, generatedConcreteTypeError("PgnLibraryDataGroup", v)
	}
	return EncodePgnLibraryDataGroup(val)
}

type PgnLibraryDataSearch struct {
	Info       MessageInfo `json:"info"`
	Source     *uint64     `json:"source,omitempty" n2k:"1"`
	Number     *uint64     `json:"number,omitempty" n2k:"2"`
	GroupId    *uint64     `json:"groupId,omitempty" n2k:"3"`
	GroupType1 *uint64     `json:"groupType1,omitempty" n2k:"4"`
	GroupName1 string      `json:"groupName1,omitempty" n2k:"5"`
	GroupType2 *uint64     `json:"groupType2,omitempty" n2k:"6"`
	GroupName2 string      `json:"groupName2,omitempty" n2k:"7"`
	GroupType3 *uint64     `json:"groupType3,omitempty" n2k:"8"`
	GroupName3 string      `json:"groupName3,omitempty" n2k:"9"`
}

func (m *PgnLibraryDataSearch) PGNNumber() uint32 { return 130572 }
func DecodePgnLibraryDataSearch(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnLibraryDataSearch{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130572, "Library Data Search"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnLibraryDataSearch(val *PgnLibraryDataSearch) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130572, "Library Data Search"), val)
}
func encodePgnLibraryDataSearchMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnLibraryDataSearch)
	if !ok {
		return nil, generatedConcreteTypeError("PgnLibraryDataSearch", v)
	}
	return EncodePgnLibraryDataSearch(val)
}

type PgnSupportedSourceData struct {
	Info           MessageInfo `json:"info"`
	IdOffset       *uint64     `json:"idOffset,omitempty" n2k:"1"`
	IdCount        *uint64     `json:"idCount,omitempty" n2k:"2"`
	TotalIdCount   *uint64     `json:"totalIdCount,omitempty" n2k:"3"`
	Id             *uint64     `json:"id,omitempty" n2k:"4"`
	Source         *uint64     `json:"source,omitempty" n2k:"5"`
	Number         *uint64     `json:"number,omitempty" n2k:"6"`
	Name           string      `json:"name,omitempty" n2k:"7"`
	PlaySupport    *uint64     `json:"playSupport,omitempty" n2k:"8"`
	BrowseSupport  *uint64     `json:"browseSupport,omitempty" n2k:"9"`
	ThumbsSupport  *uint64     `json:"thumbsSupport,omitempty" n2k:"10"`
	Connected      *uint64     `json:"connected,omitempty" n2k:"11"`
	RepeatSupport  *uint64     `json:"repeatSupport,omitempty" n2k:"12"`
	ShuffleSupport *uint64     `json:"shuffleSupport,omitempty" n2k:"13"`
}

func (m *PgnSupportedSourceData) PGNNumber() uint32 { return 130573 }
func DecodePgnSupportedSourceData(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnSupportedSourceData{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130573, "Supported Source Data"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnSupportedSourceData(val *PgnSupportedSourceData) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130573, "Supported Source Data"), val)
}
func encodePgnSupportedSourceDataMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnSupportedSourceData)
	if !ok {
		return nil, generatedConcreteTypeError("PgnSupportedSourceData", v)
	}
	return EncodePgnSupportedSourceData(val)
}

type PgnSupportedZoneData struct {
	Info           MessageInfo `json:"info"`
	FirstZoneId    *uint64     `json:"firstZoneId,omitempty" n2k:"1"`
	ZoneCount      *uint64     `json:"zoneCount,omitempty" n2k:"2"`
	TotalZoneCount *uint64     `json:"totalZoneCount,omitempty" n2k:"3"`
	ZoneId         *uint64     `json:"zoneId,omitempty" n2k:"4"`
	Name           string      `json:"name,omitempty" n2k:"5"`
}

func (m *PgnSupportedZoneData) PGNNumber() uint32 { return 130574 }
func DecodePgnSupportedZoneData(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnSupportedZoneData{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130574, "Supported Zone Data"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnSupportedZoneData(val *PgnSupportedZoneData) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130574, "Supported Zone Data"), val)
}
func encodePgnSupportedZoneDataMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnSupportedZoneData)
	if !ok {
		return nil, generatedConcreteTypeError("PgnSupportedZoneData", v)
	}
	return EncodePgnSupportedZoneData(val)
}

type PgnEntertainmentParentalControlStatus struct {
	Info           MessageInfo `json:"info"`
	Source         *uint64     `json:"source,omitempty" n2k:"1"`
	Number         *uint64     `json:"number,omitempty" n2k:"2"`
	LockType       *uint64     `json:"lockType,omitempty" n2k:"3"`
	LockStatus     *uint64     `json:"lockStatus,omitempty" n2k:"4"`
	FileStationId  *uint64     `json:"fileStationId,omitempty" n2k:"6"`
	CurrentPincode string      `json:"currentPincode,omitempty" n2k:"7"`
	NewPincode     string      `json:"newPincode,omitempty" n2k:"8"`
}

func (m *PgnEntertainmentParentalControlStatus) PGNNumber() uint32 { return 130575 }
func DecodePgnEntertainmentParentalControlStatus(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnEntertainmentParentalControlStatus{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130575, "Entertainment - Parental Control Status"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnEntertainmentParentalControlStatus(val *PgnEntertainmentParentalControlStatus) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130575, "Entertainment - Parental Control Status"), val)
}
func encodePgnEntertainmentParentalControlStatusMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnEntertainmentParentalControlStatus)
	if !ok {
		return nil, generatedConcreteTypeError("PgnEntertainmentParentalControlStatus", v)
	}
	return EncodePgnEntertainmentParentalControlStatus(val)
}

type PgnSmallCraftStatus struct {
	Info             MessageInfo `json:"info"`
	PortTrimTab      *int64      `json:"portTrimTab,omitempty" n2k:"1"`
	StarboardTrimTab *int64      `json:"starboardTrimTab,omitempty" n2k:"2"`
}

func (m *PgnSmallCraftStatus) PGNNumber() uint32 { return 130576 }
func DecodePgnSmallCraftStatus(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnSmallCraftStatus{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130576, "Small Craft Status"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnSmallCraftStatus(val *PgnSmallCraftStatus) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130576, "Small Craft Status"), val)
}
func encodePgnSmallCraftStatusMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnSmallCraftStatus)
	if !ok {
		return nil, generatedConcreteTypeError("PgnSmallCraftStatus", v)
	}
	return EncodePgnSmallCraftStatus(val)
}

type PgnVesselSpeedComponents struct {
	Info                              MessageInfo `json:"info"`
	LongitudinalSpeedWaterReferenced  *int64      `json:"longitudinalSpeedWaterReferenced,omitempty" n2k:"1"`
	TransverseSpeedWaterReferenced    *int64      `json:"transverseSpeedWaterReferenced,omitempty" n2k:"2"`
	LongitudinalSpeedGroundReferenced *int64      `json:"longitudinalSpeedGroundReferenced,omitempty" n2k:"3"`
	TransverseSpeedGroundReferenced   *int64      `json:"transverseSpeedGroundReferenced,omitempty" n2k:"4"`
	SternSpeedWaterReferenced         *int64      `json:"sternSpeedWaterReferenced,omitempty" n2k:"5"`
	SternSpeedGroundReferenced        *int64      `json:"sternSpeedGroundReferenced,omitempty" n2k:"6"`
}

func (m *PgnVesselSpeedComponents) PGNNumber() uint32 { return 130578 }
func DecodePgnVesselSpeedComponents(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnVesselSpeedComponents{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130578, "Vessel Speed Components"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnVesselSpeedComponents(val *PgnVesselSpeedComponents) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130578, "Vessel Speed Components"), val)
}
func encodePgnVesselSpeedComponentsMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnVesselSpeedComponents)
	if !ok {
		return nil, generatedConcreteTypeError("PgnVesselSpeedComponents", v)
	}
	return EncodePgnVesselSpeedComponents(val)
}

type PgnSystemConfiguration struct {
	Info            MessageInfo `json:"info"`
	Power           *uint64     `json:"power,omitempty" n2k:"1"`
	DefaultSettings *uint64     `json:"defaultSettings,omitempty" n2k:"2"`
	TunerRegions    *uint64     `json:"tunerRegions,omitempty" n2k:"3"`
	MaxFavorites    *uint64     `json:"maxFavorites,omitempty" n2k:"4"`
	VideoProtocols  *uint64     `json:"videoProtocols,omitempty" n2k:"5"`
}

func (m *PgnSystemConfiguration) PGNNumber() uint32 { return 130579 }
func DecodePgnSystemConfiguration(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnSystemConfiguration{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130579, "System Configuration"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnSystemConfiguration(val *PgnSystemConfiguration) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130579, "System Configuration"), val)
}
func encodePgnSystemConfigurationMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnSystemConfiguration)
	if !ok {
		return nil, generatedConcreteTypeError("PgnSystemConfiguration", v)
	}
	return EncodePgnSystemConfiguration(val)
}

type PgnSystemConfigurationDeprecated struct {
	Info            MessageInfo `json:"info"`
	Power           *uint64     `json:"power,omitempty" n2k:"1"`
	DefaultSettings *uint64     `json:"defaultSettings,omitempty" n2k:"2"`
	TunerRegions    *uint64     `json:"tunerRegions,omitempty" n2k:"3"`
	MaxFavorites    *uint64     `json:"maxFavorites,omitempty" n2k:"4"`
}

func (m *PgnSystemConfigurationDeprecated) PGNNumber() uint32 { return 130580 }
func DecodePgnSystemConfigurationDeprecated(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnSystemConfigurationDeprecated{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130580, "System Configuration (deprecated)"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnSystemConfigurationDeprecated(val *PgnSystemConfigurationDeprecated) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130580, "System Configuration (deprecated)"), val)
}
func encodePgnSystemConfigurationDeprecatedMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnSystemConfigurationDeprecated)
	if !ok {
		return nil, generatedConcreteTypeError("PgnSystemConfigurationDeprecated", v)
	}
	return EncodePgnSystemConfigurationDeprecated(val)
}

type PgnZoneConfigurationDeprecated struct {
	Info           MessageInfo `json:"info"`
	FirstZoneId    *uint64     `json:"firstZoneId,omitempty" n2k:"1"`
	ZoneCount      *uint64     `json:"zoneCount,omitempty" n2k:"2"`
	TotalZoneCount *uint64     `json:"totalZoneCount,omitempty" n2k:"3"`
	ZoneId         *uint64     `json:"zoneId,omitempty" n2k:"4"`
	ZoneName       string      `json:"zoneName,omitempty" n2k:"5"`
}

func (m *PgnZoneConfigurationDeprecated) PGNNumber() uint32 { return 130581 }
func DecodePgnZoneConfigurationDeprecated(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnZoneConfigurationDeprecated{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130581, "Zone Configuration (deprecated)"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnZoneConfigurationDeprecated(val *PgnZoneConfigurationDeprecated) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130581, "Zone Configuration (deprecated)"), val)
}
func encodePgnZoneConfigurationDeprecatedMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnZoneConfigurationDeprecated)
	if !ok {
		return nil, generatedConcreteTypeError("PgnZoneConfigurationDeprecated", v)
	}
	return EncodePgnZoneConfigurationDeprecated(val)
}

type PgnZoneVolume struct {
	Info         MessageInfo `json:"info"`
	ZoneId       *uint64     `json:"zoneId,omitempty" n2k:"1"`
	Volume       *uint64     `json:"volume,omitempty" n2k:"2"`
	VolumeChange *uint64     `json:"volumeChange,omitempty" n2k:"3"`
	Mute         *uint64     `json:"mute,omitempty" n2k:"4"`
	Channel      *uint64     `json:"channel,omitempty" n2k:"6"`
}

func (m *PgnZoneVolume) PGNNumber() uint32 { return 130582 }
func DecodePgnZoneVolume(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnZoneVolume{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130582, "Zone Volume"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnZoneVolume(val *PgnZoneVolume) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130582, "Zone Volume"), val)
}
func encodePgnZoneVolumeMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnZoneVolume)
	if !ok {
		return nil, generatedConcreteTypeError("PgnZoneVolume", v)
	}
	return EncodePgnZoneVolume(val)
}

type PgnAvailableAudioEqPresets struct {
	Info             MessageInfo `json:"info"`
	FirstPreset      *uint64     `json:"firstPreset,omitempty" n2k:"1"`
	PresetCount      *uint64     `json:"presetCount,omitempty" n2k:"2"`
	TotalPresetCount *uint64     `json:"totalPresetCount,omitempty" n2k:"3"`
	PresetType       *uint64     `json:"presetType,omitempty" n2k:"4"`
	PresetName       string      `json:"presetName,omitempty" n2k:"5"`
}

func (m *PgnAvailableAudioEqPresets) PGNNumber() uint32 { return 130583 }
func DecodePgnAvailableAudioEqPresets(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnAvailableAudioEqPresets{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130583, "Available Audio EQ presets"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnAvailableAudioEqPresets(val *PgnAvailableAudioEqPresets) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130583, "Available Audio EQ presets"), val)
}
func encodePgnAvailableAudioEqPresetsMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnAvailableAudioEqPresets)
	if !ok {
		return nil, generatedConcreteTypeError("PgnAvailableAudioEqPresets", v)
	}
	return EncodePgnAvailableAudioEqPresets(val)
}

type PgnAvailableBluetoothAddresses struct {
	Info              MessageInfo `json:"info"`
	FirstAddress      *uint64     `json:"firstAddress,omitempty" n2k:"1"`
	AddressCount      *uint64     `json:"addressCount,omitempty" n2k:"2"`
	TotalAddressCount *uint64     `json:"totalAddressCount,omitempty" n2k:"3"`
	BluetoothAddress  []uint8     `json:"bluetoothAddress,omitempty" n2k:"4"`
	Status            *uint64     `json:"status,omitempty" n2k:"5"`
	DeviceName        string      `json:"deviceName,omitempty" n2k:"6"`
	SignalStrength    *uint64     `json:"signalStrength,omitempty" n2k:"7"`
}

func (m *PgnAvailableBluetoothAddresses) PGNNumber() uint32 { return 130584 }
func DecodePgnAvailableBluetoothAddresses(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnAvailableBluetoothAddresses{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130584, "Available Bluetooth addresses"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnAvailableBluetoothAddresses(val *PgnAvailableBluetoothAddresses) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130584, "Available Bluetooth addresses"), val)
}
func encodePgnAvailableBluetoothAddressesMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnAvailableBluetoothAddresses)
	if !ok {
		return nil, generatedConcreteTypeError("PgnAvailableBluetoothAddresses", v)
	}
	return EncodePgnAvailableBluetoothAddresses(val)
}

type PgnBluetoothSourceStatus struct {
	Info             MessageInfo `json:"info"`
	SourceNumber     *uint64     `json:"sourceNumber,omitempty" n2k:"1"`
	Status           *uint64     `json:"status,omitempty" n2k:"2"`
	ForgetDevice     *uint64     `json:"forgetDevice,omitempty" n2k:"3"`
	Discovering      *uint64     `json:"discovering,omitempty" n2k:"4"`
	BluetoothAddress []uint8     `json:"bluetoothAddress,omitempty" n2k:"5"`
}

func (m *PgnBluetoothSourceStatus) PGNNumber() uint32 { return 130585 }
func DecodePgnBluetoothSourceStatus(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnBluetoothSourceStatus{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130585, "Bluetooth source status"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnBluetoothSourceStatus(val *PgnBluetoothSourceStatus) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130585, "Bluetooth source status"), val)
}
func encodePgnBluetoothSourceStatusMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnBluetoothSourceStatus)
	if !ok {
		return nil, generatedConcreteTypeError("PgnBluetoothSourceStatus", v)
	}
	return EncodePgnBluetoothSourceStatus(val)
}

type PgnZoneConfiguration struct {
	Info                    MessageInfo `json:"info"`
	ZoneId                  *uint64     `json:"zoneId,omitempty" n2k:"1"`
	VolumeLimit             *uint64     `json:"volumeLimit,omitempty" n2k:"2"`
	Fade                    *int64      `json:"fade,omitempty" n2k:"3"`
	Balance                 *int64      `json:"balance,omitempty" n2k:"4"`
	SubVolume               *uint64     `json:"subVolume,omitempty" n2k:"5"`
	EqTreble                *int64      `json:"eqTreble,omitempty" n2k:"6"`
	EqMidRange              *int64      `json:"eqMidRange,omitempty" n2k:"7"`
	EqBass                  *int64      `json:"eqBass,omitempty" n2k:"8"`
	PresetType              *uint64     `json:"presetType,omitempty" n2k:"9"`
	AudioFilter             *uint64     `json:"audioFilter,omitempty" n2k:"10"`
	HighPassFilterFrequency *uint64     `json:"highPassFilterFrequency,omitempty" n2k:"11"`
	LowPassFilterFrequency  *uint64     `json:"lowPassFilterFrequency,omitempty" n2k:"12"`
	Channel                 *uint64     `json:"channel,omitempty" n2k:"13"`
}

func (m *PgnZoneConfiguration) PGNNumber() uint32 { return 130586 }
func DecodePgnZoneConfiguration(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnZoneConfiguration{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130586, "Zone Configuration"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnZoneConfiguration(val *PgnZoneConfiguration) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130586, "Zone Configuration"), val)
}
func encodePgnZoneConfigurationMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnZoneConfiguration)
	if !ok {
		return nil, generatedConcreteTypeError("PgnZoneConfiguration", v)
	}
	return EncodePgnZoneConfiguration(val)
}

type PgnPgn0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Data             []uint8     `json:"data,omitempty" n2k:"4"`
}

func (m *PgnPgn0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed) PGNNumber() uint32 {
	return 130816
}
func DecodePgnPgn0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed(Info MessageInfo, stream *PGNDataStream) (Message, error) {
	val := &PgnPgn0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed{Info: Info}
	if err := decodeGeneratedConcrete(generatedConcreteInfo(130816, "0x1FF00-0x1FFFF: Manufacturer Specific fast-packet non-addressed"), val, stream); err != nil {
		return nil, err
	}
	return val, nil
}

func EncodePgnPgn0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed(val *PgnPgn0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed) ([]byte, error) {
	return encodeGeneratedConcrete(generatedConcreteInfo(130816, "0x1FF00-0x1FFFF: Manufacturer Specific fast-packet non-addressed"), val)
}
func encodePgnPgn0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressedMsg(v Message) ([]byte, error) {
	val, ok := v.(*PgnPgn0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed)
	if !ok {
		return nil, generatedConcreteTypeError("PgnPgn0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed", v)
	}
	return EncodePgnPgn0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed(val)
}
