// Code generated by PGN generator; DO NOT EDIT.
// Source schema 2.5.0 version 7.1.0.

package pgn

import "math"

type WaterDepth struct {
	Info   MessageInfo `json:"info"`
	Sid    *uint64     `json:"sid,omitempty" n2k:"1"`
	Depth  *uint64     `json:"depth,omitempty" n2k:"2"`
	Offset *int64      `json:"offset,omitempty" n2k:"3"`
	Range  *uint64     `json:"range,omitempty" n2k:"4"`
}

func (m *WaterDepth) PGNNumber() uint32                   { return 128267 }
func (m *WaterDepth) MessageInfo() MessageInfo            { return m.Info }
func (m *WaterDepth) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *WaterDepth) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *WaterDepth) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// DepthValue returns Depth as a physical value in m (value = raw * 0.01).
// The bool is false when Depth is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *WaterDepth) DepthValue() (float64, bool) {
	if m.Depth == nil {
		return 0, false
	}
	return float64(*m.Depth) * 0.01, true
}

// SetDepthValue sets Depth from a physical value in m, rounded to the nearest
// wire tick of 0.01.
func (m *WaterDepth) SetDepthValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.Depth = &raw
}

// OffsetValue returns Offset as a physical value in m (value = raw * 0.001).
// The bool is false when Offset is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *WaterDepth) OffsetValue() (float64, bool) {
	if m.Offset == nil {
		return 0, false
	}
	return float64(*m.Offset) * 0.001, true
}

// SetOffsetValue sets Offset from a physical value in m, rounded to the nearest
// wire tick of 0.001.
func (m *WaterDepth) SetOffsetValue(v float64) {
	raw := int64(math.Round(v / 0.001))
	m.Offset = &raw
}

// RangeValue returns Range as a physical value in m (value = raw * 10).
// The bool is false when Range is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *WaterDepth) RangeValue() (float64, bool) {
	if m.Range == nil {
		return 0, false
	}
	return float64(*m.Range) * 10, true
}

// SetRangeValue sets Range from a physical value in m, rounded to the nearest
// wire tick of 10.
func (m *WaterDepth) SetRangeValue(v float64) {
	raw := uint64(math.Round(v / 10))
	m.Range = &raw
}

type WindlassControlStatus struct {
	Info                     MessageInfo `json:"info"`
	Sid                      *uint64     `json:"sid,omitempty" n2k:"1"`
	WindlassId               *uint64     `json:"windlassId,omitempty" n2k:"2"`
	WindlassDirectionControl *uint64     `json:"windlassDirectionControl,omitempty" n2k:"3"`
	AnchorDockingControl     *uint64     `json:"anchorDockingControl,omitempty" n2k:"4"`
	SpeedControlType         *uint64     `json:"speedControlType,omitempty" n2k:"5"`
	SpeedControl             []uint8     `json:"speedControl,omitempty" n2k:"7"`
	PowerEnable              *uint64     `json:"powerEnable,omitempty" n2k:"8"`
	MechanicalLock           *uint64     `json:"mechanicalLock,omitempty" n2k:"9"`
	DeckAndAnchorWash        *uint64     `json:"deckAndAnchorWash,omitempty" n2k:"10"`
	AnchorLight              *uint64     `json:"anchorLight,omitempty" n2k:"11"`
	CommandTimeout           *uint64     `json:"commandTimeout,omitempty" n2k:"12"`
	WindlassControlEvents    *uint64     `json:"windlassControlEvents,omitempty" n2k:"13"`
}

func (m *WindlassControlStatus) PGNNumber() uint32                   { return 128776 }
func (m *WindlassControlStatus) MessageInfo() MessageInfo            { return m.Info }
func (m *WindlassControlStatus) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *WindlassControlStatus) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *WindlassControlStatus) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// CommandTimeoutValue returns CommandTimeout as a physical value in s (value = raw * 0.005).
// The bool is false when CommandTimeout is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *WindlassControlStatus) CommandTimeoutValue() (float64, bool) {
	if m.CommandTimeout == nil {
		return 0, false
	}
	return float64(*m.CommandTimeout) * 0.005, true
}

// SetCommandTimeoutValue sets CommandTimeout from a physical value in s, rounded to the nearest
// wire tick of 0.005.
func (m *WindlassControlStatus) SetCommandTimeoutValue(v float64) {
	raw := uint64(math.Round(v / 0.005))
	m.CommandTimeout = &raw
}

type AnchorWindlassOperatingStatus struct {
	Info                     MessageInfo `json:"info"`
	Sid                      *uint64     `json:"sid,omitempty" n2k:"1"`
	WindlassId               *uint64     `json:"windlassId,omitempty" n2k:"2"`
	WindlassDirectionControl *uint64     `json:"windlassDirectionControl,omitempty" n2k:"3"`
	WindlassMotionStatus     *uint64     `json:"windlassMotionStatus,omitempty" n2k:"4"`
	RodeTypeStatus           *uint64     `json:"rodeTypeStatus,omitempty" n2k:"5"`
	RodeCounterValue         *uint64     `json:"rodeCounterValue,omitempty" n2k:"7"`
	WindlassLineSpeed        *uint64     `json:"windlassLineSpeed,omitempty" n2k:"8"`
	AnchorDockingStatus      *uint64     `json:"anchorDockingStatus,omitempty" n2k:"9"`
	WindlassOperatingEvents  *uint64     `json:"windlassOperatingEvents,omitempty" n2k:"10"`
}

func (m *AnchorWindlassOperatingStatus) PGNNumber() uint32               { return 128777 }
func (m *AnchorWindlassOperatingStatus) MessageInfo() MessageInfo        { return m.Info }
func (m *AnchorWindlassOperatingStatus) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *AnchorWindlassOperatingStatus) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *AnchorWindlassOperatingStatus) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// RodeCounterValueValue returns RodeCounterValue as a physical value in m (value = raw * 0.1).
// The bool is false when RodeCounterValue is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *AnchorWindlassOperatingStatus) RodeCounterValueValue() (float64, bool) {
	if m.RodeCounterValue == nil {
		return 0, false
	}
	return float64(*m.RodeCounterValue) * 0.1, true
}

// SetRodeCounterValueValue sets RodeCounterValue from a physical value in m, rounded to the nearest
// wire tick of 0.1.
func (m *AnchorWindlassOperatingStatus) SetRodeCounterValueValue(v float64) {
	raw := uint64(math.Round(v / 0.1))
	m.RodeCounterValue = &raw
}

// WindlassLineSpeedValue returns WindlassLineSpeed as a physical value in m/s (value = raw * 0.01).
// The bool is false when WindlassLineSpeed is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *AnchorWindlassOperatingStatus) WindlassLineSpeedValue() (float64, bool) {
	if m.WindlassLineSpeed == nil {
		return 0, false
	}
	return float64(*m.WindlassLineSpeed) * 0.01, true
}

// SetWindlassLineSpeedValue sets WindlassLineSpeed from a physical value in m/s, rounded to the nearest
// wire tick of 0.01.
func (m *AnchorWindlassOperatingStatus) SetWindlassLineSpeedValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.WindlassLineSpeed = &raw
}

type AnchorWindlassMonitoringStatus struct {
	Info                     MessageInfo `json:"info"`
	Sid                      *uint64     `json:"sid,omitempty" n2k:"1"`
	WindlassId               *uint64     `json:"windlassId,omitempty" n2k:"2"`
	WindlassMonitoringEvents *uint64     `json:"windlassMonitoringEvents,omitempty" n2k:"3"`
	ControllerVoltage        *uint64     `json:"controllerVoltage,omitempty" n2k:"4"`
	MotorCurrent             *uint64     `json:"motorCurrent,omitempty" n2k:"5"`
	TotalMotorTime           *uint64     `json:"totalMotorTime,omitempty" n2k:"6"`
}

func (m *AnchorWindlassMonitoringStatus) PGNNumber() uint32               { return 128778 }
func (m *AnchorWindlassMonitoringStatus) MessageInfo() MessageInfo        { return m.Info }
func (m *AnchorWindlassMonitoringStatus) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *AnchorWindlassMonitoringStatus) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *AnchorWindlassMonitoringStatus) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// ControllerVoltageValue returns ControllerVoltage as a physical value in V (value = raw * 0.2).
// The bool is false when ControllerVoltage is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *AnchorWindlassMonitoringStatus) ControllerVoltageValue() (float64, bool) {
	if m.ControllerVoltage == nil {
		return 0, false
	}
	return float64(*m.ControllerVoltage) * 0.2, true
}

// SetControllerVoltageValue sets ControllerVoltage from a physical value in V, rounded to the nearest
// wire tick of 0.2.
func (m *AnchorWindlassMonitoringStatus) SetControllerVoltageValue(v float64) {
	raw := uint64(math.Round(v / 0.2))
	m.ControllerVoltage = &raw
}

// MotorCurrentValue returns MotorCurrent as a physical value in A (value = raw).
// The bool is false when MotorCurrent is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *AnchorWindlassMonitoringStatus) MotorCurrentValue() (float64, bool) {
	if m.MotorCurrent == nil {
		return 0, false
	}
	return float64(*m.MotorCurrent), true
}

// SetMotorCurrentValue sets MotorCurrent from a physical value in A, rounded to the nearest
// wire tick of 1.
func (m *AnchorWindlassMonitoringStatus) SetMotorCurrentValue(v float64) {
	raw := uint64(math.Round(v))
	m.MotorCurrent = &raw
}

// TotalMotorTimeValue returns TotalMotorTime as a physical value in s (value = raw * 60).
// The bool is false when TotalMotorTime is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *AnchorWindlassMonitoringStatus) TotalMotorTimeValue() (float64, bool) {
	if m.TotalMotorTime == nil {
		return 0, false
	}
	return float64(*m.TotalMotorTime) * 60, true
}

// SetTotalMotorTimeValue sets TotalMotorTime from a physical value in s, rounded to the nearest
// wire tick of 60.
func (m *AnchorWindlassMonitoringStatus) SetTotalMotorTimeValue(v float64) {
	raw := uint64(math.Round(v / 60))
	m.TotalMotorTime = &raw
}

type SetDriftRapidUpdate struct {
	Info         MessageInfo `json:"info"`
	Sid          *uint64     `json:"sid,omitempty" n2k:"1"`
	SetReference *uint64     `json:"setReference,omitempty" n2k:"2"`
	Set          *uint64     `json:"set,omitempty" n2k:"4"`
	Drift        *uint64     `json:"drift,omitempty" n2k:"5"`
}

func (m *SetDriftRapidUpdate) PGNNumber() uint32                   { return 129291 }
func (m *SetDriftRapidUpdate) MessageInfo() MessageInfo            { return m.Info }
func (m *SetDriftRapidUpdate) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *SetDriftRapidUpdate) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *SetDriftRapidUpdate) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// SetValue returns Set as a physical value in rad (value = raw * 0.0001).
// The bool is false when Set is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *SetDriftRapidUpdate) SetValue() (float64, bool) {
	if m.Set == nil {
		return 0, false
	}
	return float64(*m.Set) * 0.0001, true
}

// SetSetValue sets Set from a physical value in rad, rounded to the nearest
// wire tick of 0.0001.
func (m *SetDriftRapidUpdate) SetSetValue(v float64) {
	raw := uint64(math.Round(v / 0.0001))
	m.Set = &raw
}

// DriftValue returns Drift as a physical value in m/s (value = raw * 0.01).
// The bool is false when Drift is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *SetDriftRapidUpdate) DriftValue() (float64, bool) {
	if m.Drift == nil {
		return 0, false
	}
	return float64(*m.Drift) * 0.01, true
}

// SetDriftValue sets Drift from a physical value in m/s, rounded to the nearest
// wire tick of 0.01.
func (m *SetDriftRapidUpdate) SetDriftValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.Drift = &raw
}

type Label struct {
	Info                            MessageInfo `json:"info"`
	HardwareChannelId               *uint64     `json:"hardwareChannelId,omitempty" n2k:"1"`
	Pgn                             *uint64     `json:"pgn,omitempty" n2k:"2"`
	DataSourceInstanceFieldNumber   *uint64     `json:"dataSourceInstanceFieldNumber,omitempty" n2k:"3"`
	DataSourceInstanceValue         *uint64     `json:"dataSourceInstanceValue,omitempty" n2k:"4"`
	SecondaryEnumerationFieldNumber *uint64     `json:"secondaryEnumerationFieldNumber,omitempty" n2k:"5"`
	SecondaryEnumerationFieldValue  *uint64     `json:"secondaryEnumerationFieldValue,omitempty" n2k:"6"`
	ParameterFieldNumber            *uint64     `json:"parameterFieldNumber,omitempty" n2k:"7"`
	Label                           string      `json:"label,omitempty" n2k:"8"`
}

func (m *Label) PGNNumber() uint32                   { return 130060 }
func (m *Label) MessageInfo() MessageInfo            { return m.Info }
func (m *Label) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *Label) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *Label) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

type ChannelSourceConfiguration struct {
	Info                            MessageInfo `json:"info"`
	DataSourceChannelId             *uint64     `json:"dataSourceChannelId,omitempty" n2k:"1"`
	SourceSelectionStatus           *uint64     `json:"sourceSelectionStatus,omitempty" n2k:"2"`
	NameSelectionCriteriaMask       []uint8     `json:"nameSelectionCriteriaMask,omitempty" n2k:"4"`
	SourceName                      *uint64     `json:"sourceName,omitempty" n2k:"5"`
	Pgn                             *uint64     `json:"pgn,omitempty" n2k:"6"`
	DataSourceInstanceFieldNumber   *uint64     `json:"dataSourceInstanceFieldNumber,omitempty" n2k:"7"`
	DataSourceInstanceValue         *uint64     `json:"dataSourceInstanceValue,omitempty" n2k:"8"`
	SecondaryEnumerationFieldNumber *uint64     `json:"secondaryEnumerationFieldNumber,omitempty" n2k:"9"`
	SecondaryEnumerationFieldValue  *uint64     `json:"secondaryEnumerationFieldValue,omitempty" n2k:"10"`
	ParameterFieldNumber            *uint64     `json:"parameterFieldNumber,omitempty" n2k:"11"`
}

func (m *ChannelSourceConfiguration) PGNNumber() uint32               { return 130061 }
func (m *ChannelSourceConfiguration) MessageInfo() MessageInfo        { return m.Info }
func (m *ChannelSourceConfiguration) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *ChannelSourceConfiguration) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *ChannelSourceConfiguration) EncodePayload() ([]uint8, error) { return encodeFields(m) }

type WindData struct {
	Info      MessageInfo `json:"info"`
	Sid       *uint64     `json:"sid,omitempty" n2k:"1"`
	WindSpeed *uint64     `json:"windSpeed,omitempty" n2k:"2"`
	WindAngle *uint64     `json:"windAngle,omitempty" n2k:"3"`
	Reference *uint64     `json:"reference,omitempty" n2k:"4"`
}

func (m *WindData) PGNNumber() uint32                   { return 130306 }
func (m *WindData) MessageInfo() MessageInfo            { return m.Info }
func (m *WindData) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *WindData) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *WindData) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// WindSpeedValue returns WindSpeed as a physical value in m/s (value = raw * 0.01).
// The bool is false when WindSpeed is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *WindData) WindSpeedValue() (float64, bool) {
	if m.WindSpeed == nil {
		return 0, false
	}
	return float64(*m.WindSpeed) * 0.01, true
}

// SetWindSpeedValue sets WindSpeed from a physical value in m/s, rounded to the nearest
// wire tick of 0.01.
func (m *WindData) SetWindSpeedValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.WindSpeed = &raw
}

// WindAngleValue returns WindAngle as a physical value in rad (value = raw * 0.0001).
// The bool is false when WindAngle is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *WindData) WindAngleValue() (float64, bool) {
	if m.WindAngle == nil {
		return 0, false
	}
	return float64(*m.WindAngle) * 0.0001, true
}

// SetWindAngleValue sets WindAngle from a physical value in rad, rounded to the nearest
// wire tick of 0.0001.
func (m *WindData) SetWindAngleValue(v float64) {
	raw := uint64(math.Round(v / 0.0001))
	m.WindAngle = &raw
}

type EnvironmentalParametersObsolete struct {
	Info                         MessageInfo `json:"info"`
	Sid                          *uint64     `json:"sid,omitempty" n2k:"1"`
	WaterTemperature             *uint64     `json:"waterTemperature,omitempty" n2k:"2"`
	OutsideAmbientAirTemperature *uint64     `json:"outsideAmbientAirTemperature,omitempty" n2k:"3"`
	AtmosphericPressure          *uint64     `json:"atmosphericPressure,omitempty" n2k:"4"`
}

func (m *EnvironmentalParametersObsolete) PGNNumber() uint32               { return 130310 }
func (m *EnvironmentalParametersObsolete) MessageInfo() MessageInfo        { return m.Info }
func (m *EnvironmentalParametersObsolete) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *EnvironmentalParametersObsolete) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *EnvironmentalParametersObsolete) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// WaterTemperatureValue returns WaterTemperature as a physical value in K (value = raw * 0.01).
// The bool is false when WaterTemperature is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *EnvironmentalParametersObsolete) WaterTemperatureValue() (float64, bool) {
	if m.WaterTemperature == nil {
		return 0, false
	}
	return float64(*m.WaterTemperature) * 0.01, true
}

// SetWaterTemperatureValue sets WaterTemperature from a physical value in K, rounded to the nearest
// wire tick of 0.01.
func (m *EnvironmentalParametersObsolete) SetWaterTemperatureValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.WaterTemperature = &raw
}

// OutsideAmbientAirTemperatureValue returns OutsideAmbientAirTemperature as a physical value in K (value = raw * 0.01).
// The bool is false when OutsideAmbientAirTemperature is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *EnvironmentalParametersObsolete) OutsideAmbientAirTemperatureValue() (float64, bool) {
	if m.OutsideAmbientAirTemperature == nil {
		return 0, false
	}
	return float64(*m.OutsideAmbientAirTemperature) * 0.01, true
}

// SetOutsideAmbientAirTemperatureValue sets OutsideAmbientAirTemperature from a physical value in K, rounded to the nearest
// wire tick of 0.01.
func (m *EnvironmentalParametersObsolete) SetOutsideAmbientAirTemperatureValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.OutsideAmbientAirTemperature = &raw
}

// AtmosphericPressureValue returns AtmosphericPressure as a physical value in Pa (value = raw * 100).
// The bool is false when AtmosphericPressure is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *EnvironmentalParametersObsolete) AtmosphericPressureValue() (float64, bool) {
	if m.AtmosphericPressure == nil {
		return 0, false
	}
	return float64(*m.AtmosphericPressure) * 100, true
}

// SetAtmosphericPressureValue sets AtmosphericPressure from a physical value in Pa, rounded to the nearest
// wire tick of 100.
func (m *EnvironmentalParametersObsolete) SetAtmosphericPressureValue(v float64) {
	raw := uint64(math.Round(v / 100))
	m.AtmosphericPressure = &raw
}

type EnvironmentalParameters struct {
	Info                MessageInfo `json:"info"`
	Sid                 *uint64     `json:"sid,omitempty" n2k:"1"`
	TemperatureSource   *uint64     `json:"temperatureSource,omitempty" n2k:"2"`
	HumiditySource      *uint64     `json:"humiditySource,omitempty" n2k:"3"`
	Temperature         *uint64     `json:"temperature,omitempty" n2k:"4"`
	Humidity            *int64      `json:"humidity,omitempty" n2k:"5"`
	AtmosphericPressure *uint64     `json:"atmosphericPressure,omitempty" n2k:"6"`
}

func (m *EnvironmentalParameters) PGNNumber() uint32               { return 130311 }
func (m *EnvironmentalParameters) MessageInfo() MessageInfo        { return m.Info }
func (m *EnvironmentalParameters) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *EnvironmentalParameters) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *EnvironmentalParameters) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// TemperatureValue returns Temperature as a physical value in K (value = raw * 0.01).
// The bool is false when Temperature is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *EnvironmentalParameters) TemperatureValue() (float64, bool) {
	if m.Temperature == nil {
		return 0, false
	}
	return float64(*m.Temperature) * 0.01, true
}

// SetTemperatureValue sets Temperature from a physical value in K, rounded to the nearest
// wire tick of 0.01.
func (m *EnvironmentalParameters) SetTemperatureValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.Temperature = &raw
}

// HumidityValue returns Humidity as a physical value in % (value = raw * 0.004).
// The bool is false when Humidity is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *EnvironmentalParameters) HumidityValue() (float64, bool) {
	if m.Humidity == nil {
		return 0, false
	}
	return float64(*m.Humidity) * 0.004, true
}

// SetHumidityValue sets Humidity from a physical value in %, rounded to the nearest
// wire tick of 0.004.
func (m *EnvironmentalParameters) SetHumidityValue(v float64) {
	raw := int64(math.Round(v / 0.004))
	m.Humidity = &raw
}

// AtmosphericPressureValue returns AtmosphericPressure as a physical value in Pa (value = raw * 100).
// The bool is false when AtmosphericPressure is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *EnvironmentalParameters) AtmosphericPressureValue() (float64, bool) {
	if m.AtmosphericPressure == nil {
		return 0, false
	}
	return float64(*m.AtmosphericPressure) * 100, true
}

// SetAtmosphericPressureValue sets AtmosphericPressure from a physical value in Pa, rounded to the nearest
// wire tick of 100.
func (m *EnvironmentalParameters) SetAtmosphericPressureValue(v float64) {
	raw := uint64(math.Round(v / 100))
	m.AtmosphericPressure = &raw
}

type Temperature struct {
	Info              MessageInfo `json:"info"`
	Sid               *uint64     `json:"sid,omitempty" n2k:"1"`
	Instance          *uint64     `json:"instance,omitempty" n2k:"2"`
	Source            *uint64     `json:"source,omitempty" n2k:"3"`
	ActualTemperature *uint64     `json:"actualTemperature,omitempty" n2k:"4"`
	SetTemperature    *uint64     `json:"setTemperature,omitempty" n2k:"5"`
}

func (m *Temperature) PGNNumber() uint32                   { return 130312 }
func (m *Temperature) MessageInfo() MessageInfo            { return m.Info }
func (m *Temperature) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *Temperature) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *Temperature) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// ActualTemperatureValue returns ActualTemperature as a physical value in K (value = raw * 0.01).
// The bool is false when ActualTemperature is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *Temperature) ActualTemperatureValue() (float64, bool) {
	if m.ActualTemperature == nil {
		return 0, false
	}
	return float64(*m.ActualTemperature) * 0.01, true
}

// SetActualTemperatureValue sets ActualTemperature from a physical value in K, rounded to the nearest
// wire tick of 0.01.
func (m *Temperature) SetActualTemperatureValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.ActualTemperature = &raw
}

// SetTemperatureValue returns SetTemperature as a physical value in K (value = raw * 0.01).
// The bool is false when SetTemperature is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *Temperature) SetTemperatureValue() (float64, bool) {
	if m.SetTemperature == nil {
		return 0, false
	}
	return float64(*m.SetTemperature) * 0.01, true
}

// SetSetTemperatureValue sets SetTemperature from a physical value in K, rounded to the nearest
// wire tick of 0.01.
func (m *Temperature) SetSetTemperatureValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.SetTemperature = &raw
}

type Humidity struct {
	Info           MessageInfo `json:"info"`
	Sid            *uint64     `json:"sid,omitempty" n2k:"1"`
	Instance       *uint64     `json:"instance,omitempty" n2k:"2"`
	Source         *uint64     `json:"source,omitempty" n2k:"3"`
	ActualHumidity *int64      `json:"actualHumidity,omitempty" n2k:"4"`
	SetHumidity    *int64      `json:"setHumidity,omitempty" n2k:"5"`
}

func (m *Humidity) PGNNumber() uint32                   { return 130313 }
func (m *Humidity) MessageInfo() MessageInfo            { return m.Info }
func (m *Humidity) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *Humidity) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *Humidity) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// ActualHumidityValue returns ActualHumidity as a physical value in % (value = raw * 0.004).
// The bool is false when ActualHumidity is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *Humidity) ActualHumidityValue() (float64, bool) {
	if m.ActualHumidity == nil {
		return 0, false
	}
	return float64(*m.ActualHumidity) * 0.004, true
}

// SetActualHumidityValue sets ActualHumidity from a physical value in %, rounded to the nearest
// wire tick of 0.004.
func (m *Humidity) SetActualHumidityValue(v float64) {
	raw := int64(math.Round(v / 0.004))
	m.ActualHumidity = &raw
}

// SetHumidityValue returns SetHumidity as a physical value in % (value = raw * 0.004).
// The bool is false when SetHumidity is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *Humidity) SetHumidityValue() (float64, bool) {
	if m.SetHumidity == nil {
		return 0, false
	}
	return float64(*m.SetHumidity) * 0.004, true
}

// SetSetHumidityValue sets SetHumidity from a physical value in %, rounded to the nearest
// wire tick of 0.004.
func (m *Humidity) SetSetHumidityValue(v float64) {
	raw := int64(math.Round(v / 0.004))
	m.SetHumidity = &raw
}

type ActualPressure struct {
	Info     MessageInfo `json:"info"`
	Sid      *uint64     `json:"sid,omitempty" n2k:"1"`
	Instance *uint64     `json:"instance,omitempty" n2k:"2"`
	Source   *uint64     `json:"source,omitempty" n2k:"3"`
	Pressure *int64      `json:"pressure,omitempty" n2k:"4"`
}

func (m *ActualPressure) PGNNumber() uint32                   { return 130314 }
func (m *ActualPressure) MessageInfo() MessageInfo            { return m.Info }
func (m *ActualPressure) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *ActualPressure) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *ActualPressure) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// PressureValue returns Pressure as a physical value in Pa (value = raw * 0.1).
// The bool is false when Pressure is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *ActualPressure) PressureValue() (float64, bool) {
	if m.Pressure == nil {
		return 0, false
	}
	return float64(*m.Pressure) * 0.1, true
}

// SetPressureValue sets Pressure from a physical value in Pa, rounded to the nearest
// wire tick of 0.1.
func (m *ActualPressure) SetPressureValue(v float64) {
	raw := int64(math.Round(v / 0.1))
	m.Pressure = &raw
}

type SetPressure struct {
	Info     MessageInfo `json:"info"`
	Sid      *uint64     `json:"sid,omitempty" n2k:"1"`
	Instance *uint64     `json:"instance,omitempty" n2k:"2"`
	Source   *uint64     `json:"source,omitempty" n2k:"3"`
	Pressure *int64      `json:"pressure,omitempty" n2k:"4"`
}

func (m *SetPressure) PGNNumber() uint32                   { return 130315 }
func (m *SetPressure) MessageInfo() MessageInfo            { return m.Info }
func (m *SetPressure) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *SetPressure) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *SetPressure) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// PressureValue returns Pressure as a physical value in Pa (value = raw * 0.1).
// The bool is false when Pressure is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *SetPressure) PressureValue() (float64, bool) {
	if m.Pressure == nil {
		return 0, false
	}
	return float64(*m.Pressure) * 0.1, true
}

// SetPressureValue sets Pressure from a physical value in Pa, rounded to the nearest
// wire tick of 0.1.
func (m *SetPressure) SetPressureValue(v float64) {
	raw := int64(math.Round(v / 0.1))
	m.Pressure = &raw
}

type TemperatureExtendedRange struct {
	Info           MessageInfo `json:"info"`
	Sid            *uint64     `json:"sid,omitempty" n2k:"1"`
	Instance       *uint64     `json:"instance,omitempty" n2k:"2"`
	Source         *uint64     `json:"source,omitempty" n2k:"3"`
	Temperature    *uint64     `json:"temperature,omitempty" n2k:"4"`
	SetTemperature *uint64     `json:"setTemperature,omitempty" n2k:"5"`
}

func (m *TemperatureExtendedRange) PGNNumber() uint32               { return 130316 }
func (m *TemperatureExtendedRange) MessageInfo() MessageInfo        { return m.Info }
func (m *TemperatureExtendedRange) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *TemperatureExtendedRange) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *TemperatureExtendedRange) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// TemperatureValue returns Temperature as a physical value in K (value = raw * 0.001).
// The bool is false when Temperature is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *TemperatureExtendedRange) TemperatureValue() (float64, bool) {
	if m.Temperature == nil {
		return 0, false
	}
	return float64(*m.Temperature) * 0.001, true
}

// SetTemperatureValue sets Temperature from a physical value in K, rounded to the nearest
// wire tick of 0.001.
func (m *TemperatureExtendedRange) SetTemperatureValue(v float64) {
	raw := uint64(math.Round(v / 0.001))
	m.Temperature = &raw
}

type TideStationData struct {
	Info                       MessageInfo `json:"info"`
	Mode                       *uint64     `json:"mode,omitempty" n2k:"1"`
	TideTendency               *uint64     `json:"tideTendency,omitempty" n2k:"2"`
	MeasurementDate            *uint64     `json:"measurementDate,omitempty" n2k:"4"`
	MeasurementTime            *uint64     `json:"measurementTime,omitempty" n2k:"5"`
	StationLatitude            *int64      `json:"stationLatitude,omitempty" n2k:"6"`
	StationLongitude           *int64      `json:"stationLongitude,omitempty" n2k:"7"`
	TideLevel                  *int64      `json:"tideLevel,omitempty" n2k:"8"`
	TideLevelStandardDeviation *uint64     `json:"tideLevelStandardDeviation,omitempty" n2k:"9"`
	StationId                  string      `json:"stationId,omitempty" n2k:"10"`
	StationName                string      `json:"stationName,omitempty" n2k:"11"`
}

func (m *TideStationData) PGNNumber() uint32                   { return 130320 }
func (m *TideStationData) MessageInfo() MessageInfo            { return m.Info }
func (m *TideStationData) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *TideStationData) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *TideStationData) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// MeasurementDateValue returns MeasurementDate as a physical value in d (value = raw).
// The bool is false when MeasurementDate is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *TideStationData) MeasurementDateValue() (float64, bool) {
	if m.MeasurementDate == nil {
		return 0, false
	}
	return float64(*m.MeasurementDate), true
}

// SetMeasurementDateValue sets MeasurementDate from a physical value in d, rounded to the nearest
// wire tick of 1.
func (m *TideStationData) SetMeasurementDateValue(v float64) {
	raw := uint64(math.Round(v))
	m.MeasurementDate = &raw
}

// MeasurementTimeValue returns MeasurementTime as a physical value in s (value = raw * 0.0001).
// The bool is false when MeasurementTime is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *TideStationData) MeasurementTimeValue() (float64, bool) {
	if m.MeasurementTime == nil {
		return 0, false
	}
	return float64(*m.MeasurementTime) * 0.0001, true
}

// SetMeasurementTimeValue sets MeasurementTime from a physical value in s, rounded to the nearest
// wire tick of 0.0001.
func (m *TideStationData) SetMeasurementTimeValue(v float64) {
	raw := uint64(math.Round(v / 0.0001))
	m.MeasurementTime = &raw
}

// StationLatitudeValue returns StationLatitude as a physical value in deg (value = raw * 1e-07).
// The bool is false when StationLatitude is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *TideStationData) StationLatitudeValue() (float64, bool) {
	if m.StationLatitude == nil {
		return 0, false
	}
	return float64(*m.StationLatitude) * 1e-07, true
}

// SetStationLatitudeValue sets StationLatitude from a physical value in deg, rounded to the nearest
// wire tick of 1e-07.
func (m *TideStationData) SetStationLatitudeValue(v float64) {
	raw := int64(math.Round(v / 1e-07))
	m.StationLatitude = &raw
}

// StationLongitudeValue returns StationLongitude as a physical value in deg (value = raw * 1e-07).
// The bool is false when StationLongitude is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *TideStationData) StationLongitudeValue() (float64, bool) {
	if m.StationLongitude == nil {
		return 0, false
	}
	return float64(*m.StationLongitude) * 1e-07, true
}

// SetStationLongitudeValue sets StationLongitude from a physical value in deg, rounded to the nearest
// wire tick of 1e-07.
func (m *TideStationData) SetStationLongitudeValue(v float64) {
	raw := int64(math.Round(v / 1e-07))
	m.StationLongitude = &raw
}

// TideLevelValue returns TideLevel as a physical value in m (value = raw * 0.001).
// The bool is false when TideLevel is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *TideStationData) TideLevelValue() (float64, bool) {
	if m.TideLevel == nil {
		return 0, false
	}
	return float64(*m.TideLevel) * 0.001, true
}

// SetTideLevelValue sets TideLevel from a physical value in m, rounded to the nearest
// wire tick of 0.001.
func (m *TideStationData) SetTideLevelValue(v float64) {
	raw := int64(math.Round(v / 0.001))
	m.TideLevel = &raw
}

// TideLevelStandardDeviationValue returns TideLevelStandardDeviation as a physical value in m (value = raw * 0.01).
// The bool is false when TideLevelStandardDeviation is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *TideStationData) TideLevelStandardDeviationValue() (float64, bool) {
	if m.TideLevelStandardDeviation == nil {
		return 0, false
	}
	return float64(*m.TideLevelStandardDeviation) * 0.01, true
}

// SetTideLevelStandardDeviationValue sets TideLevelStandardDeviation from a physical value in m, rounded to the nearest
// wire tick of 0.01.
func (m *TideStationData) SetTideLevelStandardDeviationValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.TideLevelStandardDeviation = &raw
}

type SalinityStationData struct {
	Info             MessageInfo `json:"info"`
	Mode             *uint64     `json:"mode,omitempty" n2k:"1"`
	MeasurementDate  *uint64     `json:"measurementDate,omitempty" n2k:"3"`
	MeasurementTime  *uint64     `json:"measurementTime,omitempty" n2k:"4"`
	StationLatitude  *int64      `json:"stationLatitude,omitempty" n2k:"5"`
	StationLongitude *int64      `json:"stationLongitude,omitempty" n2k:"6"`
	Salinity         *float32    `json:"salinity,omitempty" n2k:"7"`
	WaterTemperature *uint64     `json:"waterTemperature,omitempty" n2k:"8"`
	StationId        string      `json:"stationId,omitempty" n2k:"9"`
	StationName      string      `json:"stationName,omitempty" n2k:"10"`
}

func (m *SalinityStationData) PGNNumber() uint32                   { return 130321 }
func (m *SalinityStationData) MessageInfo() MessageInfo            { return m.Info }
func (m *SalinityStationData) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *SalinityStationData) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *SalinityStationData) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// MeasurementDateValue returns MeasurementDate as a physical value in d (value = raw).
// The bool is false when MeasurementDate is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *SalinityStationData) MeasurementDateValue() (float64, bool) {
	if m.MeasurementDate == nil {
		return 0, false
	}
	return float64(*m.MeasurementDate), true
}

// SetMeasurementDateValue sets MeasurementDate from a physical value in d, rounded to the nearest
// wire tick of 1.
func (m *SalinityStationData) SetMeasurementDateValue(v float64) {
	raw := uint64(math.Round(v))
	m.MeasurementDate = &raw
}

// MeasurementTimeValue returns MeasurementTime as a physical value in s (value = raw * 0.0001).
// The bool is false when MeasurementTime is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *SalinityStationData) MeasurementTimeValue() (float64, bool) {
	if m.MeasurementTime == nil {
		return 0, false
	}
	return float64(*m.MeasurementTime) * 0.0001, true
}

// SetMeasurementTimeValue sets MeasurementTime from a physical value in s, rounded to the nearest
// wire tick of 0.0001.
func (m *SalinityStationData) SetMeasurementTimeValue(v float64) {
	raw := uint64(math.Round(v / 0.0001))
	m.MeasurementTime = &raw
}

// StationLatitudeValue returns StationLatitude as a physical value in deg (value = raw * 1e-07).
// The bool is false when StationLatitude is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *SalinityStationData) StationLatitudeValue() (float64, bool) {
	if m.StationLatitude == nil {
		return 0, false
	}
	return float64(*m.StationLatitude) * 1e-07, true
}

// SetStationLatitudeValue sets StationLatitude from a physical value in deg, rounded to the nearest
// wire tick of 1e-07.
func (m *SalinityStationData) SetStationLatitudeValue(v float64) {
	raw := int64(math.Round(v / 1e-07))
	m.StationLatitude = &raw
}

// StationLongitudeValue returns StationLongitude as a physical value in deg (value = raw * 1e-07).
// The bool is false when StationLongitude is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *SalinityStationData) StationLongitudeValue() (float64, bool) {
	if m.StationLongitude == nil {
		return 0, false
	}
	return float64(*m.StationLongitude) * 1e-07, true
}

// SetStationLongitudeValue sets StationLongitude from a physical value in deg, rounded to the nearest
// wire tick of 1e-07.
func (m *SalinityStationData) SetStationLongitudeValue(v float64) {
	raw := int64(math.Round(v / 1e-07))
	m.StationLongitude = &raw
}

// WaterTemperatureValue returns WaterTemperature as a physical value in K (value = raw * 0.01).
// The bool is false when WaterTemperature is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *SalinityStationData) WaterTemperatureValue() (float64, bool) {
	if m.WaterTemperature == nil {
		return 0, false
	}
	return float64(*m.WaterTemperature) * 0.01, true
}

// SetWaterTemperatureValue sets WaterTemperature from a physical value in K, rounded to the nearest
// wire tick of 0.01.
func (m *SalinityStationData) SetWaterTemperatureValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.WaterTemperature = &raw
}

type CurrentStationData struct {
	Info                 MessageInfo `json:"info"`
	Mode                 *uint64     `json:"mode,omitempty" n2k:"1"`
	State                *uint64     `json:"state,omitempty" n2k:"2"`
	MeasurementDate      *uint64     `json:"measurementDate,omitempty" n2k:"4"`
	MeasurementTime      *uint64     `json:"measurementTime,omitempty" n2k:"5"`
	StationLatitude      *int64      `json:"stationLatitude,omitempty" n2k:"6"`
	StationLongitude     *int64      `json:"stationLongitude,omitempty" n2k:"7"`
	MeasurementDepth     *uint64     `json:"measurementDepth,omitempty" n2k:"8"`
	CurrentSpeed         *uint64     `json:"currentSpeed,omitempty" n2k:"9"`
	CurrentFlowDirection *uint64     `json:"currentFlowDirection,omitempty" n2k:"10"`
	WaterTemperature     *uint64     `json:"waterTemperature,omitempty" n2k:"11"`
	StationId            string      `json:"stationId,omitempty" n2k:"12"`
	StationName          string      `json:"stationName,omitempty" n2k:"13"`
}

func (m *CurrentStationData) PGNNumber() uint32                   { return 130322 }
func (m *CurrentStationData) MessageInfo() MessageInfo            { return m.Info }
func (m *CurrentStationData) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *CurrentStationData) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *CurrentStationData) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// MeasurementDateValue returns MeasurementDate as a physical value in d (value = raw).
// The bool is false when MeasurementDate is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *CurrentStationData) MeasurementDateValue() (float64, bool) {
	if m.MeasurementDate == nil {
		return 0, false
	}
	return float64(*m.MeasurementDate), true
}

// SetMeasurementDateValue sets MeasurementDate from a physical value in d, rounded to the nearest
// wire tick of 1.
func (m *CurrentStationData) SetMeasurementDateValue(v float64) {
	raw := uint64(math.Round(v))
	m.MeasurementDate = &raw
}

// MeasurementTimeValue returns MeasurementTime as a physical value in s (value = raw * 0.0001).
// The bool is false when MeasurementTime is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *CurrentStationData) MeasurementTimeValue() (float64, bool) {
	if m.MeasurementTime == nil {
		return 0, false
	}
	return float64(*m.MeasurementTime) * 0.0001, true
}

// SetMeasurementTimeValue sets MeasurementTime from a physical value in s, rounded to the nearest
// wire tick of 0.0001.
func (m *CurrentStationData) SetMeasurementTimeValue(v float64) {
	raw := uint64(math.Round(v / 0.0001))
	m.MeasurementTime = &raw
}

// StationLatitudeValue returns StationLatitude as a physical value in deg (value = raw * 1e-07).
// The bool is false when StationLatitude is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *CurrentStationData) StationLatitudeValue() (float64, bool) {
	if m.StationLatitude == nil {
		return 0, false
	}
	return float64(*m.StationLatitude) * 1e-07, true
}

// SetStationLatitudeValue sets StationLatitude from a physical value in deg, rounded to the nearest
// wire tick of 1e-07.
func (m *CurrentStationData) SetStationLatitudeValue(v float64) {
	raw := int64(math.Round(v / 1e-07))
	m.StationLatitude = &raw
}

// StationLongitudeValue returns StationLongitude as a physical value in deg (value = raw * 1e-07).
// The bool is false when StationLongitude is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *CurrentStationData) StationLongitudeValue() (float64, bool) {
	if m.StationLongitude == nil {
		return 0, false
	}
	return float64(*m.StationLongitude) * 1e-07, true
}

// SetStationLongitudeValue sets StationLongitude from a physical value in deg, rounded to the nearest
// wire tick of 1e-07.
func (m *CurrentStationData) SetStationLongitudeValue(v float64) {
	raw := int64(math.Round(v / 1e-07))
	m.StationLongitude = &raw
}

// MeasurementDepthValue returns MeasurementDepth as a physical value in m (value = raw * 0.01).
// The bool is false when MeasurementDepth is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *CurrentStationData) MeasurementDepthValue() (float64, bool) {
	if m.MeasurementDepth == nil {
		return 0, false
	}
	return float64(*m.MeasurementDepth) * 0.01, true
}

// SetMeasurementDepthValue sets MeasurementDepth from a physical value in m, rounded to the nearest
// wire tick of 0.01.
func (m *CurrentStationData) SetMeasurementDepthValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.MeasurementDepth = &raw
}

// CurrentSpeedValue returns CurrentSpeed as a physical value in m/s (value = raw * 0.01).
// The bool is false when CurrentSpeed is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *CurrentStationData) CurrentSpeedValue() (float64, bool) {
	if m.CurrentSpeed == nil {
		return 0, false
	}
	return float64(*m.CurrentSpeed) * 0.01, true
}

// SetCurrentSpeedValue sets CurrentSpeed from a physical value in m/s, rounded to the nearest
// wire tick of 0.01.
func (m *CurrentStationData) SetCurrentSpeedValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.CurrentSpeed = &raw
}

// CurrentFlowDirectionValue returns CurrentFlowDirection as a physical value in rad (value = raw * 0.0001).
// The bool is false when CurrentFlowDirection is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *CurrentStationData) CurrentFlowDirectionValue() (float64, bool) {
	if m.CurrentFlowDirection == nil {
		return 0, false
	}
	return float64(*m.CurrentFlowDirection) * 0.0001, true
}

// SetCurrentFlowDirectionValue sets CurrentFlowDirection from a physical value in rad, rounded to the nearest
// wire tick of 0.0001.
func (m *CurrentStationData) SetCurrentFlowDirectionValue(v float64) {
	raw := uint64(math.Round(v / 0.0001))
	m.CurrentFlowDirection = &raw
}

// WaterTemperatureValue returns WaterTemperature as a physical value in K (value = raw * 0.01).
// The bool is false when WaterTemperature is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *CurrentStationData) WaterTemperatureValue() (float64, bool) {
	if m.WaterTemperature == nil {
		return 0, false
	}
	return float64(*m.WaterTemperature) * 0.01, true
}

// SetWaterTemperatureValue sets WaterTemperature from a physical value in K, rounded to the nearest
// wire tick of 0.01.
func (m *CurrentStationData) SetWaterTemperatureValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.WaterTemperature = &raw
}

type MeteorologicalStationData struct {
	Info                MessageInfo `json:"info"`
	Mode                *uint64     `json:"mode,omitempty" n2k:"1"`
	MeasurementDate     *uint64     `json:"measurementDate,omitempty" n2k:"3"`
	MeasurementTime     *uint64     `json:"measurementTime,omitempty" n2k:"4"`
	StationLatitude     *int64      `json:"stationLatitude,omitempty" n2k:"5"`
	StationLongitude    *int64      `json:"stationLongitude,omitempty" n2k:"6"`
	WindSpeed           *uint64     `json:"windSpeed,omitempty" n2k:"7"`
	WindDirection       *uint64     `json:"windDirection,omitempty" n2k:"8"`
	WindReference       *uint64     `json:"windReference,omitempty" n2k:"9"`
	WindGusts           *uint64     `json:"windGusts,omitempty" n2k:"11"`
	AtmosphericPressure *uint64     `json:"atmosphericPressure,omitempty" n2k:"12"`
	AmbientTemperature  *uint64     `json:"ambientTemperature,omitempty" n2k:"13"`
	StationId           string      `json:"stationId,omitempty" n2k:"14"`
	StationName         string      `json:"stationName,omitempty" n2k:"15"`
}

func (m *MeteorologicalStationData) PGNNumber() uint32               { return 130323 }
func (m *MeteorologicalStationData) MessageInfo() MessageInfo        { return m.Info }
func (m *MeteorologicalStationData) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MeteorologicalStationData) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MeteorologicalStationData) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// MeasurementDateValue returns MeasurementDate as a physical value in d (value = raw).
// The bool is false when MeasurementDate is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MeteorologicalStationData) MeasurementDateValue() (float64, bool) {
	if m.MeasurementDate == nil {
		return 0, false
	}
	return float64(*m.MeasurementDate), true
}

// SetMeasurementDateValue sets MeasurementDate from a physical value in d, rounded to the nearest
// wire tick of 1.
func (m *MeteorologicalStationData) SetMeasurementDateValue(v float64) {
	raw := uint64(math.Round(v))
	m.MeasurementDate = &raw
}

// MeasurementTimeValue returns MeasurementTime as a physical value in s (value = raw * 0.0001).
// The bool is false when MeasurementTime is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MeteorologicalStationData) MeasurementTimeValue() (float64, bool) {
	if m.MeasurementTime == nil {
		return 0, false
	}
	return float64(*m.MeasurementTime) * 0.0001, true
}

// SetMeasurementTimeValue sets MeasurementTime from a physical value in s, rounded to the nearest
// wire tick of 0.0001.
func (m *MeteorologicalStationData) SetMeasurementTimeValue(v float64) {
	raw := uint64(math.Round(v / 0.0001))
	m.MeasurementTime = &raw
}

// StationLatitudeValue returns StationLatitude as a physical value in deg (value = raw * 1e-07).
// The bool is false when StationLatitude is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MeteorologicalStationData) StationLatitudeValue() (float64, bool) {
	if m.StationLatitude == nil {
		return 0, false
	}
	return float64(*m.StationLatitude) * 1e-07, true
}

// SetStationLatitudeValue sets StationLatitude from a physical value in deg, rounded to the nearest
// wire tick of 1e-07.
func (m *MeteorologicalStationData) SetStationLatitudeValue(v float64) {
	raw := int64(math.Round(v / 1e-07))
	m.StationLatitude = &raw
}

// StationLongitudeValue returns StationLongitude as a physical value in deg (value = raw * 1e-07).
// The bool is false when StationLongitude is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MeteorologicalStationData) StationLongitudeValue() (float64, bool) {
	if m.StationLongitude == nil {
		return 0, false
	}
	return float64(*m.StationLongitude) * 1e-07, true
}

// SetStationLongitudeValue sets StationLongitude from a physical value in deg, rounded to the nearest
// wire tick of 1e-07.
func (m *MeteorologicalStationData) SetStationLongitudeValue(v float64) {
	raw := int64(math.Round(v / 1e-07))
	m.StationLongitude = &raw
}

// WindSpeedValue returns WindSpeed as a physical value in m/s (value = raw * 0.01).
// The bool is false when WindSpeed is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MeteorologicalStationData) WindSpeedValue() (float64, bool) {
	if m.WindSpeed == nil {
		return 0, false
	}
	return float64(*m.WindSpeed) * 0.01, true
}

// SetWindSpeedValue sets WindSpeed from a physical value in m/s, rounded to the nearest
// wire tick of 0.01.
func (m *MeteorologicalStationData) SetWindSpeedValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.WindSpeed = &raw
}

// WindDirectionValue returns WindDirection as a physical value in rad (value = raw * 0.0001).
// The bool is false when WindDirection is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MeteorologicalStationData) WindDirectionValue() (float64, bool) {
	if m.WindDirection == nil {
		return 0, false
	}
	return float64(*m.WindDirection) * 0.0001, true
}

// SetWindDirectionValue sets WindDirection from a physical value in rad, rounded to the nearest
// wire tick of 0.0001.
func (m *MeteorologicalStationData) SetWindDirectionValue(v float64) {
	raw := uint64(math.Round(v / 0.0001))
	m.WindDirection = &raw
}

// WindGustsValue returns WindGusts as a physical value in m/s (value = raw * 0.01).
// The bool is false when WindGusts is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MeteorologicalStationData) WindGustsValue() (float64, bool) {
	if m.WindGusts == nil {
		return 0, false
	}
	return float64(*m.WindGusts) * 0.01, true
}

// SetWindGustsValue sets WindGusts from a physical value in m/s, rounded to the nearest
// wire tick of 0.01.
func (m *MeteorologicalStationData) SetWindGustsValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.WindGusts = &raw
}

// AtmosphericPressureValue returns AtmosphericPressure as a physical value in Pa (value = raw * 100).
// The bool is false when AtmosphericPressure is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MeteorologicalStationData) AtmosphericPressureValue() (float64, bool) {
	if m.AtmosphericPressure == nil {
		return 0, false
	}
	return float64(*m.AtmosphericPressure) * 100, true
}

// SetAtmosphericPressureValue sets AtmosphericPressure from a physical value in Pa, rounded to the nearest
// wire tick of 100.
func (m *MeteorologicalStationData) SetAtmosphericPressureValue(v float64) {
	raw := uint64(math.Round(v / 100))
	m.AtmosphericPressure = &raw
}

// AmbientTemperatureValue returns AmbientTemperature as a physical value in K (value = raw * 0.01).
// The bool is false when AmbientTemperature is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MeteorologicalStationData) AmbientTemperatureValue() (float64, bool) {
	if m.AmbientTemperature == nil {
		return 0, false
	}
	return float64(*m.AmbientTemperature) * 0.01, true
}

// SetAmbientTemperatureValue sets AmbientTemperature from a physical value in K, rounded to the nearest
// wire tick of 0.01.
func (m *MeteorologicalStationData) SetAmbientTemperatureValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.AmbientTemperature = &raw
}

type MooredBuoyStationData struct {
	Info                 MessageInfo `json:"info"`
	Mode                 *uint64     `json:"mode,omitempty" n2k:"1"`
	MeasurementDate      *uint64     `json:"measurementDate,omitempty" n2k:"3"`
	MeasurementTime      *uint64     `json:"measurementTime,omitempty" n2k:"4"`
	StationLatitude      *int64      `json:"stationLatitude,omitempty" n2k:"5"`
	StationLongitude     *int64      `json:"stationLongitude,omitempty" n2k:"6"`
	WindSpeed            *uint64     `json:"windSpeed,omitempty" n2k:"7"`
	WindDirection        *uint64     `json:"windDirection,omitempty" n2k:"8"`
	WindReference        *uint64     `json:"windReference,omitempty" n2k:"9"`
	WindGusts            *uint64     `json:"windGusts,omitempty" n2k:"11"`
	WaveHeight           *uint64     `json:"waveHeight,omitempty" n2k:"12"`
	DominantWavePeriod   *uint64     `json:"dominantWavePeriod,omitempty" n2k:"13"`
	AtmosphericPressure  *uint64     `json:"atmosphericPressure,omitempty" n2k:"14"`
	PressureTendencyRate *int64      `json:"pressureTendencyRate,omitempty" n2k:"15"`
	AirTemperature       *uint64     `json:"airTemperature,omitempty" n2k:"16"`
	WaterTemperature     *uint64     `json:"waterTemperature,omitempty" n2k:"17"`
	StationId            string      `json:"stationId,omitempty" n2k:"18"`
}

func (m *MooredBuoyStationData) PGNNumber() uint32                   { return 130324 }
func (m *MooredBuoyStationData) MessageInfo() MessageInfo            { return m.Info }
func (m *MooredBuoyStationData) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *MooredBuoyStationData) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *MooredBuoyStationData) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// MeasurementDateValue returns MeasurementDate as a physical value in d (value = raw).
// The bool is false when MeasurementDate is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MooredBuoyStationData) MeasurementDateValue() (float64, bool) {
	if m.MeasurementDate == nil {
		return 0, false
	}
	return float64(*m.MeasurementDate), true
}

// SetMeasurementDateValue sets MeasurementDate from a physical value in d, rounded to the nearest
// wire tick of 1.
func (m *MooredBuoyStationData) SetMeasurementDateValue(v float64) {
	raw := uint64(math.Round(v))
	m.MeasurementDate = &raw
}

// MeasurementTimeValue returns MeasurementTime as a physical value in s (value = raw * 0.0001).
// The bool is false when MeasurementTime is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MooredBuoyStationData) MeasurementTimeValue() (float64, bool) {
	if m.MeasurementTime == nil {
		return 0, false
	}
	return float64(*m.MeasurementTime) * 0.0001, true
}

// SetMeasurementTimeValue sets MeasurementTime from a physical value in s, rounded to the nearest
// wire tick of 0.0001.
func (m *MooredBuoyStationData) SetMeasurementTimeValue(v float64) {
	raw := uint64(math.Round(v / 0.0001))
	m.MeasurementTime = &raw
}

// StationLatitudeValue returns StationLatitude as a physical value in deg (value = raw * 1e-07).
// The bool is false when StationLatitude is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MooredBuoyStationData) StationLatitudeValue() (float64, bool) {
	if m.StationLatitude == nil {
		return 0, false
	}
	return float64(*m.StationLatitude) * 1e-07, true
}

// SetStationLatitudeValue sets StationLatitude from a physical value in deg, rounded to the nearest
// wire tick of 1e-07.
func (m *MooredBuoyStationData) SetStationLatitudeValue(v float64) {
	raw := int64(math.Round(v / 1e-07))
	m.StationLatitude = &raw
}

// StationLongitudeValue returns StationLongitude as a physical value in deg (value = raw * 1e-07).
// The bool is false when StationLongitude is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MooredBuoyStationData) StationLongitudeValue() (float64, bool) {
	if m.StationLongitude == nil {
		return 0, false
	}
	return float64(*m.StationLongitude) * 1e-07, true
}

// SetStationLongitudeValue sets StationLongitude from a physical value in deg, rounded to the nearest
// wire tick of 1e-07.
func (m *MooredBuoyStationData) SetStationLongitudeValue(v float64) {
	raw := int64(math.Round(v / 1e-07))
	m.StationLongitude = &raw
}

// WindSpeedValue returns WindSpeed as a physical value in m/s (value = raw * 0.01).
// The bool is false when WindSpeed is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MooredBuoyStationData) WindSpeedValue() (float64, bool) {
	if m.WindSpeed == nil {
		return 0, false
	}
	return float64(*m.WindSpeed) * 0.01, true
}

// SetWindSpeedValue sets WindSpeed from a physical value in m/s, rounded to the nearest
// wire tick of 0.01.
func (m *MooredBuoyStationData) SetWindSpeedValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.WindSpeed = &raw
}

// WindDirectionValue returns WindDirection as a physical value in rad (value = raw * 0.0001).
// The bool is false when WindDirection is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MooredBuoyStationData) WindDirectionValue() (float64, bool) {
	if m.WindDirection == nil {
		return 0, false
	}
	return float64(*m.WindDirection) * 0.0001, true
}

// SetWindDirectionValue sets WindDirection from a physical value in rad, rounded to the nearest
// wire tick of 0.0001.
func (m *MooredBuoyStationData) SetWindDirectionValue(v float64) {
	raw := uint64(math.Round(v / 0.0001))
	m.WindDirection = &raw
}

// WindGustsValue returns WindGusts as a physical value in m/s (value = raw * 0.01).
// The bool is false when WindGusts is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MooredBuoyStationData) WindGustsValue() (float64, bool) {
	if m.WindGusts == nil {
		return 0, false
	}
	return float64(*m.WindGusts) * 0.01, true
}

// SetWindGustsValue sets WindGusts from a physical value in m/s, rounded to the nearest
// wire tick of 0.01.
func (m *MooredBuoyStationData) SetWindGustsValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.WindGusts = &raw
}

// WaveHeightValue returns WaveHeight as a physical value in m (value = raw * 0.01).
// The bool is false when WaveHeight is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MooredBuoyStationData) WaveHeightValue() (float64, bool) {
	if m.WaveHeight == nil {
		return 0, false
	}
	return float64(*m.WaveHeight) * 0.01, true
}

// SetWaveHeightValue sets WaveHeight from a physical value in m, rounded to the nearest
// wire tick of 0.01.
func (m *MooredBuoyStationData) SetWaveHeightValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.WaveHeight = &raw
}

// DominantWavePeriodValue returns DominantWavePeriod as a physical value in s (value = raw * 0.01).
// The bool is false when DominantWavePeriod is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MooredBuoyStationData) DominantWavePeriodValue() (float64, bool) {
	if m.DominantWavePeriod == nil {
		return 0, false
	}
	return float64(*m.DominantWavePeriod) * 0.01, true
}

// SetDominantWavePeriodValue sets DominantWavePeriod from a physical value in s, rounded to the nearest
// wire tick of 0.01.
func (m *MooredBuoyStationData) SetDominantWavePeriodValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.DominantWavePeriod = &raw
}

// AtmosphericPressureValue returns AtmosphericPressure as a physical value in Pa (value = raw * 100).
// The bool is false when AtmosphericPressure is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MooredBuoyStationData) AtmosphericPressureValue() (float64, bool) {
	if m.AtmosphericPressure == nil {
		return 0, false
	}
	return float64(*m.AtmosphericPressure) * 100, true
}

// SetAtmosphericPressureValue sets AtmosphericPressure from a physical value in Pa, rounded to the nearest
// wire tick of 100.
func (m *MooredBuoyStationData) SetAtmosphericPressureValue(v float64) {
	raw := uint64(math.Round(v / 100))
	m.AtmosphericPressure = &raw
}

// PressureTendencyRateValue returns PressureTendencyRate as a physical value in Pa/hr (value = raw * 10).
// The bool is false when PressureTendencyRate is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MooredBuoyStationData) PressureTendencyRateValue() (float64, bool) {
	if m.PressureTendencyRate == nil {
		return 0, false
	}
	return float64(*m.PressureTendencyRate) * 10, true
}

// SetPressureTendencyRateValue sets PressureTendencyRate from a physical value in Pa/hr, rounded to the nearest
// wire tick of 10.
func (m *MooredBuoyStationData) SetPressureTendencyRateValue(v float64) {
	raw := int64(math.Round(v / 10))
	m.PressureTendencyRate = &raw
}

// AirTemperatureValue returns AirTemperature as a physical value in K (value = raw * 0.01).
// The bool is false when AirTemperature is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MooredBuoyStationData) AirTemperatureValue() (float64, bool) {
	if m.AirTemperature == nil {
		return 0, false
	}
	return float64(*m.AirTemperature) * 0.01, true
}

// SetAirTemperatureValue sets AirTemperature from a physical value in K, rounded to the nearest
// wire tick of 0.01.
func (m *MooredBuoyStationData) SetAirTemperatureValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.AirTemperature = &raw
}

// WaterTemperatureValue returns WaterTemperature as a physical value in K (value = raw * 0.01).
// The bool is false when WaterTemperature is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MooredBuoyStationData) WaterTemperatureValue() (float64, bool) {
	if m.WaterTemperature == nil {
		return 0, false
	}
	return float64(*m.WaterTemperature) * 0.01, true
}

// SetWaterTemperatureValue sets WaterTemperature from a physical value in K, rounded to the nearest
// wire tick of 0.01.
func (m *MooredBuoyStationData) SetWaterTemperatureValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.WaterTemperature = &raw
}

type EntertainmentDiagnosticStatus struct {
	Info           MessageInfo `json:"info"`
	Source         *uint64     `json:"source,omitempty" n2k:"1"`
	Number         *uint64     `json:"number,omitempty" n2k:"2"`
	DiagnosticMode *uint64     `json:"diagnosticMode,omitempty" n2k:"3"`
	DiagnosticData string      `json:"diagnosticData,omitempty" n2k:"5"`
}

func (m *EntertainmentDiagnosticStatus) PGNNumber() uint32               { return 130568 }
func (m *EntertainmentDiagnosticStatus) MessageInfo() MessageInfo        { return m.Info }
func (m *EntertainmentDiagnosticStatus) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *EntertainmentDiagnosticStatus) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *EntertainmentDiagnosticStatus) EncodePayload() ([]uint8, error) { return encodeFields(m) }

type LibraryDataFile struct {
	Info           MessageInfo `json:"info"`
	Source         *uint64     `json:"source,omitempty" n2k:"1"`
	Number         *uint64     `json:"number,omitempty" n2k:"2"`
	Id             *uint64     `json:"id,omitempty" n2k:"3"`
	Type           *uint64     `json:"type,omitempty" n2k:"4"`
	Name           string      `json:"name,omitempty" n2k:"5"`
	Track          *uint64     `json:"track,omitempty" n2k:"6"`
	Station        *uint64     `json:"station,omitempty" n2k:"7"`
	Favorite       *uint64     `json:"favorite,omitempty" n2k:"8"`
	RadioFrequency *uint64     `json:"radioFrequency,omitempty" n2k:"9"`
	HdFrequency    *uint64     `json:"hdFrequency,omitempty" n2k:"10"`
	Zone           *uint64     `json:"zone,omitempty" n2k:"11"`
	InPlayQueue    *uint64     `json:"inPlayQueue,omitempty" n2k:"12"`
	Locked         *uint64     `json:"locked,omitempty" n2k:"13"`
	ArtistName     string      `json:"artistName,omitempty" n2k:"15"`
	AlbumName      string      `json:"albumName,omitempty" n2k:"16"`
	StationName    string      `json:"stationName,omitempty" n2k:"17"`
}

func (m *LibraryDataFile) PGNNumber() uint32                   { return 130570 }
func (m *LibraryDataFile) MessageInfo() MessageInfo            { return m.Info }
func (m *LibraryDataFile) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *LibraryDataFile) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *LibraryDataFile) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// RadioFrequencyValue returns RadioFrequency as a physical value in Hz (value = raw * 10).
// The bool is false when RadioFrequency is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *LibraryDataFile) RadioFrequencyValue() (float64, bool) {
	if m.RadioFrequency == nil {
		return 0, false
	}
	return float64(*m.RadioFrequency) * 10, true
}

// SetRadioFrequencyValue sets RadioFrequency from a physical value in Hz, rounded to the nearest
// wire tick of 10.
func (m *LibraryDataFile) SetRadioFrequencyValue(v float64) {
	raw := uint64(math.Round(v / 10))
	m.RadioFrequency = &raw
}

type LibraryDataGroup struct {
	Info         MessageInfo                  `json:"info"`
	Source       *uint64                      `json:"source,omitempty" n2k:"1"`
	Number       *uint64                      `json:"number,omitempty" n2k:"2"`
	Type         *uint64                      `json:"type,omitempty" n2k:"3"`
	Zone         *uint64                      `json:"zone,omitempty" n2k:"4"`
	GroupId      *uint64                      `json:"groupId,omitempty" n2k:"5"`
	IdOffset     *uint64                      `json:"idOffset,omitempty" n2k:"6"`
	IdCount      *uint64                      `json:"idCount,omitempty" n2k:"7"`
	TotalIdCount *uint64                      `json:"totalIdCount,omitempty" n2k:"8"`
	Artist       string                       `json:"artist,omitempty" n2k:"12"`
	Repeating1   []LibraryDataGroupRepeating1 `json:"repeating1,omitempty" n2k:"rep1"`
}

type LibraryDataGroupRepeating1 struct {
	IdType *uint64 `json:"idType,omitempty" n2k:"9"`
	Id     *uint64 `json:"id,omitempty" n2k:"10"`
	Name   string  `json:"name,omitempty" n2k:"11"`
}

func (m *LibraryDataGroup) PGNNumber() uint32                   { return 130571 }
func (m *LibraryDataGroup) MessageInfo() MessageInfo            { return m.Info }
func (m *LibraryDataGroup) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *LibraryDataGroup) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *LibraryDataGroup) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

type LibraryDataSearch struct {
	Info       MessageInfo `json:"info"`
	Source     *uint64     `json:"source,omitempty" n2k:"1"`
	Number     *uint64     `json:"number,omitempty" n2k:"2"`
	GroupId    *uint64     `json:"groupId,omitempty" n2k:"3"`
	GroupType1 *uint64     `json:"groupType1,omitempty" n2k:"4"`
	GroupName1 string      `json:"groupName1,omitempty" n2k:"5"`
	GroupType2 *uint64     `json:"groupType2,omitempty" n2k:"6"`
	GroupName2 string      `json:"groupName2,omitempty" n2k:"7"`
	GroupType3 *uint64     `json:"groupType3,omitempty" n2k:"8"`
	GroupName3 string      `json:"groupName3,omitempty" n2k:"9"`
}

func (m *LibraryDataSearch) PGNNumber() uint32                   { return 130572 }
func (m *LibraryDataSearch) MessageInfo() MessageInfo            { return m.Info }
func (m *LibraryDataSearch) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *LibraryDataSearch) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *LibraryDataSearch) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

type SupportedSourceData struct {
	Info         MessageInfo                     `json:"info"`
	IdOffset     *uint64                         `json:"idOffset,omitempty" n2k:"1"`
	IdCount      *uint64                         `json:"idCount,omitempty" n2k:"2"`
	TotalIdCount *uint64                         `json:"totalIdCount,omitempty" n2k:"3"`
	Repeating1   []SupportedSourceDataRepeating1 `json:"repeating1,omitempty" n2k:"rep1"`
}

type SupportedSourceDataRepeating1 struct {
	Id             *uint64 `json:"id,omitempty" n2k:"4"`
	Source         *uint64 `json:"source,omitempty" n2k:"5"`
	Number         *uint64 `json:"number,omitempty" n2k:"6"`
	Name           string  `json:"name,omitempty" n2k:"7"`
	PlaySupport    *uint64 `json:"playSupport,omitempty" n2k:"8"`
	BrowseSupport  *uint64 `json:"browseSupport,omitempty" n2k:"9"`
	ThumbsSupport  *uint64 `json:"thumbsSupport,omitempty" n2k:"10"`
	Connected      *uint64 `json:"connected,omitempty" n2k:"11"`
	RepeatSupport  *uint64 `json:"repeatSupport,omitempty" n2k:"12"`
	ShuffleSupport *uint64 `json:"shuffleSupport,omitempty" n2k:"13"`
}

func (m *SupportedSourceData) PGNNumber() uint32                   { return 130573 }
func (m *SupportedSourceData) MessageInfo() MessageInfo            { return m.Info }
func (m *SupportedSourceData) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *SupportedSourceData) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *SupportedSourceData) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

type SupportedZoneData struct {
	Info           MessageInfo                   `json:"info"`
	FirstZoneId    *uint64                       `json:"firstZoneId,omitempty" n2k:"1"`
	ZoneCount      *uint64                       `json:"zoneCount,omitempty" n2k:"2"`
	TotalZoneCount *uint64                       `json:"totalZoneCount,omitempty" n2k:"3"`
	Repeating1     []SupportedZoneDataRepeating1 `json:"repeating1,omitempty" n2k:"rep1"`
}

type SupportedZoneDataRepeating1 struct {
	ZoneId *uint64 `json:"zoneId,omitempty" n2k:"4"`
	Name   string  `json:"name,omitempty" n2k:"5"`
}

func (m *SupportedZoneData) PGNNumber() uint32                   { return 130574 }
func (m *SupportedZoneData) MessageInfo() MessageInfo            { return m.Info }
func (m *SupportedZoneData) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *SupportedZoneData) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *SupportedZoneData) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

type EntertainmentParentalControlStatus struct {
	Info           MessageInfo `json:"info"`
	Source         *uint64     `json:"source,omitempty" n2k:"1"`
	Number         *uint64     `json:"number,omitempty" n2k:"2"`
	LockType       *uint64     `json:"lockType,omitempty" n2k:"3"`
	LockStatus     *uint64     `json:"lockStatus,omitempty" n2k:"4"`
	FileStationId  *uint64     `json:"fileStationId,omitempty" n2k:"6"`
	CurrentPincode string      `json:"currentPincode,omitempty" n2k:"7"`
	NewPincode     string      `json:"newPincode,omitempty" n2k:"8"`
}

func (m *EntertainmentParentalControlStatus) PGNNumber() uint32               { return 130575 }
func (m *EntertainmentParentalControlStatus) MessageInfo() MessageInfo        { return m.Info }
func (m *EntertainmentParentalControlStatus) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *EntertainmentParentalControlStatus) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *EntertainmentParentalControlStatus) EncodePayload() ([]uint8, error) { return encodeFields(m) }

type SmallCraftStatus struct {
	Info             MessageInfo `json:"info"`
	PortTrimTab      *int64      `json:"portTrimTab,omitempty" n2k:"1"`
	StarboardTrimTab *int64      `json:"starboardTrimTab,omitempty" n2k:"2"`
}

func (m *SmallCraftStatus) PGNNumber() uint32                   { return 130576 }
func (m *SmallCraftStatus) MessageInfo() MessageInfo            { return m.Info }
func (m *SmallCraftStatus) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *SmallCraftStatus) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *SmallCraftStatus) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// PortTrimTabValue returns PortTrimTab as a physical value in % (value = raw).
// The bool is false when PortTrimTab is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *SmallCraftStatus) PortTrimTabValue() (float64, bool) {
	if m.PortTrimTab == nil {
		return 0, false
	}
	return float64(*m.PortTrimTab), true
}

// SetPortTrimTabValue sets PortTrimTab from a physical value in %, rounded to the nearest
// wire tick of 1.
func (m *SmallCraftStatus) SetPortTrimTabValue(v float64) {
	raw := int64(math.Round(v))
	m.PortTrimTab = &raw
}

// StarboardTrimTabValue returns StarboardTrimTab as a physical value in % (value = raw).
// The bool is false when StarboardTrimTab is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *SmallCraftStatus) StarboardTrimTabValue() (float64, bool) {
	if m.StarboardTrimTab == nil {
		return 0, false
	}
	return float64(*m.StarboardTrimTab), true
}

// SetStarboardTrimTabValue sets StarboardTrimTab from a physical value in %, rounded to the nearest
// wire tick of 1.
func (m *SmallCraftStatus) SetStarboardTrimTabValue(v float64) {
	raw := int64(math.Round(v))
	m.StarboardTrimTab = &raw
}

type VesselSpeedComponents struct {
	Info                              MessageInfo `json:"info"`
	LongitudinalSpeedWaterReferenced  *int64      `json:"longitudinalSpeedWaterReferenced,omitempty" n2k:"1"`
	TransverseSpeedWaterReferenced    *int64      `json:"transverseSpeedWaterReferenced,omitempty" n2k:"2"`
	LongitudinalSpeedGroundReferenced *int64      `json:"longitudinalSpeedGroundReferenced,omitempty" n2k:"3"`
	TransverseSpeedGroundReferenced   *int64      `json:"transverseSpeedGroundReferenced,omitempty" n2k:"4"`
	SternSpeedWaterReferenced         *int64      `json:"sternSpeedWaterReferenced,omitempty" n2k:"5"`
	SternSpeedGroundReferenced        *int64      `json:"sternSpeedGroundReferenced,omitempty" n2k:"6"`
}

func (m *VesselSpeedComponents) PGNNumber() uint32                   { return 130578 }
func (m *VesselSpeedComponents) MessageInfo() MessageInfo            { return m.Info }
func (m *VesselSpeedComponents) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *VesselSpeedComponents) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *VesselSpeedComponents) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// LongitudinalSpeedWaterReferencedValue returns LongitudinalSpeedWaterReferenced as a physical value in m/s (value = raw * 0.001).
// The bool is false when LongitudinalSpeedWaterReferenced is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *VesselSpeedComponents) LongitudinalSpeedWaterReferencedValue() (float64, bool) {
	if m.LongitudinalSpeedWaterReferenced == nil {
		return 0, false
	}
	return float64(*m.LongitudinalSpeedWaterReferenced) * 0.001, true
}

// SetLongitudinalSpeedWaterReferencedValue sets LongitudinalSpeedWaterReferenced from a physical value in m/s, rounded to the nearest
// wire tick of 0.001.
func (m *VesselSpeedComponents) SetLongitudinalSpeedWaterReferencedValue(v float64) {
	raw := int64(math.Round(v / 0.001))
	m.LongitudinalSpeedWaterReferenced = &raw
}

// TransverseSpeedWaterReferencedValue returns TransverseSpeedWaterReferenced as a physical value in m/s (value = raw * 0.001).
// The bool is false when TransverseSpeedWaterReferenced is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *VesselSpeedComponents) TransverseSpeedWaterReferencedValue() (float64, bool) {
	if m.TransverseSpeedWaterReferenced == nil {
		return 0, false
	}
	return float64(*m.TransverseSpeedWaterReferenced) * 0.001, true
}

// SetTransverseSpeedWaterReferencedValue sets TransverseSpeedWaterReferenced from a physical value in m/s, rounded to the nearest
// wire tick of 0.001.
func (m *VesselSpeedComponents) SetTransverseSpeedWaterReferencedValue(v float64) {
	raw := int64(math.Round(v / 0.001))
	m.TransverseSpeedWaterReferenced = &raw
}

// LongitudinalSpeedGroundReferencedValue returns LongitudinalSpeedGroundReferenced as a physical value in m/s (value = raw * 0.001).
// The bool is false when LongitudinalSpeedGroundReferenced is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *VesselSpeedComponents) LongitudinalSpeedGroundReferencedValue() (float64, bool) {
	if m.LongitudinalSpeedGroundReferenced == nil {
		return 0, false
	}
	return float64(*m.LongitudinalSpeedGroundReferenced) * 0.001, true
}

// SetLongitudinalSpeedGroundReferencedValue sets LongitudinalSpeedGroundReferenced from a physical value in m/s, rounded to the nearest
// wire tick of 0.001.
func (m *VesselSpeedComponents) SetLongitudinalSpeedGroundReferencedValue(v float64) {
	raw := int64(math.Round(v / 0.001))
	m.LongitudinalSpeedGroundReferenced = &raw
}

// TransverseSpeedGroundReferencedValue returns TransverseSpeedGroundReferenced as a physical value in m/s (value = raw * 0.001).
// The bool is false when TransverseSpeedGroundReferenced is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *VesselSpeedComponents) TransverseSpeedGroundReferencedValue() (float64, bool) {
	if m.TransverseSpeedGroundReferenced == nil {
		return 0, false
	}
	return float64(*m.TransverseSpeedGroundReferenced) * 0.001, true
}

// SetTransverseSpeedGroundReferencedValue sets TransverseSpeedGroundReferenced from a physical value in m/s, rounded to the nearest
// wire tick of 0.001.
func (m *VesselSpeedComponents) SetTransverseSpeedGroundReferencedValue(v float64) {
	raw := int64(math.Round(v / 0.001))
	m.TransverseSpeedGroundReferenced = &raw
}

// SternSpeedWaterReferencedValue returns SternSpeedWaterReferenced as a physical value in m/s (value = raw * 0.001).
// The bool is false when SternSpeedWaterReferenced is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *VesselSpeedComponents) SternSpeedWaterReferencedValue() (float64, bool) {
	if m.SternSpeedWaterReferenced == nil {
		return 0, false
	}
	return float64(*m.SternSpeedWaterReferenced) * 0.001, true
}

// SetSternSpeedWaterReferencedValue sets SternSpeedWaterReferenced from a physical value in m/s, rounded to the nearest
// wire tick of 0.001.
func (m *VesselSpeedComponents) SetSternSpeedWaterReferencedValue(v float64) {
	raw := int64(math.Round(v / 0.001))
	m.SternSpeedWaterReferenced = &raw
}

// SternSpeedGroundReferencedValue returns SternSpeedGroundReferenced as a physical value in m/s (value = raw * 0.001).
// The bool is false when SternSpeedGroundReferenced is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *VesselSpeedComponents) SternSpeedGroundReferencedValue() (float64, bool) {
	if m.SternSpeedGroundReferenced == nil {
		return 0, false
	}
	return float64(*m.SternSpeedGroundReferenced) * 0.001, true
}

// SetSternSpeedGroundReferencedValue sets SternSpeedGroundReferenced from a physical value in m/s, rounded to the nearest
// wire tick of 0.001.
func (m *VesselSpeedComponents) SetSternSpeedGroundReferencedValue(v float64) {
	raw := int64(math.Round(v / 0.001))
	m.SternSpeedGroundReferenced = &raw
}

type SystemConfiguration struct {
	Info            MessageInfo `json:"info"`
	Power           *uint64     `json:"power,omitempty" n2k:"1"`
	DefaultSettings *uint64     `json:"defaultSettings,omitempty" n2k:"2"`
	TunerRegions    *uint64     `json:"tunerRegions,omitempty" n2k:"3"`
	MaxFavorites    *uint64     `json:"maxFavorites,omitempty" n2k:"4"`
	VideoProtocols  *uint64     `json:"videoProtocols,omitempty" n2k:"5"`
}

func (m *SystemConfiguration) PGNNumber() uint32                   { return 130579 }
func (m *SystemConfiguration) MessageInfo() MessageInfo            { return m.Info }
func (m *SystemConfiguration) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *SystemConfiguration) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *SystemConfiguration) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

type SystemConfigurationDeprecated struct {
	Info            MessageInfo `json:"info"`
	Power           *uint64     `json:"power,omitempty" n2k:"1"`
	DefaultSettings *uint64     `json:"defaultSettings,omitempty" n2k:"2"`
	TunerRegions    *uint64     `json:"tunerRegions,omitempty" n2k:"3"`
	MaxFavorites    *uint64     `json:"maxFavorites,omitempty" n2k:"4"`
}

func (m *SystemConfigurationDeprecated) PGNNumber() uint32               { return 130580 }
func (m *SystemConfigurationDeprecated) MessageInfo() MessageInfo        { return m.Info }
func (m *SystemConfigurationDeprecated) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *SystemConfigurationDeprecated) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *SystemConfigurationDeprecated) EncodePayload() ([]uint8, error) { return encodeFields(m) }

type ZoneConfigurationDeprecated struct {
	Info           MessageInfo                             `json:"info"`
	FirstZoneId    *uint64                                 `json:"firstZoneId,omitempty" n2k:"1"`
	ZoneCount      *uint64                                 `json:"zoneCount,omitempty" n2k:"2"`
	TotalZoneCount *uint64                                 `json:"totalZoneCount,omitempty" n2k:"3"`
	Repeating1     []ZoneConfigurationDeprecatedRepeating1 `json:"repeating1,omitempty" n2k:"rep1"`
}

type ZoneConfigurationDeprecatedRepeating1 struct {
	ZoneId   *uint64 `json:"zoneId,omitempty" n2k:"4"`
	ZoneName string  `json:"zoneName,omitempty" n2k:"5"`
}

func (m *ZoneConfigurationDeprecated) PGNNumber() uint32               { return 130581 }
func (m *ZoneConfigurationDeprecated) MessageInfo() MessageInfo        { return m.Info }
func (m *ZoneConfigurationDeprecated) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *ZoneConfigurationDeprecated) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *ZoneConfigurationDeprecated) EncodePayload() ([]uint8, error) { return encodeFields(m) }

type ZoneVolume struct {
	Info         MessageInfo `json:"info"`
	ZoneId       *uint64     `json:"zoneId,omitempty" n2k:"1"`
	Volume       *uint64     `json:"volume,omitempty" n2k:"2"`
	VolumeChange *uint64     `json:"volumeChange,omitempty" n2k:"3"`
	Mute         *uint64     `json:"mute,omitempty" n2k:"4"`
	Channel      *uint64     `json:"channel,omitempty" n2k:"6"`
}

func (m *ZoneVolume) PGNNumber() uint32                   { return 130582 }
func (m *ZoneVolume) MessageInfo() MessageInfo            { return m.Info }
func (m *ZoneVolume) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *ZoneVolume) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *ZoneVolume) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// VolumeValue returns Volume as a physical value in % (value = raw).
// The bool is false when Volume is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *ZoneVolume) VolumeValue() (float64, bool) {
	if m.Volume == nil {
		return 0, false
	}
	return float64(*m.Volume), true
}

// SetVolumeValue sets Volume from a physical value in %, rounded to the nearest
// wire tick of 1.
func (m *ZoneVolume) SetVolumeValue(v float64) {
	raw := uint64(math.Round(v))
	m.Volume = &raw
}

type AvailableAudioEqPresets struct {
	Info             MessageInfo                         `json:"info"`
	FirstPreset      *uint64                             `json:"firstPreset,omitempty" n2k:"1"`
	PresetCount      *uint64                             `json:"presetCount,omitempty" n2k:"2"`
	TotalPresetCount *uint64                             `json:"totalPresetCount,omitempty" n2k:"3"`
	Repeating1       []AvailableAudioEqPresetsRepeating1 `json:"repeating1,omitempty" n2k:"rep1"`
}

type AvailableAudioEqPresetsRepeating1 struct {
	PresetType *uint64 `json:"presetType,omitempty" n2k:"4"`
	PresetName string  `json:"presetName,omitempty" n2k:"5"`
}

func (m *AvailableAudioEqPresets) PGNNumber() uint32               { return 130583 }
func (m *AvailableAudioEqPresets) MessageInfo() MessageInfo        { return m.Info }
func (m *AvailableAudioEqPresets) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *AvailableAudioEqPresets) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *AvailableAudioEqPresets) EncodePayload() ([]uint8, error) { return encodeFields(m) }

type AvailableBluetoothAddresses struct {
	Info              MessageInfo                             `json:"info"`
	FirstAddress      *uint64                                 `json:"firstAddress,omitempty" n2k:"1"`
	AddressCount      *uint64                                 `json:"addressCount,omitempty" n2k:"2"`
	TotalAddressCount *uint64                                 `json:"totalAddressCount,omitempty" n2k:"3"`
	Repeating1        []AvailableBluetoothAddressesRepeating1 `json:"repeating1,omitempty" n2k:"rep1"`
}

type AvailableBluetoothAddressesRepeating1 struct {
	BluetoothAddress []uint8 `json:"bluetoothAddress,omitempty" n2k:"4"`
	Status           *uint64 `json:"status,omitempty" n2k:"5"`
	DeviceName       string  `json:"deviceName,omitempty" n2k:"6"`
	SignalStrength   *uint64 `json:"signalStrength,omitempty" n2k:"7"`
}

func (m *AvailableBluetoothAddresses) PGNNumber() uint32               { return 130584 }
func (m *AvailableBluetoothAddresses) MessageInfo() MessageInfo        { return m.Info }
func (m *AvailableBluetoothAddresses) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *AvailableBluetoothAddresses) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *AvailableBluetoothAddresses) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// SignalStrengthValue returns SignalStrength as a physical value in % (value = raw).
// The bool is false when SignalStrength is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *AvailableBluetoothAddressesRepeating1) SignalStrengthValue() (float64, bool) {
	if m.SignalStrength == nil {
		return 0, false
	}
	return float64(*m.SignalStrength), true
}

// SetSignalStrengthValue sets SignalStrength from a physical value in %, rounded to the nearest
// wire tick of 1.
func (m *AvailableBluetoothAddressesRepeating1) SetSignalStrengthValue(v float64) {
	raw := uint64(math.Round(v))
	m.SignalStrength = &raw
}

type BluetoothSourceStatus struct {
	Info             MessageInfo `json:"info"`
	SourceNumber     *uint64     `json:"sourceNumber,omitempty" n2k:"1"`
	Status           *uint64     `json:"status,omitempty" n2k:"2"`
	ForgetDevice     *uint64     `json:"forgetDevice,omitempty" n2k:"3"`
	Discovering      *uint64     `json:"discovering,omitempty" n2k:"4"`
	BluetoothAddress []uint8     `json:"bluetoothAddress,omitempty" n2k:"5"`
}

func (m *BluetoothSourceStatus) PGNNumber() uint32                   { return 130585 }
func (m *BluetoothSourceStatus) MessageInfo() MessageInfo            { return m.Info }
func (m *BluetoothSourceStatus) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *BluetoothSourceStatus) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *BluetoothSourceStatus) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

type ZoneConfiguration struct {
	Info                    MessageInfo `json:"info"`
	ZoneId                  *uint64     `json:"zoneId,omitempty" n2k:"1"`
	VolumeLimit             *uint64     `json:"volumeLimit,omitempty" n2k:"2"`
	Fade                    *int64      `json:"fade,omitempty" n2k:"3"`
	Balance                 *int64      `json:"balance,omitempty" n2k:"4"`
	SubVolume               *uint64     `json:"subVolume,omitempty" n2k:"5"`
	EqTreble                *int64      `json:"eqTreble,omitempty" n2k:"6"`
	EqMidRange              *int64      `json:"eqMidRange,omitempty" n2k:"7"`
	EqBass                  *int64      `json:"eqBass,omitempty" n2k:"8"`
	PresetType              *uint64     `json:"presetType,omitempty" n2k:"9"`
	AudioFilter             *uint64     `json:"audioFilter,omitempty" n2k:"10"`
	HighPassFilterFrequency *uint64     `json:"highPassFilterFrequency,omitempty" n2k:"11"`
	LowPassFilterFrequency  *uint64     `json:"lowPassFilterFrequency,omitempty" n2k:"12"`
	Channel                 *uint64     `json:"channel,omitempty" n2k:"13"`
}

func (m *ZoneConfiguration) PGNNumber() uint32                   { return 130586 }
func (m *ZoneConfiguration) MessageInfo() MessageInfo            { return m.Info }
func (m *ZoneConfiguration) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *ZoneConfiguration) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *ZoneConfiguration) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// VolumeLimitValue returns VolumeLimit as a physical value in % (value = raw).
// The bool is false when VolumeLimit is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *ZoneConfiguration) VolumeLimitValue() (float64, bool) {
	if m.VolumeLimit == nil {
		return 0, false
	}
	return float64(*m.VolumeLimit), true
}

// SetVolumeLimitValue sets VolumeLimit from a physical value in %, rounded to the nearest
// wire tick of 1.
func (m *ZoneConfiguration) SetVolumeLimitValue(v float64) {
	raw := uint64(math.Round(v))
	m.VolumeLimit = &raw
}

// FadeValue returns Fade as a physical value in % (value = raw).
// The bool is false when Fade is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *ZoneConfiguration) FadeValue() (float64, bool) {
	if m.Fade == nil {
		return 0, false
	}
	return float64(*m.Fade), true
}

// SetFadeValue sets Fade from a physical value in %, rounded to the nearest
// wire tick of 1.
func (m *ZoneConfiguration) SetFadeValue(v float64) {
	raw := int64(math.Round(v))
	m.Fade = &raw
}

// BalanceValue returns Balance as a physical value in % (value = raw).
// The bool is false when Balance is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *ZoneConfiguration) BalanceValue() (float64, bool) {
	if m.Balance == nil {
		return 0, false
	}
	return float64(*m.Balance), true
}

// SetBalanceValue sets Balance from a physical value in %, rounded to the nearest
// wire tick of 1.
func (m *ZoneConfiguration) SetBalanceValue(v float64) {
	raw := int64(math.Round(v))
	m.Balance = &raw
}

// SubVolumeValue returns SubVolume as a physical value in % (value = raw).
// The bool is false when SubVolume is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *ZoneConfiguration) SubVolumeValue() (float64, bool) {
	if m.SubVolume == nil {
		return 0, false
	}
	return float64(*m.SubVolume), true
}

// SetSubVolumeValue sets SubVolume from a physical value in %, rounded to the nearest
// wire tick of 1.
func (m *ZoneConfiguration) SetSubVolumeValue(v float64) {
	raw := uint64(math.Round(v))
	m.SubVolume = &raw
}

// EqTrebleValue returns EqTreble as a physical value in % (value = raw).
// The bool is false when EqTreble is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *ZoneConfiguration) EqTrebleValue() (float64, bool) {
	if m.EqTreble == nil {
		return 0, false
	}
	return float64(*m.EqTreble), true
}

// SetEqTrebleValue sets EqTreble from a physical value in %, rounded to the nearest
// wire tick of 1.
func (m *ZoneConfiguration) SetEqTrebleValue(v float64) {
	raw := int64(math.Round(v))
	m.EqTreble = &raw
}

// EqMidRangeValue returns EqMidRange as a physical value in % (value = raw).
// The bool is false when EqMidRange is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *ZoneConfiguration) EqMidRangeValue() (float64, bool) {
	if m.EqMidRange == nil {
		return 0, false
	}
	return float64(*m.EqMidRange), true
}

// SetEqMidRangeValue sets EqMidRange from a physical value in %, rounded to the nearest
// wire tick of 1.
func (m *ZoneConfiguration) SetEqMidRangeValue(v float64) {
	raw := int64(math.Round(v))
	m.EqMidRange = &raw
}

// EqBassValue returns EqBass as a physical value in % (value = raw).
// The bool is false when EqBass is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *ZoneConfiguration) EqBassValue() (float64, bool) {
	if m.EqBass == nil {
		return 0, false
	}
	return float64(*m.EqBass), true
}

// SetEqBassValue sets EqBass from a physical value in %, rounded to the nearest
// wire tick of 1.
func (m *ZoneConfiguration) SetEqBassValue(v float64) {
	raw := int64(math.Round(v))
	m.EqBass = &raw
}

// HighPassFilterFrequencyValue returns HighPassFilterFrequency as a physical value in Hz (value = raw).
// The bool is false when HighPassFilterFrequency is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *ZoneConfiguration) HighPassFilterFrequencyValue() (float64, bool) {
	if m.HighPassFilterFrequency == nil {
		return 0, false
	}
	return float64(*m.HighPassFilterFrequency), true
}

// SetHighPassFilterFrequencyValue sets HighPassFilterFrequency from a physical value in Hz, rounded to the nearest
// wire tick of 1.
func (m *ZoneConfiguration) SetHighPassFilterFrequencyValue(v float64) {
	raw := uint64(math.Round(v))
	m.HighPassFilterFrequency = &raw
}

// LowPassFilterFrequencyValue returns LowPassFilterFrequency as a physical value in Hz (value = raw).
// The bool is false when LowPassFilterFrequency is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *ZoneConfiguration) LowPassFilterFrequencyValue() (float64, bool) {
	if m.LowPassFilterFrequency == nil {
		return 0, false
	}
	return float64(*m.LowPassFilterFrequency), true
}

// SetLowPassFilterFrequencyValue sets LowPassFilterFrequency from a physical value in Hz, rounded to the nearest
// wire tick of 1.
func (m *ZoneConfiguration) SetLowPassFilterFrequencyValue(v float64) {
	raw := uint64(math.Round(v))
	m.LowPassFilterFrequency = &raw
}

type Message0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Data             []uint8     `json:"data,omitempty" n2k:"4"`
}

func (m *Message0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed) PGNNumber() uint32 {
	return 130816
}
func (m *Message0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed) MessageInfo() MessageInfo {
	return m.Info
}
func (m *Message0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed) SetMessageInfo(info MessageInfo) {
	m.Info = info
}
func (m *Message0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *Message0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed) EncodePayload() ([]uint8, error) {
	return encodeFields(m)
}
