// Code generated by PGN generator; DO NOT EDIT.
// Source schema 2.5.0 version 7.1.0.

package pgn

import "math"

type FluidLevel struct {
	Info     MessageInfo `json:"info"`
	Instance *uint64     `json:"instance,omitempty" n2k:"1"`
	Type     *uint64     `json:"type,omitempty" n2k:"2"`
	Level    *int64      `json:"level,omitempty" n2k:"3"`
	Capacity *uint64     `json:"capacity,omitempty" n2k:"4"`
}

func (m *FluidLevel) PGNNumber() uint32                   { return 127505 }
func (m *FluidLevel) MessageInfo() MessageInfo            { return m.Info }
func (m *FluidLevel) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *FluidLevel) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *FluidLevel) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// LevelValue returns Level as a physical value in % (value = raw * 0.004).
// The bool is false when Level is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *FluidLevel) LevelValue() (float64, bool) {
	if m.Level == nil {
		return 0, false
	}
	return float64(*m.Level) * 0.004, true
}

// SetLevelValue sets Level from a physical value in %, rounded to the nearest
// wire tick of 0.004.
func (m *FluidLevel) SetLevelValue(v float64) {
	raw := int64(math.Round(v / 0.004))
	m.Level = &raw
}

// CapacityValue returns Capacity as a physical value in L (value = raw * 0.1).
// The bool is false when Capacity is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *FluidLevel) CapacityValue() (float64, bool) {
	if m.Capacity == nil {
		return 0, false
	}
	return float64(*m.Capacity) * 0.1, true
}

// SetCapacityValue sets Capacity from a physical value in L, rounded to the nearest
// wire tick of 0.1.
func (m *FluidLevel) SetCapacityValue(v float64) {
	raw := uint64(math.Round(v / 0.1))
	m.Capacity = &raw
}

type ElevatorCarStatus struct {
	Info                                   MessageInfo `json:"info"`
	Sid                                    *uint64     `json:"sid,omitempty" n2k:"1"`
	ElevatorCarId                          *uint64     `json:"elevatorCarId,omitempty" n2k:"2"`
	ElevatorCarUsage                       *uint64     `json:"elevatorCarUsage,omitempty" n2k:"3"`
	SmokeSensorStatus                      *uint64     `json:"smokeSensorStatus,omitempty" n2k:"4"`
	LimitSwitchSensorStatus                *uint64     `json:"limitSwitchSensorStatus,omitempty" n2k:"5"`
	ProximitySwitchSensorStatus            *uint64     `json:"proximitySwitchSensorStatus,omitempty" n2k:"6"`
	InertialMeasurementUnitImuSensorStatus *uint64     `json:"inertialMeasurementUnitImuSensorStatus,omitempty" n2k:"7"`
	ElevatorLoadLimitStatus                *uint64     `json:"elevatorLoadLimitStatus,omitempty" n2k:"8"`
	ElevatorLoadBalanceStatus              *uint64     `json:"elevatorLoadBalanceStatus,omitempty" n2k:"9"`
	ElevatorLoadSensor1Status              *uint64     `json:"elevatorLoadSensor1Status,omitempty" n2k:"10"`
	ElevatorLoadSensor2Status              *uint64     `json:"elevatorLoadSensor2Status,omitempty" n2k:"11"`
	ElevatorLoadSensor3Status              *uint64     `json:"elevatorLoadSensor3Status,omitempty" n2k:"12"`
	ElevatorLoadSensor4Status              *uint64     `json:"elevatorLoadSensor4Status,omitempty" n2k:"13"`
	ElevatorCarMotionStatus                *uint64     `json:"elevatorCarMotionStatus,omitempty" n2k:"15"`
	ElevatorCarDoorStatus                  *uint64     `json:"elevatorCarDoorStatus,omitempty" n2k:"16"`
	ElevatorCarEmergencyButtonStatus       *uint64     `json:"elevatorCarEmergencyButtonStatus,omitempty" n2k:"17"`
	ElevatorCarBuzzerStatus                *uint64     `json:"elevatorCarBuzzerStatus,omitempty" n2k:"18"`
	OpenDoorButtonStatus                   *uint64     `json:"openDoorButtonStatus,omitempty" n2k:"19"`
	CloseDoorButtonStatus                  *uint64     `json:"closeDoorButtonStatus,omitempty" n2k:"20"`
	CurrentDeck                            *uint64     `json:"currentDeck,omitempty" n2k:"22"`
	DestinationDeck                        *uint64     `json:"destinationDeck,omitempty" n2k:"23"`
	TotalNumberOfDecks                     *uint64     `json:"totalNumberOfDecks,omitempty" n2k:"24"`
	WeightOfLoadCell1                      *uint64     `json:"weightOfLoadCell1,omitempty" n2k:"25"`
	WeightOfLoadCell2                      *uint64     `json:"weightOfLoadCell2,omitempty" n2k:"26"`
	WeightOfLoadCell3                      *uint64     `json:"weightOfLoadCell3,omitempty" n2k:"27"`
	WeightOfLoadCell4                      *uint64     `json:"weightOfLoadCell4,omitempty" n2k:"28"`
	SpeedOfElevatorCar                     *int64      `json:"speedOfElevatorCar,omitempty" n2k:"29"`
	ElevatorBrakeStatus                    *uint64     `json:"elevatorBrakeStatus,omitempty" n2k:"30"`
	ElevatorMotorRotationControlStatus     *uint64     `json:"elevatorMotorRotationControlStatus,omitempty" n2k:"31"`
}

func (m *ElevatorCarStatus) PGNNumber() uint32                   { return 128538 }
func (m *ElevatorCarStatus) MessageInfo() MessageInfo            { return m.Info }
func (m *ElevatorCarStatus) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *ElevatorCarStatus) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *ElevatorCarStatus) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// SpeedOfElevatorCarValue returns SpeedOfElevatorCar as a physical value in m/s (value = raw * 0.01).
// The bool is false when SpeedOfElevatorCar is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *ElevatorCarStatus) SpeedOfElevatorCarValue() (float64, bool) {
	if m.SpeedOfElevatorCar == nil {
		return 0, false
	}
	return float64(*m.SpeedOfElevatorCar) * 0.01, true
}

// SetSpeedOfElevatorCarValue sets SpeedOfElevatorCar from a physical value in m/s, rounded to the nearest
// wire tick of 0.01.
func (m *ElevatorCarStatus) SetSpeedOfElevatorCarValue(v float64) {
	raw := int64(math.Round(v / 0.01))
	m.SpeedOfElevatorCar = &raw
}

type ElevatorMotorControl struct {
	Info                                          MessageInfo `json:"info"`
	Sid                                           *uint64     `json:"sid,omitempty" n2k:"1"`
	ElevatorCarId                                 *uint64     `json:"elevatorCarId,omitempty" n2k:"2"`
	ElevatorCarUsage                              *uint64     `json:"elevatorCarUsage,omitempty" n2k:"3"`
	MotorAccelerationDecelerationProfileSelection *uint64     `json:"motorAccelerationDecelerationProfileSelection,omitempty" n2k:"4"`
	MotorRotationalControlStatus                  *uint64     `json:"motorRotationalControlStatus,omitempty" n2k:"5"`
}

func (m *ElevatorMotorControl) PGNNumber() uint32                   { return 128768 }
func (m *ElevatorMotorControl) MessageInfo() MessageInfo            { return m.Info }
func (m *ElevatorMotorControl) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *ElevatorMotorControl) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *ElevatorMotorControl) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

type ElevatorDeckPushButton struct {
	Info                       MessageInfo `json:"info"`
	Sid                        *uint64     `json:"sid,omitempty" n2k:"1"`
	ElevatorCallButtonId       *uint64     `json:"elevatorCallButtonId,omitempty" n2k:"2"`
	DeckButtonId               *uint64     `json:"deckButtonId,omitempty" n2k:"3"`
	ElevatorCarUsage           *uint64     `json:"elevatorCarUsage,omitempty" n2k:"4"`
	ElevatorCarButtonSelection *uint64     `json:"elevatorCarButtonSelection,omitempty" n2k:"5"`
}

func (m *ElevatorDeckPushButton) PGNNumber() uint32               { return 128769 }
func (m *ElevatorDeckPushButton) MessageInfo() MessageInfo        { return m.Info }
func (m *ElevatorDeckPushButton) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *ElevatorDeckPushButton) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *ElevatorDeckPushButton) EncodePayload() ([]uint8, error) { return encodeFields(m) }

type LinearActuatorControlStatus struct {
	Info                    MessageInfo `json:"info"`
	ActuatorIdentifier      *uint64     `json:"actuatorIdentifier,omitempty" n2k:"1"`
	CommandedDevicePosition *uint64     `json:"commandedDevicePosition,omitempty" n2k:"2"`
	DevicePosition          *uint64     `json:"devicePosition,omitempty" n2k:"3"`
	MaximumDeviceTravel     *uint64     `json:"maximumDeviceTravel,omitempty" n2k:"4"`
	DirectionOfTravel       *uint64     `json:"directionOfTravel,omitempty" n2k:"5"`
}

func (m *LinearActuatorControlStatus) PGNNumber() uint32               { return 128780 }
func (m *LinearActuatorControlStatus) MessageInfo() MessageInfo        { return m.Info }
func (m *LinearActuatorControlStatus) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *LinearActuatorControlStatus) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *LinearActuatorControlStatus) EncodePayload() ([]uint8, error) { return encodeFields(m) }

type PayloadMass struct {
	Info              MessageInfo `json:"info"`
	Sid               *uint64     `json:"sid,omitempty" n2k:"1"`
	MeasurementStatus *uint64     `json:"measurementStatus,omitempty" n2k:"2"`
	MeasurementId     *uint64     `json:"measurementId,omitempty" n2k:"4"`
	PayloadMass       *uint64     `json:"payloadMass,omitempty" n2k:"5"`
}

func (m *PayloadMass) PGNNumber() uint32                   { return 130560 }
func (m *PayloadMass) MessageInfo() MessageInfo            { return m.Info }
func (m *PayloadMass) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *PayloadMass) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *PayloadMass) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

type WatermakerInputSettingAndStatus struct {
	Info                       MessageInfo `json:"info"`
	WatermakerOperatingState   *uint64     `json:"watermakerOperatingState,omitempty" n2k:"1"`
	ProductionStartStop        *uint64     `json:"productionStartStop,omitempty" n2k:"2"`
	RinseStartStop             *uint64     `json:"rinseStartStop,omitempty" n2k:"3"`
	LowPressurePumpStatus      *uint64     `json:"lowPressurePumpStatus,omitempty" n2k:"4"`
	HighPressurePumpStatus     *uint64     `json:"highPressurePumpStatus,omitempty" n2k:"5"`
	EmergencyStop              *uint64     `json:"emergencyStop,omitempty" n2k:"6"`
	ProductSolenoidValveStatus *uint64     `json:"productSolenoidValveStatus,omitempty" n2k:"7"`
	FlushModeStatus            *uint64     `json:"flushModeStatus,omitempty" n2k:"8"`
	SalinityStatus             *uint64     `json:"salinityStatus,omitempty" n2k:"9"`
	SensorStatus               *uint64     `json:"sensorStatus,omitempty" n2k:"10"`
	OilChangeIndicatorStatus   *uint64     `json:"oilChangeIndicatorStatus,omitempty" n2k:"11"`
	FilterStatus               *uint64     `json:"filterStatus,omitempty" n2k:"12"`
	SystemStatus               *uint64     `json:"systemStatus,omitempty" n2k:"13"`
	Salinity                   *uint64     `json:"salinity,omitempty" n2k:"15"`
	ProductWaterTemperature    *uint64     `json:"productWaterTemperature,omitempty" n2k:"16"`
	PreFilterPressure          *uint64     `json:"preFilterPressure,omitempty" n2k:"17"`
	PostFilterPressure         *uint64     `json:"postFilterPressure,omitempty" n2k:"18"`
	FeedPressure               *int64      `json:"feedPressure,omitempty" n2k:"19"`
	SystemHighPressure         *uint64     `json:"systemHighPressure,omitempty" n2k:"20"`
	ProductWaterFlow           *int64      `json:"productWaterFlow,omitempty" n2k:"21"`
	BrineWaterFlow             *int64      `json:"brineWaterFlow,omitempty" n2k:"22"`
	RunTime                    *uint64     `json:"runTime,omitempty" n2k:"23"`
}

func (m *WatermakerInputSettingAndStatus) PGNNumber() uint32               { return 130567 }
func (m *WatermakerInputSettingAndStatus) MessageInfo() MessageInfo        { return m.Info }
func (m *WatermakerInputSettingAndStatus) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *WatermakerInputSettingAndStatus) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *WatermakerInputSettingAndStatus) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// SalinityValue returns Salinity as a physical value in ppm (value = raw).
// The bool is false when Salinity is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *WatermakerInputSettingAndStatus) SalinityValue() (float64, bool) {
	if m.Salinity == nil {
		return 0, false
	}
	return float64(*m.Salinity), true
}

// SetSalinityValue sets Salinity from a physical value in ppm, rounded to the nearest
// wire tick of 1.
func (m *WatermakerInputSettingAndStatus) SetSalinityValue(v float64) {
	raw := uint64(math.Round(v))
	m.Salinity = &raw
}

// ProductWaterTemperatureValue returns ProductWaterTemperature as a physical value in K (value = raw * 0.01).
// The bool is false when ProductWaterTemperature is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *WatermakerInputSettingAndStatus) ProductWaterTemperatureValue() (float64, bool) {
	if m.ProductWaterTemperature == nil {
		return 0, false
	}
	return float64(*m.ProductWaterTemperature) * 0.01, true
}

// SetProductWaterTemperatureValue sets ProductWaterTemperature from a physical value in K, rounded to the nearest
// wire tick of 0.01.
func (m *WatermakerInputSettingAndStatus) SetProductWaterTemperatureValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.ProductWaterTemperature = &raw
}

// PreFilterPressureValue returns PreFilterPressure as a physical value in Pa (value = raw * 100).
// The bool is false when PreFilterPressure is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *WatermakerInputSettingAndStatus) PreFilterPressureValue() (float64, bool) {
	if m.PreFilterPressure == nil {
		return 0, false
	}
	return float64(*m.PreFilterPressure) * 100, true
}

// SetPreFilterPressureValue sets PreFilterPressure from a physical value in Pa, rounded to the nearest
// wire tick of 100.
func (m *WatermakerInputSettingAndStatus) SetPreFilterPressureValue(v float64) {
	raw := uint64(math.Round(v / 100))
	m.PreFilterPressure = &raw
}

// PostFilterPressureValue returns PostFilterPressure as a physical value in Pa (value = raw * 100).
// The bool is false when PostFilterPressure is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *WatermakerInputSettingAndStatus) PostFilterPressureValue() (float64, bool) {
	if m.PostFilterPressure == nil {
		return 0, false
	}
	return float64(*m.PostFilterPressure) * 100, true
}

// SetPostFilterPressureValue sets PostFilterPressure from a physical value in Pa, rounded to the nearest
// wire tick of 100.
func (m *WatermakerInputSettingAndStatus) SetPostFilterPressureValue(v float64) {
	raw := uint64(math.Round(v / 100))
	m.PostFilterPressure = &raw
}

// FeedPressureValue returns FeedPressure as a physical value in Pa (value = raw * 1000).
// The bool is false when FeedPressure is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *WatermakerInputSettingAndStatus) FeedPressureValue() (float64, bool) {
	if m.FeedPressure == nil {
		return 0, false
	}
	return float64(*m.FeedPressure) * 1000, true
}

// SetFeedPressureValue sets FeedPressure from a physical value in Pa, rounded to the nearest
// wire tick of 1000.
func (m *WatermakerInputSettingAndStatus) SetFeedPressureValue(v float64) {
	raw := int64(math.Round(v / 1000))
	m.FeedPressure = &raw
}

// SystemHighPressureValue returns SystemHighPressure as a physical value in Pa (value = raw * 1000).
// The bool is false when SystemHighPressure is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *WatermakerInputSettingAndStatus) SystemHighPressureValue() (float64, bool) {
	if m.SystemHighPressure == nil {
		return 0, false
	}
	return float64(*m.SystemHighPressure) * 1000, true
}

// SetSystemHighPressureValue sets SystemHighPressure from a physical value in Pa, rounded to the nearest
// wire tick of 1000.
func (m *WatermakerInputSettingAndStatus) SetSystemHighPressureValue(v float64) {
	raw := uint64(math.Round(v / 1000))
	m.SystemHighPressure = &raw
}

// ProductWaterFlowValue returns ProductWaterFlow as a physical value in L/h (value = raw * 0.1).
// The bool is false when ProductWaterFlow is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *WatermakerInputSettingAndStatus) ProductWaterFlowValue() (float64, bool) {
	if m.ProductWaterFlow == nil {
		return 0, false
	}
	return float64(*m.ProductWaterFlow) * 0.1, true
}

// SetProductWaterFlowValue sets ProductWaterFlow from a physical value in L/h, rounded to the nearest
// wire tick of 0.1.
func (m *WatermakerInputSettingAndStatus) SetProductWaterFlowValue(v float64) {
	raw := int64(math.Round(v / 0.1))
	m.ProductWaterFlow = &raw
}

// BrineWaterFlowValue returns BrineWaterFlow as a physical value in L/h (value = raw * 0.1).
// The bool is false when BrineWaterFlow is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *WatermakerInputSettingAndStatus) BrineWaterFlowValue() (float64, bool) {
	if m.BrineWaterFlow == nil {
		return 0, false
	}
	return float64(*m.BrineWaterFlow) * 0.1, true
}

// SetBrineWaterFlowValue sets BrineWaterFlow from a physical value in L/h, rounded to the nearest
// wire tick of 0.1.
func (m *WatermakerInputSettingAndStatus) SetBrineWaterFlowValue(v float64) {
	raw := int64(math.Round(v / 0.1))
	m.BrineWaterFlow = &raw
}

// RunTimeValue returns RunTime as a physical value in s (value = raw).
// The bool is false when RunTime is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *WatermakerInputSettingAndStatus) RunTimeValue() (float64, bool) {
	if m.RunTime == nil {
		return 0, false
	}
	return float64(*m.RunTime), true
}

// SetRunTimeValue sets RunTime from a physical value in s, rounded to the nearest
// wire tick of 1.
func (m *WatermakerInputSettingAndStatus) SetRunTimeValue(v float64) {
	raw := uint64(math.Round(v))
	m.RunTime = &raw
}
