// Code generated by PGN generator; DO NOT EDIT.
// Source schema 2.5.0 version 7.1.0.

package pgn

import "encoding/json"

type FurunoHeave struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Heave            *int64      `json:"heave,omitempty" n2k:"4"`
}

func (m *FurunoHeave) PGNNumber() uint32                   { return 65280 }
func (m *FurunoHeave) MessageInfo() MessageInfo            { return m.Info }
func (m *FurunoHeave) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *FurunoHeave) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *FurunoHeave) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *FurunoHeave) Clone() Message {
	if m == nil {
		return (*FurunoHeave)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Heave = clonePointer(m.Heave)
	return &copy
}

// HeaveValue returns Heave as a physical value in m (value = raw * 0.001).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoHeave) HeaveValue() (float64, bool) {
	if m == nil || m.Heave == nil {
		return 0, false
	}
	if *m.Heave == 2147483647 {
		return 0, false
	}
	if *m.Heave == 2147483646 {
		return 0, false
	}
	if *m.Heave == 2147483645 {
		return 0, false
	}
	value := float64(*m.Heave) * 0.001
	if value < -2.147483647e+06 && !approximatelyEqual(value, -2.147483647e+06) {
		return 0, false
	}
	if value > 2.147483644e+06 && !approximatelyEqual(value, 2.147483644e+06) {
		return 0, false
	}
	return value, true
}

// SetHeaveValue sets Heave from a physical value in m, rounded to the nearest
// wire tick of 0.001. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoHeave) SetHeaveValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("Heave", v)
	}
	if v < -2.147483647e+06 && !approximatelyEqual(v, -2.147483647e+06) {
		return invalidPhysicalValue("Heave", v)
	}
	if v > 2.147483644e+06 && !approximatelyEqual(v, 2.147483644e+06) {
		return invalidPhysicalValue("Heave", v)
	}
	ticks, err := physicalRawTicks(v, 0.001, 0, 32, true)
	if err != nil {
		return invalidPhysicalValue("Heave", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.Heave = &raw
	if _, ok := candidate.HeaveValue(); !ok {
		return invalidPhysicalValue("Heave", v)
	}
	m.Heave = &raw
	return nil
}

// MarshalJSON includes raw fields and derived physical values in schema units.
// Unavailable measurements are null. Physical values are output-only.
func (m FurunoHeave) MarshalJSON() ([]byte, error) {
	type raw FurunoHeave
	return json.Marshal(struct {
		raw
		Physical map[string]*physicalJSONValue `json:"physical"`
	}{
		raw: raw(m),
		Physical: map[string]*physicalJSONValue{
			"heave": physicalJSONMeasurement("m", m.HeaveValue),
		},
	})
}

type FurunoStatusAndVersionReport struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	ProprietaryId    *uint64     `json:"proprietaryId,omitempty" n2k:"4"`
	A                *uint64     `json:"a,omitempty" n2k:"5"`
	Status           string      `json:"status,omitempty" n2k:"6"`
}

func (m *FurunoStatusAndVersionReport) PGNNumber() uint32               { return 130816 }
func (m *FurunoStatusAndVersionReport) MessageInfo() MessageInfo        { return m.Info }
func (m *FurunoStatusAndVersionReport) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *FurunoStatusAndVersionReport) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *FurunoStatusAndVersionReport) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *FurunoStatusAndVersionReport) Clone() Message {
	if m == nil {
		return (*FurunoStatusAndVersionReport)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.ProprietaryId = clonePointer(m.ProprietaryId)
	copy.A = clonePointer(m.A)
	return &copy
}

type FurunoSvControl struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	F4               []uint8     `json:"f4,omitempty" n2k:"4"`
	F5               []uint8     `json:"f5,omitempty" n2k:"5"`
	SbasMode         *uint64     `json:"sbasMode,omitempty" n2k:"6"`
	SbasSatellite    *uint64     `json:"sbasSatellite,omitempty" n2k:"7"`
	F8               []uint8     `json:"f8,omitempty" n2k:"8"`
	GpsDisable       *uint64     `json:"gpsDisable,omitempty" n2k:"9"`
	GlonassDisable   *uint64     `json:"glonassDisable,omitempty" n2k:"10"`
	GalileoDisable   *uint64     `json:"galileoDisable,omitempty" n2k:"11"`
	QzssDisable      *uint64     `json:"qzssDisable,omitempty" n2k:"12"`
}

func (m *FurunoSvControl) PGNNumber() uint32                   { return 130817 }
func (m *FurunoSvControl) MessageInfo() MessageInfo            { return m.Info }
func (m *FurunoSvControl) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *FurunoSvControl) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *FurunoSvControl) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *FurunoSvControl) Clone() Message {
	if m == nil {
		return (*FurunoSvControl)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.F4 = cloneSlice(m.F4)
	copy.F5 = cloneSlice(m.F5)
	copy.SbasMode = clonePointer(m.SbasMode)
	copy.SbasSatellite = clonePointer(m.SbasSatellite)
	copy.F8 = cloneSlice(m.F8)
	copy.GpsDisable = clonePointer(m.GpsDisable)
	copy.GlonassDisable = clonePointer(m.GlonassDisable)
	copy.GalileoDisable = clonePointer(m.GalileoDisable)
	copy.QzssDisable = clonePointer(m.QzssDisable)
	return &copy
}

type FurunoSensorSetup struct {
	Info                   MessageInfo `json:"info"`
	ManufacturerCode       *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode           *uint64     `json:"industryCode,omitempty" n2k:"3"`
	RotationSmoothing      *uint64     `json:"rotationSmoothing,omitempty" n2k:"4"`
	HeadingOffset          *int64      `json:"headingOffset,omitempty" n2k:"5"`
	PitchOffset            *int64      `json:"pitchOffset,omitempty" n2k:"6"`
	RollOffset             *int64      `json:"rollOffset,omitempty" n2k:"7"`
	F8                     *uint64     `json:"f8,omitempty" n2k:"8"`
	F9                     *uint64     `json:"f9,omitempty" n2k:"9"`
	SogAndCogSmoothing     *int64      `json:"sogAndCogSmoothing,omitempty" n2k:"10"`
	Pgn3AxisSpeedSmoothing *int64      `json:"3AxisSpeedSmoothing,omitempty" n2k:"11"`
	Fc                     *uint64     `json:"fc,omitempty" n2k:"12"`
	Pgn3AxisOffset         *int64      `json:"3AxisOffset,omitempty" n2k:"13"`
	AirPressureOffset      *int64      `json:"airPressureOffset,omitempty" n2k:"14"`
	AirTemperatureOffset   *int64      `json:"airTemperatureOffset,omitempty" n2k:"15"`
}

func (m *FurunoSensorSetup) PGNNumber() uint32                   { return 130818 }
func (m *FurunoSensorSetup) MessageInfo() MessageInfo            { return m.Info }
func (m *FurunoSensorSetup) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *FurunoSensorSetup) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *FurunoSensorSetup) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *FurunoSensorSetup) Clone() Message {
	if m == nil {
		return (*FurunoSensorSetup)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.RotationSmoothing = clonePointer(m.RotationSmoothing)
	copy.HeadingOffset = clonePointer(m.HeadingOffset)
	copy.PitchOffset = clonePointer(m.PitchOffset)
	copy.RollOffset = clonePointer(m.RollOffset)
	copy.F8 = clonePointer(m.F8)
	copy.F9 = clonePointer(m.F9)
	copy.SogAndCogSmoothing = clonePointer(m.SogAndCogSmoothing)
	copy.Pgn3AxisSpeedSmoothing = clonePointer(m.Pgn3AxisSpeedSmoothing)
	copy.Fc = clonePointer(m.Fc)
	copy.Pgn3AxisOffset = clonePointer(m.Pgn3AxisOffset)
	copy.AirPressureOffset = clonePointer(m.AirPressureOffset)
	copy.AirTemperatureOffset = clonePointer(m.AirTemperatureOffset)
	return &copy
}

// RotationSmoothingValue returns RotationSmoothing as a physical value in s (value = raw * 0.1).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoSensorSetup) RotationSmoothingValue() (float64, bool) {
	if m == nil || m.RotationSmoothing == nil {
		return 0, false
	}
	if *m.RotationSmoothing == 65535 {
		return 0, false
	}
	if *m.RotationSmoothing == 65534 {
		return 0, false
	}
	if *m.RotationSmoothing == 65533 {
		return 0, false
	}
	value := float64(*m.RotationSmoothing) * 0.1
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 6553.2 && !approximatelyEqual(value, 6553.2) {
		return 0, false
	}
	return value, true
}

// SetRotationSmoothingValue sets RotationSmoothing from a physical value in s, rounded to the nearest
// wire tick of 0.1. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoSensorSetup) SetRotationSmoothingValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("RotationSmoothing", v)
	}
	if v < 0 && !approximatelyEqual(v, 0) {
		return invalidPhysicalValue("RotationSmoothing", v)
	}
	if v > 6553.2 && !approximatelyEqual(v, 6553.2) {
		return invalidPhysicalValue("RotationSmoothing", v)
	}
	ticks, err := physicalRawTicks(v, 0.1, 0, 16, false)
	if err != nil {
		return invalidPhysicalValue("RotationSmoothing", v)
	}
	raw := uint64(ticks)
	candidate := *m
	candidate.RotationSmoothing = &raw
	if _, ok := candidate.RotationSmoothingValue(); !ok {
		return invalidPhysicalValue("RotationSmoothing", v)
	}
	m.RotationSmoothing = &raw
	return nil
}

// HeadingOffsetValue returns HeadingOffset as a physical value in deg (value = raw * 0.1).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoSensorSetup) HeadingOffsetValue() (float64, bool) {
	if m == nil || m.HeadingOffset == nil {
		return 0, false
	}
	if *m.HeadingOffset == 32767 {
		return 0, false
	}
	if *m.HeadingOffset == 32766 {
		return 0, false
	}
	if *m.HeadingOffset == 32765 {
		return 0, false
	}
	value := float64(*m.HeadingOffset) * 0.1
	if value < -3276.7 && !approximatelyEqual(value, -3276.7) {
		return 0, false
	}
	if value > 3276.4 && !approximatelyEqual(value, 3276.4) {
		return 0, false
	}
	return value, true
}

// SetHeadingOffsetValue sets HeadingOffset from a physical value in deg, rounded to the nearest
// wire tick of 0.1. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoSensorSetup) SetHeadingOffsetValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("HeadingOffset", v)
	}
	if v < -3276.7 && !approximatelyEqual(v, -3276.7) {
		return invalidPhysicalValue("HeadingOffset", v)
	}
	if v > 3276.4 && !approximatelyEqual(v, 3276.4) {
		return invalidPhysicalValue("HeadingOffset", v)
	}
	ticks, err := physicalRawTicks(v, 0.1, 0, 16, true)
	if err != nil {
		return invalidPhysicalValue("HeadingOffset", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.HeadingOffset = &raw
	if _, ok := candidate.HeadingOffsetValue(); !ok {
		return invalidPhysicalValue("HeadingOffset", v)
	}
	m.HeadingOffset = &raw
	return nil
}

// PitchOffsetValue returns PitchOffset as a physical value in deg (value = raw * 0.1).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoSensorSetup) PitchOffsetValue() (float64, bool) {
	if m == nil || m.PitchOffset == nil {
		return 0, false
	}
	if *m.PitchOffset == 32767 {
		return 0, false
	}
	if *m.PitchOffset == 32766 {
		return 0, false
	}
	if *m.PitchOffset == 32765 {
		return 0, false
	}
	value := float64(*m.PitchOffset) * 0.1
	if value < -3276.7 && !approximatelyEqual(value, -3276.7) {
		return 0, false
	}
	if value > 3276.4 && !approximatelyEqual(value, 3276.4) {
		return 0, false
	}
	return value, true
}

// SetPitchOffsetValue sets PitchOffset from a physical value in deg, rounded to the nearest
// wire tick of 0.1. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoSensorSetup) SetPitchOffsetValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("PitchOffset", v)
	}
	if v < -3276.7 && !approximatelyEqual(v, -3276.7) {
		return invalidPhysicalValue("PitchOffset", v)
	}
	if v > 3276.4 && !approximatelyEqual(v, 3276.4) {
		return invalidPhysicalValue("PitchOffset", v)
	}
	ticks, err := physicalRawTicks(v, 0.1, 0, 16, true)
	if err != nil {
		return invalidPhysicalValue("PitchOffset", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.PitchOffset = &raw
	if _, ok := candidate.PitchOffsetValue(); !ok {
		return invalidPhysicalValue("PitchOffset", v)
	}
	m.PitchOffset = &raw
	return nil
}

// RollOffsetValue returns RollOffset as a physical value in deg (value = raw * 0.1).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoSensorSetup) RollOffsetValue() (float64, bool) {
	if m == nil || m.RollOffset == nil {
		return 0, false
	}
	if *m.RollOffset == 32767 {
		return 0, false
	}
	if *m.RollOffset == 32766 {
		return 0, false
	}
	if *m.RollOffset == 32765 {
		return 0, false
	}
	value := float64(*m.RollOffset) * 0.1
	if value < -3276.7 && !approximatelyEqual(value, -3276.7) {
		return 0, false
	}
	if value > 3276.4 && !approximatelyEqual(value, 3276.4) {
		return 0, false
	}
	return value, true
}

// SetRollOffsetValue sets RollOffset from a physical value in deg, rounded to the nearest
// wire tick of 0.1. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoSensorSetup) SetRollOffsetValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("RollOffset", v)
	}
	if v < -3276.7 && !approximatelyEqual(v, -3276.7) {
		return invalidPhysicalValue("RollOffset", v)
	}
	if v > 3276.4 && !approximatelyEqual(v, 3276.4) {
		return invalidPhysicalValue("RollOffset", v)
	}
	ticks, err := physicalRawTicks(v, 0.1, 0, 16, true)
	if err != nil {
		return invalidPhysicalValue("RollOffset", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.RollOffset = &raw
	if _, ok := candidate.RollOffsetValue(); !ok {
		return invalidPhysicalValue("RollOffset", v)
	}
	m.RollOffset = &raw
	return nil
}

// SogAndCogSmoothingValue returns SogAndCogSmoothing as a physical value in s (value = raw * 0.001).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoSensorSetup) SogAndCogSmoothingValue() (float64, bool) {
	if m == nil || m.SogAndCogSmoothing == nil {
		return 0, false
	}
	if *m.SogAndCogSmoothing == 2147483647 {
		return 0, false
	}
	if *m.SogAndCogSmoothing == 2147483646 {
		return 0, false
	}
	if *m.SogAndCogSmoothing == 2147483645 {
		return 0, false
	}
	value := float64(*m.SogAndCogSmoothing) * 0.001
	if value < -2.147483647e+06 && !approximatelyEqual(value, -2.147483647e+06) {
		return 0, false
	}
	if value > 2.147483644e+06 && !approximatelyEqual(value, 2.147483644e+06) {
		return 0, false
	}
	return value, true
}

// SetSogAndCogSmoothingValue sets SogAndCogSmoothing from a physical value in s, rounded to the nearest
// wire tick of 0.001. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoSensorSetup) SetSogAndCogSmoothingValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("SogAndCogSmoothing", v)
	}
	if v < -2.147483647e+06 && !approximatelyEqual(v, -2.147483647e+06) {
		return invalidPhysicalValue("SogAndCogSmoothing", v)
	}
	if v > 2.147483644e+06 && !approximatelyEqual(v, 2.147483644e+06) {
		return invalidPhysicalValue("SogAndCogSmoothing", v)
	}
	ticks, err := physicalRawTicks(v, 0.001, 0, 32, true)
	if err != nil {
		return invalidPhysicalValue("SogAndCogSmoothing", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.SogAndCogSmoothing = &raw
	if _, ok := candidate.SogAndCogSmoothingValue(); !ok {
		return invalidPhysicalValue("SogAndCogSmoothing", v)
	}
	m.SogAndCogSmoothing = &raw
	return nil
}

// Pgn3AxisSpeedSmoothingValue returns Pgn3AxisSpeedSmoothing as a physical value in s (value = raw * 0.001).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoSensorSetup) Pgn3AxisSpeedSmoothingValue() (float64, bool) {
	if m == nil || m.Pgn3AxisSpeedSmoothing == nil {
		return 0, false
	}
	if *m.Pgn3AxisSpeedSmoothing == 2147483647 {
		return 0, false
	}
	if *m.Pgn3AxisSpeedSmoothing == 2147483646 {
		return 0, false
	}
	if *m.Pgn3AxisSpeedSmoothing == 2147483645 {
		return 0, false
	}
	value := float64(*m.Pgn3AxisSpeedSmoothing) * 0.001
	if value < -2.147483647e+06 && !approximatelyEqual(value, -2.147483647e+06) {
		return 0, false
	}
	if value > 2.147483644e+06 && !approximatelyEqual(value, 2.147483644e+06) {
		return 0, false
	}
	return value, true
}

// SetPgn3AxisSpeedSmoothingValue sets Pgn3AxisSpeedSmoothing from a physical value in s, rounded to the nearest
// wire tick of 0.001. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoSensorSetup) SetPgn3AxisSpeedSmoothingValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("Pgn3AxisSpeedSmoothing", v)
	}
	if v < -2.147483647e+06 && !approximatelyEqual(v, -2.147483647e+06) {
		return invalidPhysicalValue("Pgn3AxisSpeedSmoothing", v)
	}
	if v > 2.147483644e+06 && !approximatelyEqual(v, 2.147483644e+06) {
		return invalidPhysicalValue("Pgn3AxisSpeedSmoothing", v)
	}
	ticks, err := physicalRawTicks(v, 0.001, 0, 32, true)
	if err != nil {
		return invalidPhysicalValue("Pgn3AxisSpeedSmoothing", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.Pgn3AxisSpeedSmoothing = &raw
	if _, ok := candidate.Pgn3AxisSpeedSmoothingValue(); !ok {
		return invalidPhysicalValue("Pgn3AxisSpeedSmoothing", v)
	}
	m.Pgn3AxisSpeedSmoothing = &raw
	return nil
}

// Pgn3AxisOffsetValue returns Pgn3AxisOffset as a physical value in % (value = raw * 0.00032).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoSensorSetup) Pgn3AxisOffsetValue() (float64, bool) {
	if m == nil || m.Pgn3AxisOffset == nil {
		return 0, false
	}
	if *m.Pgn3AxisOffset == 32767 {
		return 0, false
	}
	if *m.Pgn3AxisOffset == 32766 {
		return 0, false
	}
	if *m.Pgn3AxisOffset == 32765 {
		return 0, false
	}
	value := float64(*m.Pgn3AxisOffset) * 0.00032
	if value < -12.5 && !approximatelyEqual(value, -12.5) {
		return 0, false
	}
	if value > 12.5 && !approximatelyEqual(value, 12.5) {
		return 0, false
	}
	return value, true
}

// SetPgn3AxisOffsetValue sets Pgn3AxisOffset from a physical value in %, rounded to the nearest
// wire tick of 0.00032. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoSensorSetup) SetPgn3AxisOffsetValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("Pgn3AxisOffset", v)
	}
	if v < -12.5 && !approximatelyEqual(v, -12.5) {
		return invalidPhysicalValue("Pgn3AxisOffset", v)
	}
	if v > 12.5 && !approximatelyEqual(v, 12.5) {
		return invalidPhysicalValue("Pgn3AxisOffset", v)
	}
	ticks, err := physicalRawTicks(v, 0.00032, 0, 16, true)
	if err != nil {
		return invalidPhysicalValue("Pgn3AxisOffset", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.Pgn3AxisOffset = &raw
	if _, ok := candidate.Pgn3AxisOffsetValue(); !ok {
		return invalidPhysicalValue("Pgn3AxisOffset", v)
	}
	m.Pgn3AxisOffset = &raw
	return nil
}

// AirPressureOffsetValue returns AirPressureOffset as a physical value in Pa (value = raw * 10).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoSensorSetup) AirPressureOffsetValue() (float64, bool) {
	if m == nil || m.AirPressureOffset == nil {
		return 0, false
	}
	if *m.AirPressureOffset == 32767 {
		return 0, false
	}
	if *m.AirPressureOffset == 32766 {
		return 0, false
	}
	if *m.AirPressureOffset == 32765 {
		return 0, false
	}
	value := float64(*m.AirPressureOffset) * 10
	if value < -99.9 && !approximatelyEqual(value, -99.9) {
		return 0, false
	}
	if value > 99.9 && !approximatelyEqual(value, 99.9) {
		return 0, false
	}
	return value, true
}

// SetAirPressureOffsetValue sets AirPressureOffset from a physical value in Pa, rounded to the nearest
// wire tick of 10. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoSensorSetup) SetAirPressureOffsetValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("AirPressureOffset", v)
	}
	if v < -99.9 && !approximatelyEqual(v, -99.9) {
		return invalidPhysicalValue("AirPressureOffset", v)
	}
	if v > 99.9 && !approximatelyEqual(v, 99.9) {
		return invalidPhysicalValue("AirPressureOffset", v)
	}
	ticks, err := physicalRawTicks(v, 10, 0, 16, true)
	if err != nil {
		return invalidPhysicalValue("AirPressureOffset", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.AirPressureOffset = &raw
	if _, ok := candidate.AirPressureOffsetValue(); !ok {
		return invalidPhysicalValue("AirPressureOffset", v)
	}
	m.AirPressureOffset = &raw
	return nil
}

// AirTemperatureOffsetValue returns AirTemperatureOffset as a physical value in K (value = raw * 0.1).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoSensorSetup) AirTemperatureOffsetValue() (float64, bool) {
	if m == nil || m.AirTemperatureOffset == nil {
		return 0, false
	}
	if *m.AirTemperatureOffset == 32767 {
		return 0, false
	}
	if *m.AirTemperatureOffset == 32766 {
		return 0, false
	}
	if *m.AirTemperatureOffset == 32765 {
		return 0, false
	}
	value := float64(*m.AirTemperatureOffset) * 0.1
	if value < -99.9 && !approximatelyEqual(value, -99.9) {
		return 0, false
	}
	if value > 99.9 && !approximatelyEqual(value, 99.9) {
		return 0, false
	}
	return value, true
}

// SetAirTemperatureOffsetValue sets AirTemperatureOffset from a physical value in K, rounded to the nearest
// wire tick of 0.1. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoSensorSetup) SetAirTemperatureOffsetValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("AirTemperatureOffset", v)
	}
	if v < -99.9 && !approximatelyEqual(v, -99.9) {
		return invalidPhysicalValue("AirTemperatureOffset", v)
	}
	if v > 99.9 && !approximatelyEqual(v, 99.9) {
		return invalidPhysicalValue("AirTemperatureOffset", v)
	}
	ticks, err := physicalRawTicks(v, 0.1, 0, 16, true)
	if err != nil {
		return invalidPhysicalValue("AirTemperatureOffset", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.AirTemperatureOffset = &raw
	if _, ok := candidate.AirTemperatureOffsetValue(); !ok {
		return invalidPhysicalValue("AirTemperatureOffset", v)
	}
	m.AirTemperatureOffset = &raw
	return nil
}

// MarshalJSON includes raw fields and derived physical values in schema units.
// Unavailable measurements are null. Physical values are output-only.
func (m FurunoSensorSetup) MarshalJSON() ([]byte, error) {
	type raw FurunoSensorSetup
	return json.Marshal(struct {
		raw
		Physical map[string]*physicalJSONValue `json:"physical"`
	}{
		raw: raw(m),
		Physical: map[string]*physicalJSONValue{
			"rotationSmoothing":    physicalJSONMeasurement("s", m.RotationSmoothingValue),
			"headingOffset":        physicalJSONMeasurement("deg", m.HeadingOffsetValue),
			"pitchOffset":          physicalJSONMeasurement("deg", m.PitchOffsetValue),
			"rollOffset":           physicalJSONMeasurement("deg", m.RollOffsetValue),
			"sogAndCogSmoothing":   physicalJSONMeasurement("s", m.SogAndCogSmoothingValue),
			"3AxisSpeedSmoothing":  physicalJSONMeasurement("s", m.Pgn3AxisSpeedSmoothingValue),
			"3AxisOffset":          physicalJSONMeasurement("%", m.Pgn3AxisOffsetValue),
			"airPressureOffset":    physicalJSONMeasurement("Pa", m.AirPressureOffsetValue),
			"airTemperatureOffset": physicalJSONMeasurement("K", m.AirTemperatureOffsetValue),
		},
	})
}

type FurunoDeadReckoningConfiguration struct {
	Info              MessageInfo `json:"info"`
	ManufacturerCode  *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode      *uint64     `json:"industryCode,omitempty" n2k:"3"`
	F4                *uint64     `json:"f4,omitempty" n2k:"4"`
	F5                *uint64     `json:"f5,omitempty" n2k:"5"`
	F6                *uint64     `json:"f6,omitempty" n2k:"6"`
	F7                *uint64     `json:"f7,omitempty" n2k:"7"`
	F8                *uint64     `json:"f8,omitempty" n2k:"8"`
	DeadReckoningTime *uint64     `json:"deadReckoningTime,omitempty" n2k:"9"`
	F10               *uint64     `json:"f10,omitempty" n2k:"10"`
	F11               *uint64     `json:"f11,omitempty" n2k:"11"`
}

func (m *FurunoDeadReckoningConfiguration) PGNNumber() uint32               { return 130819 }
func (m *FurunoDeadReckoningConfiguration) MessageInfo() MessageInfo        { return m.Info }
func (m *FurunoDeadReckoningConfiguration) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *FurunoDeadReckoningConfiguration) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *FurunoDeadReckoningConfiguration) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *FurunoDeadReckoningConfiguration) Clone() Message {
	if m == nil {
		return (*FurunoDeadReckoningConfiguration)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.F4 = clonePointer(m.F4)
	copy.F5 = clonePointer(m.F5)
	copy.F6 = clonePointer(m.F6)
	copy.F7 = clonePointer(m.F7)
	copy.F8 = clonePointer(m.F8)
	copy.DeadReckoningTime = clonePointer(m.DeadReckoningTime)
	copy.F10 = clonePointer(m.F10)
	copy.F11 = clonePointer(m.F11)
	return &copy
}

type FurunoUnknown130820 struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	A                *uint64     `json:"a,omitempty" n2k:"4"`
	B                *uint64     `json:"b,omitempty" n2k:"5"`
	C                *uint64     `json:"c,omitempty" n2k:"6"`
	D                *uint64     `json:"d,omitempty" n2k:"7"`
	E                *uint64     `json:"e,omitempty" n2k:"8"`
}

func (m *FurunoUnknown130820) PGNNumber() uint32                   { return 130820 }
func (m *FurunoUnknown130820) MessageInfo() MessageInfo            { return m.Info }
func (m *FurunoUnknown130820) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *FurunoUnknown130820) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *FurunoUnknown130820) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *FurunoUnknown130820) Clone() Message {
	if m == nil {
		return (*FurunoUnknown130820)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.A = clonePointer(m.A)
	copy.B = clonePointer(m.B)
	copy.C = clonePointer(m.C)
	copy.D = clonePointer(m.D)
	copy.E = clonePointer(m.E)
	return &copy
}

type FurunoUnknown130821 struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Sid              *uint64     `json:"sid,omitempty" n2k:"4"`
	A                *uint64     `json:"a,omitempty" n2k:"5"`
	B                *uint64     `json:"b,omitempty" n2k:"6"`
	C                *uint64     `json:"c,omitempty" n2k:"7"`
	D                *uint64     `json:"d,omitempty" n2k:"8"`
	E                *uint64     `json:"e,omitempty" n2k:"9"`
	F                *uint64     `json:"f,omitempty" n2k:"10"`
	G                *uint64     `json:"g,omitempty" n2k:"11"`
	H                *uint64     `json:"h,omitempty" n2k:"12"`
	I                *uint64     `json:"i,omitempty" n2k:"13"`
}

func (m *FurunoUnknown130821) PGNNumber() uint32                   { return 130821 }
func (m *FurunoUnknown130821) MessageInfo() MessageInfo            { return m.Info }
func (m *FurunoUnknown130821) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *FurunoUnknown130821) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *FurunoUnknown130821) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *FurunoUnknown130821) Clone() Message {
	if m == nil {
		return (*FurunoUnknown130821)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Sid = clonePointer(m.Sid)
	copy.A = clonePointer(m.A)
	copy.B = clonePointer(m.B)
	copy.C = clonePointer(m.C)
	copy.D = clonePointer(m.D)
	copy.E = clonePointer(m.E)
	copy.F = clonePointer(m.F)
	copy.G = clonePointer(m.G)
	copy.H = clonePointer(m.H)
	copy.I = clonePointer(m.I)
	return &copy
}

type FurunoNavpilotStatus struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	MessageId        *uint64     `json:"messageId,omitempty" n2k:"4"`
	RudderAngle      *uint64     `json:"rudderAngle,omitempty" n2k:"5"`
	A                *int64      `json:"a,omitempty" n2k:"6"`
	B                *uint64     `json:"b,omitempty" n2k:"7"`
	CommandedCourse  *uint64     `json:"commandedCourse,omitempty" n2k:"8"`
	C                *uint64     `json:"c,omitempty" n2k:"9"`
	D                *uint64     `json:"d,omitempty" n2k:"10"`
}

func (m *FurunoNavpilotStatus) PGNNumber() uint32                   { return 130827 }
func (m *FurunoNavpilotStatus) MessageInfo() MessageInfo            { return m.Info }
func (m *FurunoNavpilotStatus) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *FurunoNavpilotStatus) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *FurunoNavpilotStatus) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *FurunoNavpilotStatus) Clone() Message {
	if m == nil {
		return (*FurunoNavpilotStatus)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.MessageId = clonePointer(m.MessageId)
	copy.RudderAngle = clonePointer(m.RudderAngle)
	copy.A = clonePointer(m.A)
	copy.B = clonePointer(m.B)
	copy.CommandedCourse = clonePointer(m.CommandedCourse)
	copy.C = clonePointer(m.C)
	copy.D = clonePointer(m.D)
	return &copy
}

// RudderAngleValue returns RudderAngle as a physical value in rad (value = raw * 0.0001).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoNavpilotStatus) RudderAngleValue() (float64, bool) {
	if m == nil || m.RudderAngle == nil {
		return 0, false
	}
	if *m.RudderAngle == 65535 {
		return 0, false
	}
	if *m.RudderAngle == 65534 {
		return 0, false
	}
	if *m.RudderAngle == 65533 {
		return 0, false
	}
	value := float64(*m.RudderAngle) * 0.0001
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 6.2831852 && !approximatelyEqual(value, 6.2831852) {
		return 0, false
	}
	return value, true
}

// SetRudderAngleValue sets RudderAngle from a physical value in rad, rounded to the nearest
// wire tick of 0.0001. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoNavpilotStatus) SetRudderAngleValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("RudderAngle", v)
	}
	if v < 0 && !approximatelyEqual(v, 0) {
		return invalidPhysicalValue("RudderAngle", v)
	}
	if v > 6.2831852 && !approximatelyEqual(v, 6.2831852) {
		return invalidPhysicalValue("RudderAngle", v)
	}
	ticks, err := physicalRawTicks(v, 0.0001, 0, 16, false)
	if err != nil {
		return invalidPhysicalValue("RudderAngle", v)
	}
	raw := uint64(ticks)
	candidate := *m
	candidate.RudderAngle = &raw
	if _, ok := candidate.RudderAngleValue(); !ok {
		return invalidPhysicalValue("RudderAngle", v)
	}
	m.RudderAngle = &raw
	return nil
}

// CommandedCourseValue returns CommandedCourse as a physical value in rad (value = raw * 0.0001).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoNavpilotStatus) CommandedCourseValue() (float64, bool) {
	if m == nil || m.CommandedCourse == nil {
		return 0, false
	}
	if *m.CommandedCourse == 65535 {
		return 0, false
	}
	if *m.CommandedCourse == 65534 {
		return 0, false
	}
	if *m.CommandedCourse == 65533 {
		return 0, false
	}
	value := float64(*m.CommandedCourse) * 0.0001
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 6.2831852 && !approximatelyEqual(value, 6.2831852) {
		return 0, false
	}
	return value, true
}

// SetCommandedCourseValue sets CommandedCourse from a physical value in rad, rounded to the nearest
// wire tick of 0.0001. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoNavpilotStatus) SetCommandedCourseValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("CommandedCourse", v)
	}
	if v < 0 && !approximatelyEqual(v, 0) {
		return invalidPhysicalValue("CommandedCourse", v)
	}
	if v > 6.2831852 && !approximatelyEqual(v, 6.2831852) {
		return invalidPhysicalValue("CommandedCourse", v)
	}
	ticks, err := physicalRawTicks(v, 0.0001, 0, 16, false)
	if err != nil {
		return invalidPhysicalValue("CommandedCourse", v)
	}
	raw := uint64(ticks)
	candidate := *m
	candidate.CommandedCourse = &raw
	if _, ok := candidate.CommandedCourseValue(); !ok {
		return invalidPhysicalValue("CommandedCourse", v)
	}
	m.CommandedCourse = &raw
	return nil
}

// MarshalJSON includes raw fields and derived physical values in schema units.
// Unavailable measurements are null. Physical values are output-only.
func (m FurunoNavpilotStatus) MarshalJSON() ([]byte, error) {
	type raw FurunoNavpilotStatus
	return json.Marshal(struct {
		raw
		Physical map[string]*physicalJSONValue `json:"physical"`
	}{
		raw: raw(m),
		Physical: map[string]*physicalJSONValue{
			"rudderAngle":     physicalJSONMeasurement("rad", m.RudderAngleValue),
			"commandedCourse": physicalJSONMeasurement("rad", m.CommandedCourseValue),
		},
	})
}

type FurunoShipParametersAndAntennaPosition struct {
	Info                    MessageInfo `json:"info"`
	ManufacturerCode        *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode            *uint64     `json:"industryCode,omitempty" n2k:"3"`
	EquipmentIdentification *uint64     `json:"equipmentIdentification,omitempty" n2k:"4"`
	AntennaPositionX        *int64      `json:"antennaPositionX,omitempty" n2k:"5"`
	AntennaPositionY        *uint64     `json:"antennaPositionY,omitempty" n2k:"6"`
	AntennaPositionZ        *uint64     `json:"antennaPositionZ,omitempty" n2k:"7"`
	ShipSWidth              *uint64     `json:"shipSWidth,omitempty" n2k:"8"`
	ShipSLength             *uint64     `json:"shipSLength,omitempty" n2k:"9"`
	ShipSHeight             *uint64     `json:"shipSHeight,omitempty" n2k:"10"`
}

func (m *FurunoShipParametersAndAntennaPosition) PGNNumber() uint32               { return 130833 }
func (m *FurunoShipParametersAndAntennaPosition) MessageInfo() MessageInfo        { return m.Info }
func (m *FurunoShipParametersAndAntennaPosition) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *FurunoShipParametersAndAntennaPosition) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *FurunoShipParametersAndAntennaPosition) EncodePayload() ([]uint8, error) {
	return encodeFields(m)
}

// Clone returns a message owning every mutable field and retained wire byte.
func (m *FurunoShipParametersAndAntennaPosition) Clone() Message {
	if m == nil {
		return (*FurunoShipParametersAndAntennaPosition)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.EquipmentIdentification = clonePointer(m.EquipmentIdentification)
	copy.AntennaPositionX = clonePointer(m.AntennaPositionX)
	copy.AntennaPositionY = clonePointer(m.AntennaPositionY)
	copy.AntennaPositionZ = clonePointer(m.AntennaPositionZ)
	copy.ShipSWidth = clonePointer(m.ShipSWidth)
	copy.ShipSLength = clonePointer(m.ShipSLength)
	copy.ShipSHeight = clonePointer(m.ShipSHeight)
	return &copy
}

// AntennaPositionXValue returns AntennaPositionX as a physical value in m (value = raw * 0.01).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoShipParametersAndAntennaPosition) AntennaPositionXValue() (float64, bool) {
	if m == nil || m.AntennaPositionX == nil {
		return 0, false
	}
	if *m.AntennaPositionX == 32767 {
		return 0, false
	}
	if *m.AntennaPositionX == 32766 {
		return 0, false
	}
	if *m.AntennaPositionX == 32765 {
		return 0, false
	}
	value := float64(*m.AntennaPositionX) * 0.01
	if value < -327.67 && !approximatelyEqual(value, -327.67) {
		return 0, false
	}
	if value > 327.64 && !approximatelyEqual(value, 327.64) {
		return 0, false
	}
	return value, true
}

// SetAntennaPositionXValue sets AntennaPositionX from a physical value in m, rounded to the nearest
// wire tick of 0.01. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoShipParametersAndAntennaPosition) SetAntennaPositionXValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("AntennaPositionX", v)
	}
	if v < -327.67 && !approximatelyEqual(v, -327.67) {
		return invalidPhysicalValue("AntennaPositionX", v)
	}
	if v > 327.64 && !approximatelyEqual(v, 327.64) {
		return invalidPhysicalValue("AntennaPositionX", v)
	}
	ticks, err := physicalRawTicks(v, 0.01, 0, 16, true)
	if err != nil {
		return invalidPhysicalValue("AntennaPositionX", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.AntennaPositionX = &raw
	if _, ok := candidate.AntennaPositionXValue(); !ok {
		return invalidPhysicalValue("AntennaPositionX", v)
	}
	m.AntennaPositionX = &raw
	return nil
}

// AntennaPositionYValue returns AntennaPositionY as a physical value in m (value = raw * 0.1).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoShipParametersAndAntennaPosition) AntennaPositionYValue() (float64, bool) {
	if m == nil || m.AntennaPositionY == nil {
		return 0, false
	}
	if *m.AntennaPositionY == 65535 {
		return 0, false
	}
	if *m.AntennaPositionY == 65534 {
		return 0, false
	}
	if *m.AntennaPositionY == 65533 {
		return 0, false
	}
	value := float64(*m.AntennaPositionY) * 0.1
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 6553.2 && !approximatelyEqual(value, 6553.2) {
		return 0, false
	}
	return value, true
}

// SetAntennaPositionYValue sets AntennaPositionY from a physical value in m, rounded to the nearest
// wire tick of 0.1. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoShipParametersAndAntennaPosition) SetAntennaPositionYValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("AntennaPositionY", v)
	}
	if v < 0 && !approximatelyEqual(v, 0) {
		return invalidPhysicalValue("AntennaPositionY", v)
	}
	if v > 6553.2 && !approximatelyEqual(v, 6553.2) {
		return invalidPhysicalValue("AntennaPositionY", v)
	}
	ticks, err := physicalRawTicks(v, 0.1, 0, 16, false)
	if err != nil {
		return invalidPhysicalValue("AntennaPositionY", v)
	}
	raw := uint64(ticks)
	candidate := *m
	candidate.AntennaPositionY = &raw
	if _, ok := candidate.AntennaPositionYValue(); !ok {
		return invalidPhysicalValue("AntennaPositionY", v)
	}
	m.AntennaPositionY = &raw
	return nil
}

// AntennaPositionZValue returns AntennaPositionZ as a physical value in m (value = raw * 0.1).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoShipParametersAndAntennaPosition) AntennaPositionZValue() (float64, bool) {
	if m == nil || m.AntennaPositionZ == nil {
		return 0, false
	}
	if *m.AntennaPositionZ == 65535 {
		return 0, false
	}
	if *m.AntennaPositionZ == 65534 {
		return 0, false
	}
	if *m.AntennaPositionZ == 65533 {
		return 0, false
	}
	value := float64(*m.AntennaPositionZ) * 0.1
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 6553.2 && !approximatelyEqual(value, 6553.2) {
		return 0, false
	}
	return value, true
}

// SetAntennaPositionZValue sets AntennaPositionZ from a physical value in m, rounded to the nearest
// wire tick of 0.1. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoShipParametersAndAntennaPosition) SetAntennaPositionZValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("AntennaPositionZ", v)
	}
	if v < 0 && !approximatelyEqual(v, 0) {
		return invalidPhysicalValue("AntennaPositionZ", v)
	}
	if v > 6553.2 && !approximatelyEqual(v, 6553.2) {
		return invalidPhysicalValue("AntennaPositionZ", v)
	}
	ticks, err := physicalRawTicks(v, 0.1, 0, 16, false)
	if err != nil {
		return invalidPhysicalValue("AntennaPositionZ", v)
	}
	raw := uint64(ticks)
	candidate := *m
	candidate.AntennaPositionZ = &raw
	if _, ok := candidate.AntennaPositionZValue(); !ok {
		return invalidPhysicalValue("AntennaPositionZ", v)
	}
	m.AntennaPositionZ = &raw
	return nil
}

// ShipSWidthValue returns ShipSWidth as a physical value in m (value = raw * 0.1).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoShipParametersAndAntennaPosition) ShipSWidthValue() (float64, bool) {
	if m == nil || m.ShipSWidth == nil {
		return 0, false
	}
	if *m.ShipSWidth == 65535 {
		return 0, false
	}
	if *m.ShipSWidth == 65534 {
		return 0, false
	}
	if *m.ShipSWidth == 65533 {
		return 0, false
	}
	value := float64(*m.ShipSWidth) * 0.1
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 6553.2 && !approximatelyEqual(value, 6553.2) {
		return 0, false
	}
	return value, true
}

// SetShipSWidthValue sets ShipSWidth from a physical value in m, rounded to the nearest
// wire tick of 0.1. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoShipParametersAndAntennaPosition) SetShipSWidthValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("ShipSWidth", v)
	}
	if v < 0 && !approximatelyEqual(v, 0) {
		return invalidPhysicalValue("ShipSWidth", v)
	}
	if v > 6553.2 && !approximatelyEqual(v, 6553.2) {
		return invalidPhysicalValue("ShipSWidth", v)
	}
	ticks, err := physicalRawTicks(v, 0.1, 0, 16, false)
	if err != nil {
		return invalidPhysicalValue("ShipSWidth", v)
	}
	raw := uint64(ticks)
	candidate := *m
	candidate.ShipSWidth = &raw
	if _, ok := candidate.ShipSWidthValue(); !ok {
		return invalidPhysicalValue("ShipSWidth", v)
	}
	m.ShipSWidth = &raw
	return nil
}

// ShipSLengthValue returns ShipSLength as a physical value in m (value = raw * 0.1).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoShipParametersAndAntennaPosition) ShipSLengthValue() (float64, bool) {
	if m == nil || m.ShipSLength == nil {
		return 0, false
	}
	if *m.ShipSLength == 65535 {
		return 0, false
	}
	if *m.ShipSLength == 65534 {
		return 0, false
	}
	if *m.ShipSLength == 65533 {
		return 0, false
	}
	value := float64(*m.ShipSLength) * 0.1
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 6553.2 && !approximatelyEqual(value, 6553.2) {
		return 0, false
	}
	return value, true
}

// SetShipSLengthValue sets ShipSLength from a physical value in m, rounded to the nearest
// wire tick of 0.1. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoShipParametersAndAntennaPosition) SetShipSLengthValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("ShipSLength", v)
	}
	if v < 0 && !approximatelyEqual(v, 0) {
		return invalidPhysicalValue("ShipSLength", v)
	}
	if v > 6553.2 && !approximatelyEqual(v, 6553.2) {
		return invalidPhysicalValue("ShipSLength", v)
	}
	ticks, err := physicalRawTicks(v, 0.1, 0, 16, false)
	if err != nil {
		return invalidPhysicalValue("ShipSLength", v)
	}
	raw := uint64(ticks)
	candidate := *m
	candidate.ShipSLength = &raw
	if _, ok := candidate.ShipSLengthValue(); !ok {
		return invalidPhysicalValue("ShipSLength", v)
	}
	m.ShipSLength = &raw
	return nil
}

// ShipSHeightValue returns ShipSHeight as a physical value in m (value = raw * 0.1).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoShipParametersAndAntennaPosition) ShipSHeightValue() (float64, bool) {
	if m == nil || m.ShipSHeight == nil {
		return 0, false
	}
	if *m.ShipSHeight == 65535 {
		return 0, false
	}
	if *m.ShipSHeight == 65534 {
		return 0, false
	}
	if *m.ShipSHeight == 65533 {
		return 0, false
	}
	value := float64(*m.ShipSHeight) * 0.1
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 6553.2 && !approximatelyEqual(value, 6553.2) {
		return 0, false
	}
	return value, true
}

// SetShipSHeightValue sets ShipSHeight from a physical value in m, rounded to the nearest
// wire tick of 0.1. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoShipParametersAndAntennaPosition) SetShipSHeightValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("ShipSHeight", v)
	}
	if v < 0 && !approximatelyEqual(v, 0) {
		return invalidPhysicalValue("ShipSHeight", v)
	}
	if v > 6553.2 && !approximatelyEqual(v, 6553.2) {
		return invalidPhysicalValue("ShipSHeight", v)
	}
	ticks, err := physicalRawTicks(v, 0.1, 0, 16, false)
	if err != nil {
		return invalidPhysicalValue("ShipSHeight", v)
	}
	raw := uint64(ticks)
	candidate := *m
	candidate.ShipSHeight = &raw
	if _, ok := candidate.ShipSHeightValue(); !ok {
		return invalidPhysicalValue("ShipSHeight", v)
	}
	m.ShipSHeight = &raw
	return nil
}

// MarshalJSON includes raw fields and derived physical values in schema units.
// Unavailable measurements are null. Physical values are output-only.
func (m FurunoShipParametersAndAntennaPosition) MarshalJSON() ([]byte, error) {
	type raw FurunoShipParametersAndAntennaPosition
	return json.Marshal(struct {
		raw
		Physical map[string]*physicalJSONValue `json:"physical"`
	}{
		raw: raw(m),
		Physical: map[string]*physicalJSONValue{
			"antennaPositionX": physicalJSONMeasurement("m", m.AntennaPositionXValue),
			"antennaPositionY": physicalJSONMeasurement("m", m.AntennaPositionYValue),
			"antennaPositionZ": physicalJSONMeasurement("m", m.AntennaPositionZValue),
			"shipSWidth":       physicalJSONMeasurement("m", m.ShipSWidthValue),
			"shipSLength":      physicalJSONMeasurement("m", m.ShipSLengthValue),
			"shipSHeight":      physicalJSONMeasurement("m", m.ShipSHeightValue),
		},
	})
}

type FurunoSpeedCalculationPosition struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	PointIndex       *uint64     `json:"pointIndex,omitempty" n2k:"4"`
	PositionY        *uint64     `json:"positionY,omitempty" n2k:"6"`
	PositionZ        *uint64     `json:"positionZ,omitempty" n2k:"7"`
}

func (m *FurunoSpeedCalculationPosition) PGNNumber() uint32               { return 130834 }
func (m *FurunoSpeedCalculationPosition) MessageInfo() MessageInfo        { return m.Info }
func (m *FurunoSpeedCalculationPosition) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *FurunoSpeedCalculationPosition) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *FurunoSpeedCalculationPosition) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *FurunoSpeedCalculationPosition) Clone() Message {
	if m == nil {
		return (*FurunoSpeedCalculationPosition)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.PointIndex = clonePointer(m.PointIndex)
	copy.PositionY = clonePointer(m.PositionY)
	copy.PositionZ = clonePointer(m.PositionZ)
	return &copy
}

// PositionYValue returns PositionY as a physical value in m (value = raw * 0.1).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoSpeedCalculationPosition) PositionYValue() (float64, bool) {
	if m == nil || m.PositionY == nil {
		return 0, false
	}
	if *m.PositionY == 65535 {
		return 0, false
	}
	if *m.PositionY == 65534 {
		return 0, false
	}
	if *m.PositionY == 65533 {
		return 0, false
	}
	value := float64(*m.PositionY) * 0.1
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 6553.2 && !approximatelyEqual(value, 6553.2) {
		return 0, false
	}
	return value, true
}

// SetPositionYValue sets PositionY from a physical value in m, rounded to the nearest
// wire tick of 0.1. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoSpeedCalculationPosition) SetPositionYValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("PositionY", v)
	}
	if v < 0 && !approximatelyEqual(v, 0) {
		return invalidPhysicalValue("PositionY", v)
	}
	if v > 6553.2 && !approximatelyEqual(v, 6553.2) {
		return invalidPhysicalValue("PositionY", v)
	}
	ticks, err := physicalRawTicks(v, 0.1, 0, 16, false)
	if err != nil {
		return invalidPhysicalValue("PositionY", v)
	}
	raw := uint64(ticks)
	candidate := *m
	candidate.PositionY = &raw
	if _, ok := candidate.PositionYValue(); !ok {
		return invalidPhysicalValue("PositionY", v)
	}
	m.PositionY = &raw
	return nil
}

// PositionZValue returns PositionZ as a physical value in m (value = raw * 0.1).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoSpeedCalculationPosition) PositionZValue() (float64, bool) {
	if m == nil || m.PositionZ == nil {
		return 0, false
	}
	if *m.PositionZ == 65535 {
		return 0, false
	}
	if *m.PositionZ == 65534 {
		return 0, false
	}
	if *m.PositionZ == 65533 {
		return 0, false
	}
	value := float64(*m.PositionZ) * 0.1
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 6553.2 && !approximatelyEqual(value, 6553.2) {
		return 0, false
	}
	return value, true
}

// SetPositionZValue sets PositionZ from a physical value in m, rounded to the nearest
// wire tick of 0.1. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoSpeedCalculationPosition) SetPositionZValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("PositionZ", v)
	}
	if v < 0 && !approximatelyEqual(v, 0) {
		return invalidPhysicalValue("PositionZ", v)
	}
	if v > 6553.2 && !approximatelyEqual(v, 6553.2) {
		return invalidPhysicalValue("PositionZ", v)
	}
	ticks, err := physicalRawTicks(v, 0.1, 0, 16, false)
	if err != nil {
		return invalidPhysicalValue("PositionZ", v)
	}
	raw := uint64(ticks)
	candidate := *m
	candidate.PositionZ = &raw
	if _, ok := candidate.PositionZValue(); !ok {
		return invalidPhysicalValue("PositionZ", v)
	}
	m.PositionZ = &raw
	return nil
}

// MarshalJSON includes raw fields and derived physical values in schema units.
// Unavailable measurements are null. Physical values are output-only.
func (m FurunoSpeedCalculationPosition) MarshalJSON() ([]byte, error) {
	type raw FurunoSpeedCalculationPosition
	return json.Marshal(struct {
		raw
		Physical map[string]*physicalJSONValue `json:"physical"`
	}{
		raw: raw(m),
		Physical: map[string]*physicalJSONValue{
			"positionY": physicalJSONMeasurement("m", m.PositionYValue),
			"positionZ": physicalJSONMeasurement("m", m.PositionZValue),
		},
	})
}

type FurunoSixDegreesOfFreedomMovement struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	A                *int64      `json:"a,omitempty" n2k:"4"`
	B                *int64      `json:"b,omitempty" n2k:"5"`
	C                *int64      `json:"c,omitempty" n2k:"6"`
	D                *int64      `json:"d,omitempty" n2k:"7"`
	E                *int64      `json:"e,omitempty" n2k:"8"`
	F                *int64      `json:"f,omitempty" n2k:"9"`
	G                *int64      `json:"g,omitempty" n2k:"10"`
	H                *int64      `json:"h,omitempty" n2k:"11"`
	I                *int64      `json:"i,omitempty" n2k:"12"`
}

func (m *FurunoSixDegreesOfFreedomMovement) PGNNumber() uint32               { return 130842 }
func (m *FurunoSixDegreesOfFreedomMovement) MessageInfo() MessageInfo        { return m.Info }
func (m *FurunoSixDegreesOfFreedomMovement) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *FurunoSixDegreesOfFreedomMovement) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *FurunoSixDegreesOfFreedomMovement) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *FurunoSixDegreesOfFreedomMovement) Clone() Message {
	if m == nil {
		return (*FurunoSixDegreesOfFreedomMovement)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.A = clonePointer(m.A)
	copy.B = clonePointer(m.B)
	copy.C = clonePointer(m.C)
	copy.D = clonePointer(m.D)
	copy.E = clonePointer(m.E)
	copy.F = clonePointer(m.F)
	copy.G = clonePointer(m.G)
	copy.H = clonePointer(m.H)
	copy.I = clonePointer(m.I)
	return &copy
}

type FurunoHeelAngleRollInformation struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Heel             *int64      `json:"heel,omitempty" n2k:"4"`
	Field4           *int64      `json:"field4,omitempty" n2k:"5"`
	Field6           *int64      `json:"field6,omitempty" n2k:"6"`
	Field8           *int64      `json:"field8,omitempty" n2k:"7"`
}

func (m *FurunoHeelAngleRollInformation) PGNNumber() uint32               { return 130843 }
func (m *FurunoHeelAngleRollInformation) MessageInfo() MessageInfo        { return m.Info }
func (m *FurunoHeelAngleRollInformation) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *FurunoHeelAngleRollInformation) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *FurunoHeelAngleRollInformation) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *FurunoHeelAngleRollInformation) Clone() Message {
	if m == nil {
		return (*FurunoHeelAngleRollInformation)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Heel = clonePointer(m.Heel)
	copy.Field4 = clonePointer(m.Field4)
	copy.Field6 = clonePointer(m.Field6)
	copy.Field8 = clonePointer(m.Field8)
	return &copy
}

// HeelValue returns Heel as a physical value in rad (value = raw * 0.0001).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoHeelAngleRollInformation) HeelValue() (float64, bool) {
	if m == nil || m.Heel == nil {
		return 0, false
	}
	if *m.Heel == 32767 {
		return 0, false
	}
	if *m.Heel == 32766 {
		return 0, false
	}
	if *m.Heel == 32765 {
		return 0, false
	}
	value := float64(*m.Heel) * 0.0001
	if value < -3.1415926 && !approximatelyEqual(value, -3.1415926) {
		return 0, false
	}
	if value > 3.1415926 && !approximatelyEqual(value, 3.1415926) {
		return 0, false
	}
	return value, true
}

// SetHeelValue sets Heel from a physical value in rad, rounded to the nearest
// wire tick of 0.0001. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoHeelAngleRollInformation) SetHeelValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("Heel", v)
	}
	if v < -3.1415926 && !approximatelyEqual(v, -3.1415926) {
		return invalidPhysicalValue("Heel", v)
	}
	if v > 3.1415926 && !approximatelyEqual(v, 3.1415926) {
		return invalidPhysicalValue("Heel", v)
	}
	ticks, err := physicalRawTicks(v, 0.0001, 0, 16, true)
	if err != nil {
		return invalidPhysicalValue("Heel", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.Heel = &raw
	if _, ok := candidate.HeelValue(); !ok {
		return invalidPhysicalValue("Heel", v)
	}
	m.Heel = &raw
	return nil
}

// Field4Value returns Field4 as a physical value in rad (value = raw * 0.0001).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoHeelAngleRollInformation) Field4Value() (float64, bool) {
	if m == nil || m.Field4 == nil {
		return 0, false
	}
	if *m.Field4 == 32767 {
		return 0, false
	}
	if *m.Field4 == 32766 {
		return 0, false
	}
	if *m.Field4 == 32765 {
		return 0, false
	}
	value := float64(*m.Field4) * 0.0001
	if value < -3.1415926 && !approximatelyEqual(value, -3.1415926) {
		return 0, false
	}
	if value > 3.1415926 && !approximatelyEqual(value, 3.1415926) {
		return 0, false
	}
	return value, true
}

// SetField4Value sets Field4 from a physical value in rad, rounded to the nearest
// wire tick of 0.0001. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoHeelAngleRollInformation) SetField4Value(v float64) error {
	if m == nil {
		return invalidPhysicalValue("Field4", v)
	}
	if v < -3.1415926 && !approximatelyEqual(v, -3.1415926) {
		return invalidPhysicalValue("Field4", v)
	}
	if v > 3.1415926 && !approximatelyEqual(v, 3.1415926) {
		return invalidPhysicalValue("Field4", v)
	}
	ticks, err := physicalRawTicks(v, 0.0001, 0, 16, true)
	if err != nil {
		return invalidPhysicalValue("Field4", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.Field4 = &raw
	if _, ok := candidate.Field4Value(); !ok {
		return invalidPhysicalValue("Field4", v)
	}
	m.Field4 = &raw
	return nil
}

// Field6Value returns Field6 as a physical value in rad (value = raw * 0.0001).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoHeelAngleRollInformation) Field6Value() (float64, bool) {
	if m == nil || m.Field6 == nil {
		return 0, false
	}
	if *m.Field6 == 32767 {
		return 0, false
	}
	if *m.Field6 == 32766 {
		return 0, false
	}
	if *m.Field6 == 32765 {
		return 0, false
	}
	value := float64(*m.Field6) * 0.0001
	if value < -3.1415926 && !approximatelyEqual(value, -3.1415926) {
		return 0, false
	}
	if value > 3.1415926 && !approximatelyEqual(value, 3.1415926) {
		return 0, false
	}
	return value, true
}

// SetField6Value sets Field6 from a physical value in rad, rounded to the nearest
// wire tick of 0.0001. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoHeelAngleRollInformation) SetField6Value(v float64) error {
	if m == nil {
		return invalidPhysicalValue("Field6", v)
	}
	if v < -3.1415926 && !approximatelyEqual(v, -3.1415926) {
		return invalidPhysicalValue("Field6", v)
	}
	if v > 3.1415926 && !approximatelyEqual(v, 3.1415926) {
		return invalidPhysicalValue("Field6", v)
	}
	ticks, err := physicalRawTicks(v, 0.0001, 0, 16, true)
	if err != nil {
		return invalidPhysicalValue("Field6", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.Field6 = &raw
	if _, ok := candidate.Field6Value(); !ok {
		return invalidPhysicalValue("Field6", v)
	}
	m.Field6 = &raw
	return nil
}

// Field8Value returns Field8 as a physical value in rad (value = raw * 0.0001).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoHeelAngleRollInformation) Field8Value() (float64, bool) {
	if m == nil || m.Field8 == nil {
		return 0, false
	}
	if *m.Field8 == 32767 {
		return 0, false
	}
	if *m.Field8 == 32766 {
		return 0, false
	}
	if *m.Field8 == 32765 {
		return 0, false
	}
	value := float64(*m.Field8) * 0.0001
	if value < -3.1415926 && !approximatelyEqual(value, -3.1415926) {
		return 0, false
	}
	if value > 3.1415926 && !approximatelyEqual(value, 3.1415926) {
		return 0, false
	}
	return value, true
}

// SetField8Value sets Field8 from a physical value in rad, rounded to the nearest
// wire tick of 0.0001. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoHeelAngleRollInformation) SetField8Value(v float64) error {
	if m == nil {
		return invalidPhysicalValue("Field8", v)
	}
	if v < -3.1415926 && !approximatelyEqual(v, -3.1415926) {
		return invalidPhysicalValue("Field8", v)
	}
	if v > 3.1415926 && !approximatelyEqual(v, 3.1415926) {
		return invalidPhysicalValue("Field8", v)
	}
	ticks, err := physicalRawTicks(v, 0.0001, 0, 16, true)
	if err != nil {
		return invalidPhysicalValue("Field8", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.Field8 = &raw
	if _, ok := candidate.Field8Value(); !ok {
		return invalidPhysicalValue("Field8", v)
	}
	m.Field8 = &raw
	return nil
}

// MarshalJSON includes raw fields and derived physical values in schema units.
// Unavailable measurements are null. Physical values are output-only.
func (m FurunoHeelAngleRollInformation) MarshalJSON() ([]byte, error) {
	type raw FurunoHeelAngleRollInformation
	return json.Marshal(struct {
		raw
		Physical map[string]*physicalJSONValue `json:"physical"`
	}{
		raw: raw(m),
		Physical: map[string]*physicalJSONValue{
			"heel":   physicalJSONMeasurement("rad", m.HeelValue),
			"field4": physicalJSONMeasurement("rad", m.Field4Value),
			"field6": physicalJSONMeasurement("rad", m.Field6Value),
			"field8": physicalJSONMeasurement("rad", m.Field8Value),
		},
	})
}

type FurunoMultiSatsInViewExtended struct {
	Info             MessageInfo                               `json:"info"`
	ManufacturerCode *uint64                                   `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64                                   `json:"industryCode,omitempty" n2k:"3"`
	ReportType       *uint64                                   `json:"reportType,omitempty" n2k:"4"`
	Antenna          *uint64                                   `json:"antenna,omitempty" n2k:"5"`
	PageType         *uint64                                   `json:"pageType,omitempty" n2k:"6"`
	Page             *uint64                                   `json:"page,omitempty" n2k:"7"`
	SatsInUse        *uint64                                   `json:"satsInUse,omitempty" n2k:"9"`
	SatsInView       *uint64                                   `json:"satsInView,omitempty" n2k:"10"`
	Repeating1       []FurunoMultiSatsInViewExtendedRepeating1 `json:"repeating1,omitempty" n2k:"rep1"`
}

type FurunoMultiSatsInViewExtendedRepeating1 struct {
	Prn            *uint64 `json:"prn,omitempty" n2k:"11"`
	Elevation      *int64  `json:"elevation,omitempty" n2k:"12"`
	Azimuth        *int64  `json:"azimuth,omitempty" n2k:"13"`
	Snr            *int64  `json:"snr,omitempty" n2k:"14"`
	RangeResidual  *int64  `json:"rangeResidual,omitempty" n2k:"15"`
	BaselineStatus *uint64 `json:"baselineStatus,omitempty" n2k:"16"`
}

func (m *FurunoMultiSatsInViewExtended) PGNNumber() uint32               { return 130845 }
func (m *FurunoMultiSatsInViewExtended) MessageInfo() MessageInfo        { return m.Info }
func (m *FurunoMultiSatsInViewExtended) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *FurunoMultiSatsInViewExtended) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *FurunoMultiSatsInViewExtended) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *FurunoMultiSatsInViewExtended) Clone() Message {
	if m == nil {
		return (*FurunoMultiSatsInViewExtended)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.ReportType = clonePointer(m.ReportType)
	copy.Antenna = clonePointer(m.Antenna)
	copy.PageType = clonePointer(m.PageType)
	copy.Page = clonePointer(m.Page)
	copy.SatsInUse = clonePointer(m.SatsInUse)
	copy.SatsInView = clonePointer(m.SatsInView)
	copy.Repeating1 = cloneSlice(m.Repeating1)
	for i := range copy.Repeating1 {
		copy.Repeating1[i].Prn = clonePointer(m.Repeating1[i].Prn)
		copy.Repeating1[i].Elevation = clonePointer(m.Repeating1[i].Elevation)
		copy.Repeating1[i].Azimuth = clonePointer(m.Repeating1[i].Azimuth)
		copy.Repeating1[i].Snr = clonePointer(m.Repeating1[i].Snr)
		copy.Repeating1[i].RangeResidual = clonePointer(m.Repeating1[i].RangeResidual)
		copy.Repeating1[i].BaselineStatus = clonePointer(m.Repeating1[i].BaselineStatus)
	}
	return &copy
}

// ElevationValue returns Elevation as a physical value in rad (value = raw * 0.0001).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoMultiSatsInViewExtendedRepeating1) ElevationValue() (float64, bool) {
	if m == nil || m.Elevation == nil {
		return 0, false
	}
	if *m.Elevation == 32767 {
		return 0, false
	}
	if *m.Elevation == 32766 {
		return 0, false
	}
	if *m.Elevation == 32765 {
		return 0, false
	}
	value := float64(*m.Elevation) * 0.0001
	if value < -3.1415926 && !approximatelyEqual(value, -3.1415926) {
		return 0, false
	}
	if value > 3.1415926 && !approximatelyEqual(value, 3.1415926) {
		return 0, false
	}
	return value, true
}

// SetElevationValue sets Elevation from a physical value in rad, rounded to the nearest
// wire tick of 0.0001. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoMultiSatsInViewExtendedRepeating1) SetElevationValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("Elevation", v)
	}
	if v < -3.1415926 && !approximatelyEqual(v, -3.1415926) {
		return invalidPhysicalValue("Elevation", v)
	}
	if v > 3.1415926 && !approximatelyEqual(v, 3.1415926) {
		return invalidPhysicalValue("Elevation", v)
	}
	ticks, err := physicalRawTicks(v, 0.0001, 0, 16, true)
	if err != nil {
		return invalidPhysicalValue("Elevation", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.Elevation = &raw
	if _, ok := candidate.ElevationValue(); !ok {
		return invalidPhysicalValue("Elevation", v)
	}
	m.Elevation = &raw
	return nil
}

// AzimuthValue returns Azimuth as a physical value in rad (value = raw * 0.0001).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoMultiSatsInViewExtendedRepeating1) AzimuthValue() (float64, bool) {
	if m == nil || m.Azimuth == nil {
		return 0, false
	}
	if *m.Azimuth == 32767 {
		return 0, false
	}
	if *m.Azimuth == 32766 {
		return 0, false
	}
	if *m.Azimuth == 32765 {
		return 0, false
	}
	value := float64(*m.Azimuth) * 0.0001
	if value < -3.1415926 && !approximatelyEqual(value, -3.1415926) {
		return 0, false
	}
	if value > 3.1415926 && !approximatelyEqual(value, 3.1415926) {
		return 0, false
	}
	return value, true
}

// SetAzimuthValue sets Azimuth from a physical value in rad, rounded to the nearest
// wire tick of 0.0001. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoMultiSatsInViewExtendedRepeating1) SetAzimuthValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("Azimuth", v)
	}
	if v < -3.1415926 && !approximatelyEqual(v, -3.1415926) {
		return invalidPhysicalValue("Azimuth", v)
	}
	if v > 3.1415926 && !approximatelyEqual(v, 3.1415926) {
		return invalidPhysicalValue("Azimuth", v)
	}
	ticks, err := physicalRawTicks(v, 0.0001, 0, 16, true)
	if err != nil {
		return invalidPhysicalValue("Azimuth", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.Azimuth = &raw
	if _, ok := candidate.AzimuthValue(); !ok {
		return invalidPhysicalValue("Azimuth", v)
	}
	m.Azimuth = &raw
	return nil
}

// SnrValue returns Snr as a physical value in dB (value = raw * 0.01).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoMultiSatsInViewExtendedRepeating1) SnrValue() (float64, bool) {
	if m == nil || m.Snr == nil {
		return 0, false
	}
	if *m.Snr == 32767 {
		return 0, false
	}
	if *m.Snr == 32766 {
		return 0, false
	}
	if *m.Snr == 32765 {
		return 0, false
	}
	value := float64(*m.Snr) * 0.01
	if value < -327.67 && !approximatelyEqual(value, -327.67) {
		return 0, false
	}
	if value > 327.64 && !approximatelyEqual(value, 327.64) {
		return 0, false
	}
	return value, true
}

// SetSnrValue sets Snr from a physical value in dB, rounded to the nearest
// wire tick of 0.01. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoMultiSatsInViewExtendedRepeating1) SetSnrValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("Snr", v)
	}
	if v < -327.67 && !approximatelyEqual(v, -327.67) {
		return invalidPhysicalValue("Snr", v)
	}
	if v > 327.64 && !approximatelyEqual(v, 327.64) {
		return invalidPhysicalValue("Snr", v)
	}
	ticks, err := physicalRawTicks(v, 0.01, 0, 16, true)
	if err != nil {
		return invalidPhysicalValue("Snr", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.Snr = &raw
	if _, ok := candidate.SnrValue(); !ok {
		return invalidPhysicalValue("Snr", v)
	}
	m.Snr = &raw
	return nil
}

// RangeResidualValue returns RangeResidual as a physical value in m (value = raw * 1e-05).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *FurunoMultiSatsInViewExtendedRepeating1) RangeResidualValue() (float64, bool) {
	if m == nil || m.RangeResidual == nil {
		return 0, false
	}
	if *m.RangeResidual == 2147483647 {
		return 0, false
	}
	if *m.RangeResidual == 2147483646 {
		return 0, false
	}
	if *m.RangeResidual == 2147483645 {
		return 0, false
	}
	value := float64(*m.RangeResidual) * 1e-05
	if value < -21474.83647 && !approximatelyEqual(value, -21474.83647) {
		return 0, false
	}
	if value > 21474.83644 && !approximatelyEqual(value, 21474.83644) {
		return 0, false
	}
	return value, true
}

// SetRangeResidualValue sets RangeResidual from a physical value in m, rounded to the nearest
// wire tick of 1e-05. Invalid, non-finite, sentinel, or out-of-range values
// return ErrInvalidPhysicalValue and leave the field unchanged. A nil receiver is invalid.
func (m *FurunoMultiSatsInViewExtendedRepeating1) SetRangeResidualValue(v float64) error {
	if m == nil {
		return invalidPhysicalValue("RangeResidual", v)
	}
	if v < -21474.83647 && !approximatelyEqual(v, -21474.83647) {
		return invalidPhysicalValue("RangeResidual", v)
	}
	if v > 21474.83644 && !approximatelyEqual(v, 21474.83644) {
		return invalidPhysicalValue("RangeResidual", v)
	}
	ticks, err := physicalRawTicks(v, 1e-05, 0, 32, true)
	if err != nil {
		return invalidPhysicalValue("RangeResidual", v)
	}
	raw := int64(ticks)
	candidate := *m
	candidate.RangeResidual = &raw
	if _, ok := candidate.RangeResidualValue(); !ok {
		return invalidPhysicalValue("RangeResidual", v)
	}
	m.RangeResidual = &raw
	return nil
}

// MarshalJSON includes raw fields and derived physical values in schema units.
// Unavailable measurements are null. Physical values are output-only.
func (m FurunoMultiSatsInViewExtendedRepeating1) MarshalJSON() ([]byte, error) {
	type raw FurunoMultiSatsInViewExtendedRepeating1
	return json.Marshal(struct {
		raw
		Physical map[string]*physicalJSONValue `json:"physical"`
	}{
		raw: raw(m),
		Physical: map[string]*physicalJSONValue{
			"elevation":     physicalJSONMeasurement("rad", m.ElevationValue),
			"azimuth":       physicalJSONMeasurement("rad", m.AzimuthValue),
			"snr":           physicalJSONMeasurement("dB", m.SnrValue),
			"rangeResidual": physicalJSONMeasurement("m", m.RangeResidualValue),
		},
	})
}

type FurunoMotionSensorStatusExtended struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Status           *uint64     `json:"status,omitempty" n2k:"4"`
	Data             []uint8     `json:"data,omitempty" n2k:"5"`
}

func (m *FurunoMotionSensorStatusExtended) PGNNumber() uint32               { return 130846 }
func (m *FurunoMotionSensorStatusExtended) MessageInfo() MessageInfo        { return m.Info }
func (m *FurunoMotionSensorStatusExtended) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *FurunoMotionSensorStatusExtended) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *FurunoMotionSensorStatusExtended) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *FurunoMotionSensorStatusExtended) Clone() Message {
	if m == nil {
		return (*FurunoMotionSensorStatusExtended)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Status = clonePointer(m.Status)
	copy.Data = cloneSlice(m.Data)
	return &copy
}
