// Code generated by PGN generator; DO NOT EDIT.
// Source schema 2.4.0 version 7.0.0.

package pgn

type PgnHondaEngineData struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Data             []uint8     `json:"data,omitempty" n2k:"4"`
}

func (m *PgnHondaEngineData) PGNNumber() uint32               { return 65280 }
func (m *PgnHondaEngineData) MessageInfo() MessageInfo        { return m.Info }
func (m *PgnHondaEngineData) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *PgnHondaEngineData) DecodePayload(payload []uint8) error {
	return decodeStructPayload(lookupPgnInfo(65280, "Honda: Engine Data"), m, payload)
}
func (m *PgnHondaEngineData) EncodePayload() ([]uint8, error) {
	return encodeStructPayload(lookupPgnInfo(65280, "Honda: Engine Data"), m)
}

type PgnHondaEngineAlerts struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Data             []uint8     `json:"data,omitempty" n2k:"4"`
}

func (m *PgnHondaEngineAlerts) PGNNumber() uint32               { return 65284 }
func (m *PgnHondaEngineAlerts) MessageInfo() MessageInfo        { return m.Info }
func (m *PgnHondaEngineAlerts) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *PgnHondaEngineAlerts) DecodePayload(payload []uint8) error {
	return decodeStructPayload(lookupPgnInfo(65284, "Honda: Engine Alerts"), m, payload)
}
func (m *PgnHondaEngineAlerts) EncodePayload() ([]uint8, error) {
	return encodeStructPayload(lookupPgnInfo(65284, "Honda: Engine Alerts"), m)
}

type PgnHondaEngineStatus struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
}

func (m *PgnHondaEngineStatus) PGNNumber() uint32               { return 130816 }
func (m *PgnHondaEngineStatus) MessageInfo() MessageInfo        { return m.Info }
func (m *PgnHondaEngineStatus) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *PgnHondaEngineStatus) DecodePayload(payload []uint8) error {
	return decodeStructPayload(lookupPgnInfo(130816, "Honda: Engine Status"), m, payload)
}
func (m *PgnHondaEngineStatus) EncodePayload() ([]uint8, error) {
	return encodeStructPayload(lookupPgnInfo(130816, "Honda: Engine Status"), m)
}
