// Code generated by PGN generator; DO NOT EDIT.
// Source schema 2.4.0 version 7.0.0.

package pgn

type PgnLowranceTemperature struct {
	Info              MessageInfo `json:"info"`
	ManufacturerCode  *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode      *uint64     `json:"industryCode,omitempty" n2k:"3"`
	TemperatureSource *uint64     `json:"temperatureSource,omitempty" n2k:"4"`
	ActualTemperature *uint64     `json:"actualTemperature,omitempty" n2k:"5"`
}

func (m *PgnLowranceTemperature) PGNNumber() uint32               { return 65285 }
func (m *PgnLowranceTemperature) MessageInfo() MessageInfo        { return m.Info }
func (m *PgnLowranceTemperature) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *PgnLowranceTemperature) DecodePayload(payload []uint8) error {
	return decodeStructPayload(lookupPgnInfo(65285, "Lowrance: Temperature"), m, payload)
}
func (m *PgnLowranceTemperature) EncodePayload() ([]uint8, error) {
	return encodeStructPayload(lookupPgnInfo(65285, "Lowrance: Temperature"), m)
}

type PgnLowranceProductInformation struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	ProductCode      *uint64     `json:"productCode,omitempty" n2k:"4"`
	Model            string      `json:"model,omitempty" n2k:"5"`
	A                *uint64     `json:"a,omitempty" n2k:"6"`
	B                *uint64     `json:"b,omitempty" n2k:"7"`
	C                *uint64     `json:"c,omitempty" n2k:"8"`
	FirmwareVersion  string      `json:"firmwareVersion,omitempty" n2k:"9"`
	FirmwareDate     string      `json:"firmwareDate,omitempty" n2k:"10"`
	FirmwareTime     string      `json:"firmwareTime,omitempty" n2k:"11"`
}

func (m *PgnLowranceProductInformation) PGNNumber() uint32               { return 130817 }
func (m *PgnLowranceProductInformation) MessageInfo() MessageInfo        { return m.Info }
func (m *PgnLowranceProductInformation) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *PgnLowranceProductInformation) DecodePayload(payload []uint8) error {
	return decodeStructPayload(lookupPgnInfo(130817, "Lowrance: Product Information"), m, payload)
}
func (m *PgnLowranceProductInformation) EncodePayload() ([]uint8, error) {
	return encodeStructPayload(lookupPgnInfo(130817, "Lowrance: Product Information"), m)
}

type PgnLowranceUnknown struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	A                *uint64     `json:"a,omitempty" n2k:"4"`
	B                *uint64     `json:"b,omitempty" n2k:"5"`
	C                *uint64     `json:"c,omitempty" n2k:"6"`
	D                *uint64     `json:"d,omitempty" n2k:"7"`
	E                *uint64     `json:"e,omitempty" n2k:"8"`
	F                *uint64     `json:"f,omitempty" n2k:"9"`
}

func (m *PgnLowranceUnknown) PGNNumber() uint32               { return 130827 }
func (m *PgnLowranceUnknown) MessageInfo() MessageInfo        { return m.Info }
func (m *PgnLowranceUnknown) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *PgnLowranceUnknown) DecodePayload(payload []uint8) error {
	return decodeStructPayload(lookupPgnInfo(130827, "Lowrance: unknown"), m, payload)
}
func (m *PgnLowranceUnknown) EncodePayload() ([]uint8, error) {
	return encodeStructPayload(lookupPgnInfo(130827, "Lowrance: unknown"), m)
}
