// Code generated by PGN generator; DO NOT EDIT.
// Source schema 2.5.0 version 7.1.0.

package pgn

import "math"

type MaretronKeelPosition struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Data             []uint8     `json:"data,omitempty" n2k:"4"`
}

func (m *MaretronKeelPosition) PGNNumber() uint32                   { return 65280 }
func (m *MaretronKeelPosition) MessageInfo() MessageInfo            { return m.Info }
func (m *MaretronKeelPosition) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *MaretronKeelPosition) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *MaretronKeelPosition) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronKeelPosition) Clone() Message {
	if m == nil {
		return (*MaretronKeelPosition)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Data = cloneSlice(m.Data)
	return &copy
}

type MaretronNumberOfChannels struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Pgn              *uint64     `json:"pgn,omitempty" n2k:"4"`
	NumberOfChannels *uint64     `json:"numberOfChannels,omitempty" n2k:"5"`
}

func (m *MaretronNumberOfChannels) PGNNumber() uint32               { return 65282 }
func (m *MaretronNumberOfChannels) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronNumberOfChannels) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronNumberOfChannels) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronNumberOfChannels) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronNumberOfChannels) Clone() Message {
	if m == nil {
		return (*MaretronNumberOfChannels)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Pgn = clonePointer(m.Pgn)
	copy.NumberOfChannels = clonePointer(m.NumberOfChannels)
	return &copy
}

type MaretronProprietaryDcBreakerCurrent struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	BankInstance     *uint64     `json:"bankInstance,omitempty" n2k:"4"`
	IndicatorNumber  *uint64     `json:"indicatorNumber,omitempty" n2k:"5"`
	BreakerCurrent   *int64      `json:"breakerCurrent,omitempty" n2k:"6"`
}

func (m *MaretronProprietaryDcBreakerCurrent) PGNNumber() uint32               { return 65284 }
func (m *MaretronProprietaryDcBreakerCurrent) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronProprietaryDcBreakerCurrent) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronProprietaryDcBreakerCurrent) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronProprietaryDcBreakerCurrent) EncodePayload() ([]uint8, error) {
	return encodeFields(m)
}

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronProprietaryDcBreakerCurrent) Clone() Message {
	if m == nil {
		return (*MaretronProprietaryDcBreakerCurrent)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.BankInstance = clonePointer(m.BankInstance)
	copy.IndicatorNumber = clonePointer(m.IndicatorNumber)
	copy.BreakerCurrent = clonePointer(m.BreakerCurrent)
	return &copy
}

// BreakerCurrentValue returns BreakerCurrent as a physical value in A (value = raw * 0.1).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *MaretronProprietaryDcBreakerCurrent) BreakerCurrentValue() (float64, bool) {
	if m == nil || m.BreakerCurrent == nil {
		return 0, false
	}
	if *m.BreakerCurrent == 32767 {
		return 0, false
	}
	if *m.BreakerCurrent == 32766 {
		return 0, false
	}
	if *m.BreakerCurrent == 32765 {
		return 0, false
	}
	value := float64(*m.BreakerCurrent) * 0.1
	if value < -3276.7 && !approximatelyEqual(value, -3276.7) {
		return 0, false
	}
	if value > 3276.4 && !approximatelyEqual(value, 3276.4) {
		return 0, false
	}
	return value, true
}

// SetBreakerCurrentValue sets BreakerCurrent from a physical value in A, rounded to the nearest
// wire tick of 0.1.
func (m *MaretronProprietaryDcBreakerCurrent) SetBreakerCurrentValue(v float64) {
	raw := int64(math.Round(v / 0.1))
	m.BreakerCurrent = &raw
}

type MaretronUniversalConfigurationSf struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Data             []uint8     `json:"data,omitempty" n2k:"4"`
}

func (m *MaretronUniversalConfigurationSf) PGNNumber() uint32               { return 65285 }
func (m *MaretronUniversalConfigurationSf) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronUniversalConfigurationSf) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronUniversalConfigurationSf) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronUniversalConfigurationSf) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronUniversalConfigurationSf) Clone() Message {
	if m == nil {
		return (*MaretronUniversalConfigurationSf)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Data = cloneSlice(m.Data)
	return &copy
}

type MaretronFluidFlowRate struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Sid              *uint64     `json:"sid,omitempty" n2k:"4"`
	FlowRateInstance *uint64     `json:"flowRateInstance,omitempty" n2k:"5"`
	FluidType        *uint64     `json:"fluidType,omitempty" n2k:"6"`
	FluidFlowRate    *int64      `json:"fluidFlowRate,omitempty" n2k:"8"`
}

func (m *MaretronFluidFlowRate) PGNNumber() uint32                   { return 65286 }
func (m *MaretronFluidFlowRate) MessageInfo() MessageInfo            { return m.Info }
func (m *MaretronFluidFlowRate) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *MaretronFluidFlowRate) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *MaretronFluidFlowRate) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronFluidFlowRate) Clone() Message {
	if m == nil {
		return (*MaretronFluidFlowRate)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Sid = clonePointer(m.Sid)
	copy.FlowRateInstance = clonePointer(m.FlowRateInstance)
	copy.FluidType = clonePointer(m.FluidType)
	copy.FluidFlowRate = clonePointer(m.FluidFlowRate)
	return &copy
}

// FluidFlowRateValue returns FluidFlowRate as a physical value (value = raw * 0.0001).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *MaretronFluidFlowRate) FluidFlowRateValue() (float64, bool) {
	if m == nil || m.FluidFlowRate == nil {
		return 0, false
	}
	if *m.FluidFlowRate == 8388607 {
		return 0, false
	}
	if *m.FluidFlowRate == 8388606 {
		return 0, false
	}
	if *m.FluidFlowRate == 8388605 {
		return 0, false
	}
	value := float64(*m.FluidFlowRate) * 0.0001
	if value < -838.8607 && !approximatelyEqual(value, -838.8607) {
		return 0, false
	}
	if value > 838.8604 && !approximatelyEqual(value, 838.8604) {
		return 0, false
	}
	return value, true
}

// SetFluidFlowRateValue sets FluidFlowRate from a physical value, rounded to the nearest
// wire tick of 0.0001.
func (m *MaretronFluidFlowRate) SetFluidFlowRateValue(v float64) {
	raw := int64(math.Round(v / 0.0001))
	m.FluidFlowRate = &raw
}

type MaretronTripVolume struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Sid              *uint64     `json:"sid,omitempty" n2k:"4"`
	VolumeInstance   *uint64     `json:"volumeInstance,omitempty" n2k:"5"`
	FluidType        *uint64     `json:"fluidType,omitempty" n2k:"6"`
	TripVolume       *uint64     `json:"tripVolume,omitempty" n2k:"8"`
}

func (m *MaretronTripVolume) PGNNumber() uint32                   { return 65287 }
func (m *MaretronTripVolume) MessageInfo() MessageInfo            { return m.Info }
func (m *MaretronTripVolume) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *MaretronTripVolume) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *MaretronTripVolume) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronTripVolume) Clone() Message {
	if m == nil {
		return (*MaretronTripVolume)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Sid = clonePointer(m.Sid)
	copy.VolumeInstance = clonePointer(m.VolumeInstance)
	copy.FluidType = clonePointer(m.FluidType)
	copy.TripVolume = clonePointer(m.TripVolume)
	return &copy
}

// TripVolumeValue returns TripVolume as a physical value (value = raw * 0.001).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *MaretronTripVolume) TripVolumeValue() (float64, bool) {
	if m == nil || m.TripVolume == nil {
		return 0, false
	}
	if *m.TripVolume == 16777215 {
		return 0, false
	}
	if *m.TripVolume == 16777214 {
		return 0, false
	}
	if *m.TripVolume == 16777213 {
		return 0, false
	}
	value := float64(*m.TripVolume) * 0.001
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 16777.212 && !approximatelyEqual(value, 16777.212) {
		return 0, false
	}
	return value, true
}

// SetTripVolumeValue sets TripVolume from a physical value, rounded to the nearest
// wire tick of 0.001.
func (m *MaretronTripVolume) SetTripVolumeValue(v float64) {
	raw := uint64(math.Round(v / 0.001))
	m.TripVolume = &raw
}

type Maretron420Ma struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Sid              *uint64     `json:"sid,omitempty" n2k:"4"`
	DataInstance     *uint64     `json:"dataInstance,omitempty" n2k:"5"`
	Pgn420MaData     *uint64     `json:"420MaData,omitempty" n2k:"6"`
}

func (m *Maretron420Ma) PGNNumber() uint32                   { return 65288 }
func (m *Maretron420Ma) MessageInfo() MessageInfo            { return m.Info }
func (m *Maretron420Ma) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *Maretron420Ma) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *Maretron420Ma) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *Maretron420Ma) Clone() Message {
	if m == nil {
		return (*Maretron420Ma)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Sid = clonePointer(m.Sid)
	copy.DataInstance = clonePointer(m.DataInstance)
	copy.Pgn420MaData = clonePointer(m.Pgn420MaData)
	return &copy
}

type Maretron010V struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Sid              *uint64     `json:"sid,omitempty" n2k:"4"`
	DataInstance     *uint64     `json:"dataInstance,omitempty" n2k:"5"`
	Pgn010VData      *uint64     `json:"010VData,omitempty" n2k:"6"`
}

func (m *Maretron010V) PGNNumber() uint32                   { return 65289 }
func (m *Maretron010V) MessageInfo() MessageInfo            { return m.Info }
func (m *Maretron010V) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *Maretron010V) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *Maretron010V) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *Maretron010V) Clone() Message {
	if m == nil {
		return (*Maretron010V)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Sid = clonePointer(m.Sid)
	copy.DataInstance = clonePointer(m.DataInstance)
	copy.Pgn010VData = clonePointer(m.Pgn010VData)
	return &copy
}

// Pgn010VDataValue returns Pgn010VData as a physical value (value = raw * 0.000244141).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *Maretron010V) Pgn010VDataValue() (float64, bool) {
	if m == nil || m.Pgn010VData == nil {
		return 0, false
	}
	if *m.Pgn010VData == 65535 {
		return 0, false
	}
	if *m.Pgn010VData == 65534 {
		return 0, false
	}
	if *m.Pgn010VData == 65533 {
		return 0, false
	}
	value := float64(*m.Pgn010VData) * 0.000244141
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 15.9990234375 && !approximatelyEqual(value, 15.9990234375) {
		return 0, false
	}
	return value, true
}

// SetPgn010VDataValue sets Pgn010VData from a physical value, rounded to the nearest
// wire tick of 0.000244141.
func (m *Maretron010V) SetPgn010VDataValue(v float64) {
	raw := uint64(math.Round(v / 0.000244141))
	m.Pgn010VData = &raw
}

type MaretronRotationalRate struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Sid              *uint64     `json:"sid,omitempty" n2k:"4"`
	DataInstance     *uint64     `json:"dataInstance,omitempty" n2k:"5"`
	RotationalRate   *int64      `json:"rotationalRate,omitempty" n2k:"6"`
}

func (m *MaretronRotationalRate) PGNNumber() uint32               { return 65290 }
func (m *MaretronRotationalRate) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronRotationalRate) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronRotationalRate) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronRotationalRate) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronRotationalRate) Clone() Message {
	if m == nil {
		return (*MaretronRotationalRate)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Sid = clonePointer(m.Sid)
	copy.DataInstance = clonePointer(m.DataInstance)
	copy.RotationalRate = clonePointer(m.RotationalRate)
	return &copy
}

// RotationalRateValue returns RotationalRate as a physical value (value = raw * 0.25).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *MaretronRotationalRate) RotationalRateValue() (float64, bool) {
	if m == nil || m.RotationalRate == nil {
		return 0, false
	}
	if *m.RotationalRate == 32767 {
		return 0, false
	}
	if *m.RotationalRate == 32766 {
		return 0, false
	}
	if *m.RotationalRate == 32765 {
		return 0, false
	}
	value := float64(*m.RotationalRate) * 0.25
	if value < -8191.75 && !approximatelyEqual(value, -8191.75) {
		return 0, false
	}
	if value > 8191 && !approximatelyEqual(value, 8191) {
		return 0, false
	}
	return value, true
}

// SetRotationalRateValue sets RotationalRate from a physical value, rounded to the nearest
// wire tick of 0.25.
func (m *MaretronRotationalRate) SetRotationalRateValue(v float64) {
	raw := int64(math.Round(v / 0.25))
	m.RotationalRate = &raw
}

type MaretronResistance struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Sid              *uint64     `json:"sid,omitempty" n2k:"4"`
	DataInstance     *uint64     `json:"dataInstance,omitempty" n2k:"5"`
	Resistance       *uint64     `json:"resistance,omitempty" n2k:"6"`
}

func (m *MaretronResistance) PGNNumber() uint32                   { return 65291 }
func (m *MaretronResistance) MessageInfo() MessageInfo            { return m.Info }
func (m *MaretronResistance) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *MaretronResistance) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *MaretronResistance) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronResistance) Clone() Message {
	if m == nil {
		return (*MaretronResistance)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Sid = clonePointer(m.Sid)
	copy.DataInstance = clonePointer(m.DataInstance)
	copy.Resistance = clonePointer(m.Resistance)
	return &copy
}

// ResistanceValue returns Resistance as a physical value (value = raw * 0.01).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *MaretronResistance) ResistanceValue() (float64, bool) {
	if m == nil || m.Resistance == nil {
		return 0, false
	}
	if *m.Resistance == 65535 {
		return 0, false
	}
	if *m.Resistance == 65534 {
		return 0, false
	}
	if *m.Resistance == 65533 {
		return 0, false
	}
	value := float64(*m.Resistance) * 0.01
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 655.32 && !approximatelyEqual(value, 655.32) {
		return 0, false
	}
	return value, true
}

// SetResistanceValue sets Resistance from a physical value, rounded to the nearest
// wire tick of 0.01.
func (m *MaretronResistance) SetResistanceValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.Resistance = &raw
}

type MaretronAutomationFunctionMaster struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Data             []uint8     `json:"data,omitempty" n2k:"4"`
}

func (m *MaretronAutomationFunctionMaster) PGNNumber() uint32               { return 65292 }
func (m *MaretronAutomationFunctionMaster) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronAutomationFunctionMaster) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronAutomationFunctionMaster) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronAutomationFunctionMaster) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronAutomationFunctionMaster) Clone() Message {
	if m == nil {
		return (*MaretronAutomationFunctionMaster)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Data = cloneSlice(m.Data)
	return &copy
}

type MaretronDeviationCalibrationResponse struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	ProductCode      *uint64     `json:"productCode,omitempty" n2k:"4"`
	SoftwareCode     *uint64     `json:"softwareCode,omitempty" n2k:"5"`
	Command          *uint64     `json:"command,omitempty" n2k:"6"`
	Status           *uint64     `json:"status,omitempty" n2k:"7"`
}

func (m *MaretronDeviationCalibrationResponse) PGNNumber() uint32               { return 126720 }
func (m *MaretronDeviationCalibrationResponse) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronDeviationCalibrationResponse) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronDeviationCalibrationResponse) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronDeviationCalibrationResponse) EncodePayload() ([]uint8, error) {
	return encodeFields(m)
}

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronDeviationCalibrationResponse) Clone() Message {
	if m == nil {
		return (*MaretronDeviationCalibrationResponse)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.ProductCode = clonePointer(m.ProductCode)
	copy.SoftwareCode = clonePointer(m.SoftwareCode)
	copy.Command = clonePointer(m.Command)
	copy.Status = clonePointer(m.Status)
	return &copy
}

type MaretronProprietaryConfiguration struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	ProductCode      *uint64     `json:"productCode,omitempty" n2k:"4"`
	SoftwareCode     *uint64     `json:"softwareCode,omitempty" n2k:"5"`
	Opcode           *uint64     `json:"opcode,omitempty" n2k:"6"`
	Payload          []uint8     `json:"payload,omitempty" n2k:"7"`
}

func (m *MaretronProprietaryConfiguration) PGNNumber() uint32               { return 126720 }
func (m *MaretronProprietaryConfiguration) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronProprietaryConfiguration) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronProprietaryConfiguration) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronProprietaryConfiguration) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronProprietaryConfiguration) Clone() Message {
	if m == nil {
		return (*MaretronProprietaryConfiguration)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.ProductCode = clonePointer(m.ProductCode)
	copy.SoftwareCode = clonePointer(m.SoftwareCode)
	copy.Opcode = clonePointer(m.Opcode)
	copy.Payload = cloneSlice(m.Payload)
	return &copy
}

type MaretronAnnunciatorCapabilities struct {
	Info                MessageInfo                                 `json:"info"`
	ManufacturerCode    *uint64                                     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode        *uint64                                     `json:"industryCode,omitempty" n2k:"3"`
	AnnunciatorInstance *uint64                                     `json:"annunciatorInstance,omitempty" n2k:"4"`
	NumberOfTones       *uint64                                     `json:"numberOfTones,omitempty" n2k:"5"`
	Repeating1          []MaretronAnnunciatorCapabilitiesRepeating1 `json:"repeating1,omitempty" n2k:"rep1"`
}

type MaretronAnnunciatorCapabilitiesRepeating1 struct {
	Tone *uint64 `json:"tone,omitempty" n2k:"6"`
}

func (m *MaretronAnnunciatorCapabilities) PGNNumber() uint32               { return 130817 }
func (m *MaretronAnnunciatorCapabilities) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronAnnunciatorCapabilities) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronAnnunciatorCapabilities) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronAnnunciatorCapabilities) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronAnnunciatorCapabilities) Clone() Message {
	if m == nil {
		return (*MaretronAnnunciatorCapabilities)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.AnnunciatorInstance = clonePointer(m.AnnunciatorInstance)
	copy.NumberOfTones = clonePointer(m.NumberOfTones)
	copy.Repeating1 = cloneSlice(m.Repeating1)
	for i := range copy.Repeating1 {
		copy.Repeating1[i].Tone = clonePointer(m.Repeating1[i].Tone)
	}
	return &copy
}

type MaretronLabel struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Instance         *uint64     `json:"instance,omitempty" n2k:"4"`
	DataSource       *uint64     `json:"dataSource,omitempty" n2k:"5"`
	DataIndicator    *uint64     `json:"dataIndicator,omitempty" n2k:"6"`
	Label            string      `json:"label,omitempty" n2k:"7"`
	HardwareChannel  *uint64     `json:"hardwareChannel,omitempty" n2k:"8"`
}

func (m *MaretronLabel) PGNNumber() uint32                   { return 130818 }
func (m *MaretronLabel) MessageInfo() MessageInfo            { return m.Info }
func (m *MaretronLabel) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *MaretronLabel) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *MaretronLabel) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronLabel) Clone() Message {
	if m == nil {
		return (*MaretronLabel)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Instance = clonePointer(m.Instance)
	copy.DataSource = clonePointer(m.DataSource)
	copy.DataIndicator = clonePointer(m.DataIndicator)
	copy.HardwareChannel = clonePointer(m.HardwareChannel)
	return &copy
}

type MaretronAlertTransmission struct {
	Info                    MessageInfo `json:"info"`
	ManufacturerCode        *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode            *uint64     `json:"industryCode,omitempty" n2k:"3"`
	AlertType               *uint64     `json:"alertType,omitempty" n2k:"4"`
	AlertCategory           *uint64     `json:"alertCategory,omitempty" n2k:"5"`
	AlertSystem             *uint64     `json:"alertSystem,omitempty" n2k:"6"`
	AlertSubSystem          *uint64     `json:"alertSubSystem,omitempty" n2k:"7"`
	AlertId                 *uint64     `json:"alertId,omitempty" n2k:"8"`
	DataSourceNetworkIdName *uint64     `json:"dataSourceNetworkIdName,omitempty" n2k:"9"`
	DataSourceInstance      *uint64     `json:"dataSourceInstance,omitempty" n2k:"10"`
	DataSourceIndexSource   *uint64     `json:"dataSourceIndexSource,omitempty" n2k:"11"`
	AlertOccurrenceNumber   *uint64     `json:"alertOccurrenceNumber,omitempty" n2k:"12"`
	MaretronExtension       []uint8     `json:"maretronExtension,omitempty" n2k:"13"`
}

func (m *MaretronAlertTransmission) PGNNumber() uint32               { return 130819 }
func (m *MaretronAlertTransmission) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronAlertTransmission) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronAlertTransmission) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronAlertTransmission) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronAlertTransmission) Clone() Message {
	if m == nil {
		return (*MaretronAlertTransmission)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.AlertType = clonePointer(m.AlertType)
	copy.AlertCategory = clonePointer(m.AlertCategory)
	copy.AlertSystem = clonePointer(m.AlertSystem)
	copy.AlertSubSystem = clonePointer(m.AlertSubSystem)
	copy.AlertId = clonePointer(m.AlertId)
	copy.DataSourceNetworkIdName = clonePointer(m.DataSourceNetworkIdName)
	copy.DataSourceInstance = clonePointer(m.DataSourceInstance)
	copy.DataSourceIndexSource = clonePointer(m.DataSourceIndexSource)
	copy.AlertOccurrenceNumber = clonePointer(m.AlertOccurrenceNumber)
	copy.MaretronExtension = cloneSlice(m.MaretronExtension)
	return &copy
}

type MaretronAlertResponse struct {
	Info                           MessageInfo `json:"info"`
	ManufacturerCode               *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode                   *uint64     `json:"industryCode,omitempty" n2k:"3"`
	AlertType                      *uint64     `json:"alertType,omitempty" n2k:"4"`
	AlertCategory                  *uint64     `json:"alertCategory,omitempty" n2k:"5"`
	AlertSystem                    *uint64     `json:"alertSystem,omitempty" n2k:"6"`
	AlertSubSystem                 *uint64     `json:"alertSubSystem,omitempty" n2k:"7"`
	AlertId                        *uint64     `json:"alertId,omitempty" n2k:"8"`
	DataSourceNetworkIdName        *uint64     `json:"dataSourceNetworkIdName,omitempty" n2k:"9"`
	DataSourceInstance             *uint64     `json:"dataSourceInstance,omitempty" n2k:"10"`
	DataSourceIndexSource          *uint64     `json:"dataSourceIndexSource,omitempty" n2k:"11"`
	AlertOccurrenceNumber          *uint64     `json:"alertOccurrenceNumber,omitempty" n2k:"12"`
	AcknowledgeSourceNetworkIdName *uint64     `json:"acknowledgeSourceNetworkIdName,omitempty" n2k:"13"`
	ResponseCommand                *uint64     `json:"responseCommand,omitempty" n2k:"14"`
}

func (m *MaretronAlertResponse) PGNNumber() uint32                   { return 130820 }
func (m *MaretronAlertResponse) MessageInfo() MessageInfo            { return m.Info }
func (m *MaretronAlertResponse) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *MaretronAlertResponse) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *MaretronAlertResponse) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronAlertResponse) Clone() Message {
	if m == nil {
		return (*MaretronAlertResponse)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.AlertType = clonePointer(m.AlertType)
	copy.AlertCategory = clonePointer(m.AlertCategory)
	copy.AlertSystem = clonePointer(m.AlertSystem)
	copy.AlertSubSystem = clonePointer(m.AlertSubSystem)
	copy.AlertId = clonePointer(m.AlertId)
	copy.DataSourceNetworkIdName = clonePointer(m.DataSourceNetworkIdName)
	copy.DataSourceInstance = clonePointer(m.DataSourceInstance)
	copy.DataSourceIndexSource = clonePointer(m.DataSourceIndexSource)
	copy.AlertOccurrenceNumber = clonePointer(m.AlertOccurrenceNumber)
	copy.AcknowledgeSourceNetworkIdName = clonePointer(m.AcknowledgeSourceNetworkIdName)
	copy.ResponseCommand = clonePointer(m.ResponseCommand)
	return &copy
}

type MaretronAlertText struct {
	Info                         MessageInfo `json:"info"`
	ManufacturerCode             *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode                 *uint64     `json:"industryCode,omitempty" n2k:"3"`
	AlertType                    *uint64     `json:"alertType,omitempty" n2k:"4"`
	AlertCategory                *uint64     `json:"alertCategory,omitempty" n2k:"5"`
	AlertSystem                  *uint64     `json:"alertSystem,omitempty" n2k:"6"`
	AlertSubSystem               *uint64     `json:"alertSubSystem,omitempty" n2k:"7"`
	AlertId                      *uint64     `json:"alertId,omitempty" n2k:"8"`
	DataSourceNetworkIdName      *uint64     `json:"dataSourceNetworkIdName,omitempty" n2k:"9"`
	DataSourceInstance           *uint64     `json:"dataSourceInstance,omitempty" n2k:"10"`
	DataSourceIndexSource        *uint64     `json:"dataSourceIndexSource,omitempty" n2k:"11"`
	AlertOccurrenceNumber        *uint64     `json:"alertOccurrenceNumber,omitempty" n2k:"12"`
	LanguageId                   *uint64     `json:"languageId,omitempty" n2k:"13"`
	AlertTextDescription         string      `json:"alertTextDescription,omitempty" n2k:"14"`
	AlertLocationTextDescription string      `json:"alertLocationTextDescription,omitempty" n2k:"15"`
}

func (m *MaretronAlertText) PGNNumber() uint32                   { return 130821 }
func (m *MaretronAlertText) MessageInfo() MessageInfo            { return m.Info }
func (m *MaretronAlertText) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *MaretronAlertText) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *MaretronAlertText) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronAlertText) Clone() Message {
	if m == nil {
		return (*MaretronAlertText)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.AlertType = clonePointer(m.AlertType)
	copy.AlertCategory = clonePointer(m.AlertCategory)
	copy.AlertSystem = clonePointer(m.AlertSystem)
	copy.AlertSubSystem = clonePointer(m.AlertSubSystem)
	copy.AlertId = clonePointer(m.AlertId)
	copy.DataSourceNetworkIdName = clonePointer(m.DataSourceNetworkIdName)
	copy.DataSourceInstance = clonePointer(m.DataSourceInstance)
	copy.DataSourceIndexSource = clonePointer(m.DataSourceIndexSource)
	copy.AlertOccurrenceNumber = clonePointer(m.AlertOccurrenceNumber)
	copy.LanguageId = clonePointer(m.LanguageId)
	return &copy
}

type MaretronAlertControl struct {
	Info                    MessageInfo `json:"info"`
	ManufacturerCode        *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode            *uint64     `json:"industryCode,omitempty" n2k:"3"`
	AlertType               *uint64     `json:"alertType,omitempty" n2k:"4"`
	AlertCategory           *uint64     `json:"alertCategory,omitempty" n2k:"5"`
	AlertSystem             *uint64     `json:"alertSystem,omitempty" n2k:"6"`
	AlertSubSystem          *uint64     `json:"alertSubSystem,omitempty" n2k:"7"`
	AlertId                 *uint64     `json:"alertId,omitempty" n2k:"8"`
	DataSourceNetworkIdName *uint64     `json:"dataSourceNetworkIdName,omitempty" n2k:"9"`
	DataSourceInstance      *uint64     `json:"dataSourceInstance,omitempty" n2k:"10"`
	DataSourceIndexSource   *uint64     `json:"dataSourceIndexSource,omitempty" n2k:"11"`
	AlertOccurrenceNumber   *uint64     `json:"alertOccurrenceNumber,omitempty" n2k:"12"`
	MaretronExtension       []uint8     `json:"maretronExtension,omitempty" n2k:"13"`
}

func (m *MaretronAlertControl) PGNNumber() uint32                   { return 130822 }
func (m *MaretronAlertControl) MessageInfo() MessageInfo            { return m.Info }
func (m *MaretronAlertControl) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *MaretronAlertControl) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *MaretronAlertControl) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronAlertControl) Clone() Message {
	if m == nil {
		return (*MaretronAlertControl)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.AlertType = clonePointer(m.AlertType)
	copy.AlertCategory = clonePointer(m.AlertCategory)
	copy.AlertSystem = clonePointer(m.AlertSystem)
	copy.AlertSubSystem = clonePointer(m.AlertSubSystem)
	copy.AlertId = clonePointer(m.AlertId)
	copy.DataSourceNetworkIdName = clonePointer(m.DataSourceNetworkIdName)
	copy.DataSourceInstance = clonePointer(m.DataSourceInstance)
	copy.DataSourceIndexSource = clonePointer(m.DataSourceIndexSource)
	copy.AlertOccurrenceNumber = clonePointer(m.AlertOccurrenceNumber)
	copy.MaretronExtension = cloneSlice(m.MaretronExtension)
	return &copy
}

type MaretronProprietaryTemperatureHighRange struct {
	Info              MessageInfo `json:"info"`
	ManufacturerCode  *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode      *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Sid               *uint64     `json:"sid,omitempty" n2k:"4"`
	Instance          *uint64     `json:"instance,omitempty" n2k:"5"`
	Source            *uint64     `json:"source,omitempty" n2k:"6"`
	ActualTemperature *uint64     `json:"actualTemperature,omitempty" n2k:"7"`
	SetTemperature    *uint64     `json:"setTemperature,omitempty" n2k:"8"`
}

func (m *MaretronProprietaryTemperatureHighRange) PGNNumber() uint32               { return 130823 }
func (m *MaretronProprietaryTemperatureHighRange) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronProprietaryTemperatureHighRange) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronProprietaryTemperatureHighRange) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronProprietaryTemperatureHighRange) EncodePayload() ([]uint8, error) {
	return encodeFields(m)
}

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronProprietaryTemperatureHighRange) Clone() Message {
	if m == nil {
		return (*MaretronProprietaryTemperatureHighRange)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Sid = clonePointer(m.Sid)
	copy.Instance = clonePointer(m.Instance)
	copy.Source = clonePointer(m.Source)
	copy.ActualTemperature = clonePointer(m.ActualTemperature)
	copy.SetTemperature = clonePointer(m.SetTemperature)
	return &copy
}

// ActualTemperatureValue returns ActualTemperature as a physical value in K (value = raw * 0.1).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *MaretronProprietaryTemperatureHighRange) ActualTemperatureValue() (float64, bool) {
	if m == nil || m.ActualTemperature == nil {
		return 0, false
	}
	if *m.ActualTemperature == 65535 {
		return 0, false
	}
	if *m.ActualTemperature == 65534 {
		return 0, false
	}
	if *m.ActualTemperature == 65533 {
		return 0, false
	}
	value := float64(*m.ActualTemperature) * 0.1
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 6553.2 && !approximatelyEqual(value, 6553.2) {
		return 0, false
	}
	return value, true
}

// SetActualTemperatureValue sets ActualTemperature from a physical value in K, rounded to the nearest
// wire tick of 0.1.
func (m *MaretronProprietaryTemperatureHighRange) SetActualTemperatureValue(v float64) {
	raw := uint64(math.Round(v / 0.1))
	m.ActualTemperature = &raw
}

// SetTemperatureValue returns SetTemperature as a physical value in K (value = raw * 0.1).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *MaretronProprietaryTemperatureHighRange) SetTemperatureValue() (float64, bool) {
	if m == nil || m.SetTemperature == nil {
		return 0, false
	}
	if *m.SetTemperature == 65535 {
		return 0, false
	}
	if *m.SetTemperature == 65534 {
		return 0, false
	}
	if *m.SetTemperature == 65533 {
		return 0, false
	}
	value := float64(*m.SetTemperature) * 0.1
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 6553.2 && !approximatelyEqual(value, 6553.2) {
		return 0, false
	}
	return value, true
}

// SetSetTemperatureValue sets SetTemperature from a physical value in K, rounded to the nearest
// wire tick of 0.1.
func (m *MaretronProprietaryTemperatureHighRange) SetSetTemperatureValue(v float64) {
	raw := uint64(math.Round(v / 0.1))
	m.SetTemperature = &raw
}

type MaretronAnnunciator struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Field4           *uint64     `json:"field4,omitempty" n2k:"4"`
	Field5           *uint64     `json:"field5,omitempty" n2k:"5"`
	Field6           *uint64     `json:"field6,omitempty" n2k:"6"`
	Field7           *uint64     `json:"field7,omitempty" n2k:"7"`
	Field8           *uint64     `json:"field8,omitempty" n2k:"8"`
}

func (m *MaretronAnnunciator) PGNNumber() uint32                   { return 130824 }
func (m *MaretronAnnunciator) MessageInfo() MessageInfo            { return m.Info }
func (m *MaretronAnnunciator) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *MaretronAnnunciator) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *MaretronAnnunciator) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronAnnunciator) Clone() Message {
	if m == nil {
		return (*MaretronAnnunciator)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Field4 = clonePointer(m.Field4)
	copy.Field5 = clonePointer(m.Field5)
	copy.Field6 = clonePointer(m.Field6)
	copy.Field7 = clonePointer(m.Field7)
	copy.Field8 = clonePointer(m.Field8)
	return &copy
}

type MaretronDataInstanceChannelCorrelation struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Pgn              *uint64     `json:"pgn,omitempty" n2k:"4"`
	HardwareChannel  *uint64     `json:"hardwareChannel,omitempty" n2k:"5"`
	Instance         *uint64     `json:"instance,omitempty" n2k:"6"`
	DataSource       *uint64     `json:"dataSource,omitempty" n2k:"7"`
	DataIndicator    *uint64     `json:"dataIndicator,omitempty" n2k:"8"`
}

func (m *MaretronDataInstanceChannelCorrelation) PGNNumber() uint32               { return 130825 }
func (m *MaretronDataInstanceChannelCorrelation) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronDataInstanceChannelCorrelation) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronDataInstanceChannelCorrelation) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronDataInstanceChannelCorrelation) EncodePayload() ([]uint8, error) {
	return encodeFields(m)
}

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronDataInstanceChannelCorrelation) Clone() Message {
	if m == nil {
		return (*MaretronDataInstanceChannelCorrelation)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Pgn = clonePointer(m.Pgn)
	copy.HardwareChannel = clonePointer(m.HardwareChannel)
	copy.Instance = clonePointer(m.Instance)
	copy.DataSource = clonePointer(m.DataSource)
	copy.DataIndicator = clonePointer(m.DataIndicator)
	return &copy
}

type MaretronSwitchIndicatorStatus struct {
	Info                  MessageInfo                               `json:"info"`
	ManufacturerCode      *uint64                                   `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode          *uint64                                   `json:"industryCode,omitempty" n2k:"3"`
	IndicatorBankInstance *uint64                                   `json:"indicatorBankInstance,omitempty" n2k:"4"`
	NumberOfStatusFields  *uint64                                   `json:"numberOfStatusFields,omitempty" n2k:"5"`
	Repeating1            []MaretronSwitchIndicatorStatusRepeating1 `json:"repeating1,omitempty" n2k:"rep1"`
}

type MaretronSwitchIndicatorStatusRepeating1 struct {
	IndicatorStatus *uint64 `json:"indicatorStatus,omitempty" n2k:"6"`
}

func (m *MaretronSwitchIndicatorStatus) PGNNumber() uint32               { return 130826 }
func (m *MaretronSwitchIndicatorStatus) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronSwitchIndicatorStatus) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronSwitchIndicatorStatus) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronSwitchIndicatorStatus) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronSwitchIndicatorStatus) Clone() Message {
	if m == nil {
		return (*MaretronSwitchIndicatorStatus)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.IndicatorBankInstance = clonePointer(m.IndicatorBankInstance)
	copy.NumberOfStatusFields = clonePointer(m.NumberOfStatusFields)
	copy.Repeating1 = cloneSlice(m.Repeating1)
	for i := range copy.Repeating1 {
		copy.Repeating1[i].IndicatorStatus = clonePointer(m.Repeating1[i].IndicatorStatus)
	}
	return &copy
}

type MaretronDometicHvacControlStatus struct {
	Info                        MessageInfo `json:"info"`
	ManufacturerCode            *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode                *uint64     `json:"industryCode,omitempty" n2k:"3"`
	CanId                       *uint64     `json:"canId,omitempty" n2k:"4"`
	ConfigurationMode           *uint64     `json:"configurationMode,omitempty" n2k:"5"`
	Status                      *uint64     `json:"status,omitempty" n2k:"6"`
	FanModeSpeed                *uint64     `json:"fanModeSpeed,omitempty" n2k:"7"`
	SetpointTemperature         *uint64     `json:"setpointTemperature,omitempty" n2k:"8"`
	AmbientTemperature          *uint64     `json:"ambientTemperature,omitempty" n2k:"9"`
	OutdoorTemperature          *uint64     `json:"outdoorTemperature,omitempty" n2k:"10"`
	FaultStatus                 *uint64     `json:"faultStatus,omitempty" n2k:"11"`
	AdditionalSensorTemperature *uint64     `json:"additionalSensorTemperature,omitempty" n2k:"12"`
}

func (m *MaretronDometicHvacControlStatus) PGNNumber() uint32               { return 130828 }
func (m *MaretronDometicHvacControlStatus) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronDometicHvacControlStatus) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronDometicHvacControlStatus) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronDometicHvacControlStatus) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronDometicHvacControlStatus) Clone() Message {
	if m == nil {
		return (*MaretronDometicHvacControlStatus)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.CanId = clonePointer(m.CanId)
	copy.ConfigurationMode = clonePointer(m.ConfigurationMode)
	copy.Status = clonePointer(m.Status)
	copy.FanModeSpeed = clonePointer(m.FanModeSpeed)
	copy.SetpointTemperature = clonePointer(m.SetpointTemperature)
	copy.AmbientTemperature = clonePointer(m.AmbientTemperature)
	copy.OutdoorTemperature = clonePointer(m.OutdoorTemperature)
	copy.FaultStatus = clonePointer(m.FaultStatus)
	copy.AdditionalSensorTemperature = clonePointer(m.AdditionalSensorTemperature)
	return &copy
}

type MaretronDometicHvacStatus struct {
	Info                        MessageInfo `json:"info"`
	ManufacturerCode            *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode                *uint64     `json:"industryCode,omitempty" n2k:"3"`
	AdditionalSensorTemperature *uint64     `json:"additionalSensorTemperature,omitempty" n2k:"4"`
	CanId                       *uint64     `json:"canId,omitempty" n2k:"5"`
	State                       *uint64     `json:"state,omitempty" n2k:"6"`
	HardwareStatus              *uint64     `json:"hardwareStatus,omitempty" n2k:"7"`
	Faults                      *uint64     `json:"faults,omitempty" n2k:"8"`
	LineVoltage                 *uint64     `json:"lineVoltage,omitempty" n2k:"9"`
	CompressorCurrent           *uint64     `json:"compressorCurrent,omitempty" n2k:"10"`
}

func (m *MaretronDometicHvacStatus) PGNNumber() uint32               { return 130830 }
func (m *MaretronDometicHvacStatus) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronDometicHvacStatus) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronDometicHvacStatus) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronDometicHvacStatus) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronDometicHvacStatus) Clone() Message {
	if m == nil {
		return (*MaretronDometicHvacStatus)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.AdditionalSensorTemperature = clonePointer(m.AdditionalSensorTemperature)
	copy.CanId = clonePointer(m.CanId)
	copy.State = clonePointer(m.State)
	copy.HardwareStatus = clonePointer(m.HardwareStatus)
	copy.Faults = clonePointer(m.Faults)
	copy.LineVoltage = clonePointer(m.LineVoltage)
	copy.CompressorCurrent = clonePointer(m.CompressorCurrent)
	return &copy
}

type MaretronUniversalConfigurationFp struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Data             []uint8     `json:"data,omitempty" n2k:"4"`
}

func (m *MaretronUniversalConfigurationFp) PGNNumber() uint32               { return 130831 }
func (m *MaretronUniversalConfigurationFp) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronUniversalConfigurationFp) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronUniversalConfigurationFp) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronUniversalConfigurationFp) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronUniversalConfigurationFp) Clone() Message {
	if m == nil {
		return (*MaretronUniversalConfigurationFp)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Data = cloneSlice(m.Data)
	return &copy
}

type MaretronVesselOperatingMode struct {
	Info                   MessageInfo `json:"info"`
	ManufacturerCode       *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode           *uint64     `json:"industryCode,omitempty" n2k:"3"`
	AlertSystem            *uint64     `json:"alertSystem,omitempty" n2k:"4"`
	AlertSubSystem         *uint64     `json:"alertSubSystem,omitempty" n2k:"5"`
	AlertSystemInstance    *uint64     `json:"alertSystemInstance,omitempty" n2k:"6"`
	OperatingMode          *uint64     `json:"operatingMode,omitempty" n2k:"7"`
	GeneratingGlobalAlerts *uint64     `json:"generatingGlobalAlerts,omitempty" n2k:"8"`
	UserChanged            *uint64     `json:"userChanged,omitempty" n2k:"9"`
	InIndependentMode      *uint64     `json:"inIndependentMode,omitempty" n2k:"10"`
}

func (m *MaretronVesselOperatingMode) PGNNumber() uint32               { return 130832 }
func (m *MaretronVesselOperatingMode) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronVesselOperatingMode) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronVesselOperatingMode) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronVesselOperatingMode) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronVesselOperatingMode) Clone() Message {
	if m == nil {
		return (*MaretronVesselOperatingMode)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.AlertSystem = clonePointer(m.AlertSystem)
	copy.AlertSubSystem = clonePointer(m.AlertSubSystem)
	copy.AlertSystemInstance = clonePointer(m.AlertSystemInstance)
	copy.OperatingMode = clonePointer(m.OperatingMode)
	copy.GeneratingGlobalAlerts = clonePointer(m.GeneratingGlobalAlerts)
	copy.UserChanged = clonePointer(m.UserChanged)
	copy.InIndependentMode = clonePointer(m.InIndependentMode)
	return &copy
}

type MaretronVesselDataRecorderStatus struct {
	Info               MessageInfo `json:"info"`
	ManufacturerCode   *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode       *uint64     `json:"industryCode,omitempty" n2k:"3"`
	VdrRecordingStatus *uint64     `json:"vdrRecordingStatus,omitempty" n2k:"4"`
	MemoryCapacity     *uint64     `json:"memoryCapacity,omitempty" n2k:"5"`
	MemoryUsed         *uint64     `json:"memoryUsed,omitempty" n2k:"6"`
}

func (m *MaretronVesselDataRecorderStatus) PGNNumber() uint32               { return 130833 }
func (m *MaretronVesselDataRecorderStatus) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronVesselDataRecorderStatus) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronVesselDataRecorderStatus) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronVesselDataRecorderStatus) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronVesselDataRecorderStatus) Clone() Message {
	if m == nil {
		return (*MaretronVesselDataRecorderStatus)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.VdrRecordingStatus = clonePointer(m.VdrRecordingStatus)
	copy.MemoryCapacity = clonePointer(m.MemoryCapacity)
	copy.MemoryUsed = clonePointer(m.MemoryUsed)
	return &copy
}

type MaretronSmsStatus struct {
	Info                MessageInfo `json:"info"`
	ManufacturerCode    *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode        *uint64     `json:"industryCode,omitempty" n2k:"3"`
	SimCardStatus       *uint64     `json:"simCardStatus,omitempty" n2k:"4"`
	GsmBand             *uint64     `json:"gsmBand,omitempty" n2k:"5"`
	SignalStrength      *uint64     `json:"signalStrength,omitempty" n2k:"6"`
	BitErrorRate        *uint64     `json:"bitErrorRate,omitempty" n2k:"7"`
	SimCardPhoneNumber  string      `json:"simCardPhoneNumber,omitempty" n2k:"8"`
	NetworkOperatorName string      `json:"networkOperatorName,omitempty" n2k:"9"`
}

func (m *MaretronSmsStatus) PGNNumber() uint32                   { return 130834 }
func (m *MaretronSmsStatus) MessageInfo() MessageInfo            { return m.Info }
func (m *MaretronSmsStatus) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *MaretronSmsStatus) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *MaretronSmsStatus) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronSmsStatus) Clone() Message {
	if m == nil {
		return (*MaretronSmsStatus)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.SimCardStatus = clonePointer(m.SimCardStatus)
	copy.GsmBand = clonePointer(m.GsmBand)
	copy.SignalStrength = clonePointer(m.SignalStrength)
	copy.BitErrorRate = clonePointer(m.BitErrorRate)
	return &copy
}

type MaretronSmsTextMessage struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	MessageType      *uint64     `json:"messageType,omitempty" n2k:"4"`
	PhoneNumber      string      `json:"phoneNumber,omitempty" n2k:"5"`
	Message          string      `json:"message,omitempty" n2k:"6"`
}

func (m *MaretronSmsTextMessage) PGNNumber() uint32               { return 130835 }
func (m *MaretronSmsTextMessage) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronSmsTextMessage) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronSmsTextMessage) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronSmsTextMessage) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronSmsTextMessage) Clone() Message {
	if m == nil {
		return (*MaretronSmsTextMessage)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.MessageType = clonePointer(m.MessageType)
	return &copy
}

type MaretronSwitchStatusCounter struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Instance         *uint64     `json:"instance,omitempty" n2k:"4"`
	IndicatorNumber  *uint64     `json:"indicatorNumber,omitempty" n2k:"5"`
	StartDate        *uint64     `json:"startDate,omitempty" n2k:"6"`
	StartTime        *uint64     `json:"startTime,omitempty" n2k:"7"`
	OffCounter       *uint64     `json:"offCounter,omitempty" n2k:"8"`
	OnCounter        *uint64     `json:"onCounter,omitempty" n2k:"9"`
	ErrorCounter     *uint64     `json:"errorCounter,omitempty" n2k:"10"`
	SwitchStatus     *uint64     `json:"switchStatus,omitempty" n2k:"11"`
}

func (m *MaretronSwitchStatusCounter) PGNNumber() uint32               { return 130836 }
func (m *MaretronSwitchStatusCounter) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronSwitchStatusCounter) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronSwitchStatusCounter) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronSwitchStatusCounter) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronSwitchStatusCounter) Clone() Message {
	if m == nil {
		return (*MaretronSwitchStatusCounter)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Instance = clonePointer(m.Instance)
	copy.IndicatorNumber = clonePointer(m.IndicatorNumber)
	copy.StartDate = clonePointer(m.StartDate)
	copy.StartTime = clonePointer(m.StartTime)
	copy.OffCounter = clonePointer(m.OffCounter)
	copy.OnCounter = clonePointer(m.OnCounter)
	copy.ErrorCounter = clonePointer(m.ErrorCounter)
	copy.SwitchStatus = clonePointer(m.SwitchStatus)
	return &copy
}

// StartDateValue returns StartDate as a physical value in d (value = raw).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *MaretronSwitchStatusCounter) StartDateValue() (float64, bool) {
	if m == nil || m.StartDate == nil {
		return 0, false
	}
	if *m.StartDate == 65535 {
		return 0, false
	}
	if *m.StartDate == 65534 {
		return 0, false
	}
	if *m.StartDate == 65533 {
		return 0, false
	}
	value := float64(*m.StartDate)
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 65532 && !approximatelyEqual(value, 65532) {
		return 0, false
	}
	return value, true
}

// SetStartDateValue sets StartDate from a physical value in d, rounded to the nearest
// wire tick of 1.
func (m *MaretronSwitchStatusCounter) SetStartDateValue(v float64) {
	raw := uint64(math.Round(v))
	m.StartDate = &raw
}

// StartTimeValue returns StartTime as a physical value in s (value = raw * 0.0001).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *MaretronSwitchStatusCounter) StartTimeValue() (float64, bool) {
	if m == nil || m.StartTime == nil {
		return 0, false
	}
	if *m.StartTime == 4294967295 {
		return 0, false
	}
	if *m.StartTime == 4294967294 {
		return 0, false
	}
	if *m.StartTime == 4294967293 {
		return 0, false
	}
	value := float64(*m.StartTime) * 0.0001
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 86401 && !approximatelyEqual(value, 86401) {
		return 0, false
	}
	return value, true
}

// SetStartTimeValue sets StartTime from a physical value in s, rounded to the nearest
// wire tick of 0.0001.
func (m *MaretronSwitchStatusCounter) SetStartTimeValue(v float64) {
	raw := uint64(math.Round(v / 0.0001))
	m.StartTime = &raw
}

type MaretronSwitchStatusTimer struct {
	Info                   MessageInfo `json:"info"`
	ManufacturerCode       *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode           *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Instance               *uint64     `json:"instance,omitempty" n2k:"4"`
	IndicatorNumber        *uint64     `json:"indicatorNumber,omitempty" n2k:"5"`
	StartDate              *uint64     `json:"startDate,omitempty" n2k:"6"`
	StartTime              *uint64     `json:"startTime,omitempty" n2k:"7"`
	AccumulatedOffPeriod   *uint64     `json:"accumulatedOffPeriod,omitempty" n2k:"8"`
	AccumulatedOnPeriod    *uint64     `json:"accumulatedOnPeriod,omitempty" n2k:"9"`
	AccumulatedErrorPeriod *uint64     `json:"accumulatedErrorPeriod,omitempty" n2k:"10"`
	SwitchStatus           *uint64     `json:"switchStatus,omitempty" n2k:"11"`
}

func (m *MaretronSwitchStatusTimer) PGNNumber() uint32               { return 130837 }
func (m *MaretronSwitchStatusTimer) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronSwitchStatusTimer) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronSwitchStatusTimer) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronSwitchStatusTimer) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronSwitchStatusTimer) Clone() Message {
	if m == nil {
		return (*MaretronSwitchStatusTimer)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Instance = clonePointer(m.Instance)
	copy.IndicatorNumber = clonePointer(m.IndicatorNumber)
	copy.StartDate = clonePointer(m.StartDate)
	copy.StartTime = clonePointer(m.StartTime)
	copy.AccumulatedOffPeriod = clonePointer(m.AccumulatedOffPeriod)
	copy.AccumulatedOnPeriod = clonePointer(m.AccumulatedOnPeriod)
	copy.AccumulatedErrorPeriod = clonePointer(m.AccumulatedErrorPeriod)
	copy.SwitchStatus = clonePointer(m.SwitchStatus)
	return &copy
}

// StartDateValue returns StartDate as a physical value in d (value = raw).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *MaretronSwitchStatusTimer) StartDateValue() (float64, bool) {
	if m == nil || m.StartDate == nil {
		return 0, false
	}
	if *m.StartDate == 65535 {
		return 0, false
	}
	if *m.StartDate == 65534 {
		return 0, false
	}
	if *m.StartDate == 65533 {
		return 0, false
	}
	value := float64(*m.StartDate)
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 65532 && !approximatelyEqual(value, 65532) {
		return 0, false
	}
	return value, true
}

// SetStartDateValue sets StartDate from a physical value in d, rounded to the nearest
// wire tick of 1.
func (m *MaretronSwitchStatusTimer) SetStartDateValue(v float64) {
	raw := uint64(math.Round(v))
	m.StartDate = &raw
}

// StartTimeValue returns StartTime as a physical value in s (value = raw * 0.0001).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *MaretronSwitchStatusTimer) StartTimeValue() (float64, bool) {
	if m == nil || m.StartTime == nil {
		return 0, false
	}
	if *m.StartTime == 4294967295 {
		return 0, false
	}
	if *m.StartTime == 4294967294 {
		return 0, false
	}
	if *m.StartTime == 4294967293 {
		return 0, false
	}
	value := float64(*m.StartTime) * 0.0001
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 86401 && !approximatelyEqual(value, 86401) {
		return 0, false
	}
	return value, true
}

// SetStartTimeValue sets StartTime from a physical value in s, rounded to the nearest
// wire tick of 0.0001.
func (m *MaretronSwitchStatusTimer) SetStartTimeValue(v float64) {
	raw := uint64(math.Round(v / 0.0001))
	m.StartTime = &raw
}

// AccumulatedOffPeriodValue returns AccumulatedOffPeriod as a physical value in s (value = raw).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *MaretronSwitchStatusTimer) AccumulatedOffPeriodValue() (float64, bool) {
	if m == nil || m.AccumulatedOffPeriod == nil {
		return 0, false
	}
	if *m.AccumulatedOffPeriod == 4294967295 {
		return 0, false
	}
	if *m.AccumulatedOffPeriod == 4294967294 {
		return 0, false
	}
	if *m.AccumulatedOffPeriod == 4294967293 {
		return 0, false
	}
	value := float64(*m.AccumulatedOffPeriod)
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 4.294967292e+09 && !approximatelyEqual(value, 4.294967292e+09) {
		return 0, false
	}
	return value, true
}

// SetAccumulatedOffPeriodValue sets AccumulatedOffPeriod from a physical value in s, rounded to the nearest
// wire tick of 1.
func (m *MaretronSwitchStatusTimer) SetAccumulatedOffPeriodValue(v float64) {
	raw := uint64(math.Round(v))
	m.AccumulatedOffPeriod = &raw
}

// AccumulatedOnPeriodValue returns AccumulatedOnPeriod as a physical value in s (value = raw).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *MaretronSwitchStatusTimer) AccumulatedOnPeriodValue() (float64, bool) {
	if m == nil || m.AccumulatedOnPeriod == nil {
		return 0, false
	}
	if *m.AccumulatedOnPeriod == 4294967295 {
		return 0, false
	}
	if *m.AccumulatedOnPeriod == 4294967294 {
		return 0, false
	}
	if *m.AccumulatedOnPeriod == 4294967293 {
		return 0, false
	}
	value := float64(*m.AccumulatedOnPeriod)
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 4.294967292e+09 && !approximatelyEqual(value, 4.294967292e+09) {
		return 0, false
	}
	return value, true
}

// SetAccumulatedOnPeriodValue sets AccumulatedOnPeriod from a physical value in s, rounded to the nearest
// wire tick of 1.
func (m *MaretronSwitchStatusTimer) SetAccumulatedOnPeriodValue(v float64) {
	raw := uint64(math.Round(v))
	m.AccumulatedOnPeriod = &raw
}

// AccumulatedErrorPeriodValue returns AccumulatedErrorPeriod as a physical value in s (value = raw).
// The bool is false for absent, sentinel, or out-of-range measurements.
func (m *MaretronSwitchStatusTimer) AccumulatedErrorPeriodValue() (float64, bool) {
	if m == nil || m.AccumulatedErrorPeriod == nil {
		return 0, false
	}
	if *m.AccumulatedErrorPeriod == 4294967295 {
		return 0, false
	}
	if *m.AccumulatedErrorPeriod == 4294967294 {
		return 0, false
	}
	if *m.AccumulatedErrorPeriod == 4294967293 {
		return 0, false
	}
	value := float64(*m.AccumulatedErrorPeriod)
	if value < 0 && !approximatelyEqual(value, 0) {
		return 0, false
	}
	if value > 4.294967292e+09 && !approximatelyEqual(value, 4.294967292e+09) {
		return 0, false
	}
	return value, true
}

// SetAccumulatedErrorPeriodValue sets AccumulatedErrorPeriod from a physical value in s, rounded to the nearest
// wire tick of 1.
func (m *MaretronSwitchStatusTimer) SetAccumulatedErrorPeriodValue(v float64) {
	raw := uint64(math.Round(v))
	m.AccumulatedErrorPeriod = &raw
}

type MaretronBnwas struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Data             []uint8     `json:"data,omitempty" n2k:"4"`
}

func (m *MaretronBnwas) PGNNumber() uint32                   { return 130838 }
func (m *MaretronBnwas) MessageInfo() MessageInfo            { return m.Info }
func (m *MaretronBnwas) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *MaretronBnwas) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *MaretronBnwas) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronBnwas) Clone() Message {
	if m == nil {
		return (*MaretronBnwas)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Data = cloneSlice(m.Data)
	return &copy
}

type MaretronGenericSensor struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	DataInstance     *uint64     `json:"dataInstance,omitempty" n2k:"4"`
	DataFormat       *uint64     `json:"dataFormat,omitempty" n2k:"5"`
	Value            []uint8     `json:"value,omitempty" n2k:"6"`
}

func (m *MaretronGenericSensor) PGNNumber() uint32                   { return 130840 }
func (m *MaretronGenericSensor) MessageInfo() MessageInfo            { return m.Info }
func (m *MaretronGenericSensor) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *MaretronGenericSensor) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *MaretronGenericSensor) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronGenericSensor) Clone() Message {
	if m == nil {
		return (*MaretronGenericSensor)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.DataInstance = clonePointer(m.DataInstance)
	copy.DataFormat = clonePointer(m.DataFormat)
	copy.Value = cloneSlice(m.Value)
	return &copy
}

type MaretronCanFrameForwarding struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Data             []uint8     `json:"data,omitempty" n2k:"4"`
}

func (m *MaretronCanFrameForwarding) PGNNumber() uint32               { return 130841 }
func (m *MaretronCanFrameForwarding) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronCanFrameForwarding) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronCanFrameForwarding) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronCanFrameForwarding) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronCanFrameForwarding) Clone() Message {
	if m == nil {
		return (*MaretronCanFrameForwarding)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Data = cloneSlice(m.Data)
	return &copy
}

type MaretronWindlassOperatingStatus struct {
	Info                     MessageInfo `json:"info"`
	ManufacturerCode         *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode             *uint64     `json:"industryCode,omitempty" n2k:"3"`
	WindlassOperatingEvents  *uint64     `json:"windlassOperatingEvents,omitempty" n2k:"4"`
	WindlassInstance         *uint64     `json:"windlassInstance,omitempty" n2k:"5"`
	WindlassDirectionControl *uint64     `json:"windlassDirectionControl,omitempty" n2k:"6"`
	SpeedControl             *uint64     `json:"speedControl,omitempty" n2k:"7"`
	PowerEnable              *uint64     `json:"powerEnable,omitempty" n2k:"8"`
	MechanicalEnable         *uint64     `json:"mechanicalEnable,omitempty" n2k:"9"`
	AnchorDockingControl     *uint64     `json:"anchorDockingControl,omitempty" n2k:"10"`
	DeckAndAnchorWash        *uint64     `json:"deckAndAnchorWash,omitempty" n2k:"11"`
	AnchorLight              *uint64     `json:"anchorLight,omitempty" n2k:"12"`
	AuxiliaryAControl        *uint64     `json:"auxiliaryAControl,omitempty" n2k:"13"`
	AuxiliaryBControl        *uint64     `json:"auxiliaryBControl,omitempty" n2k:"14"`
	AuxiliaryCControl        *uint64     `json:"auxiliaryCControl,omitempty" n2k:"15"`
	AuxiliaryDControl        *uint64     `json:"auxiliaryDControl,omitempty" n2k:"16"`
}

func (m *MaretronWindlassOperatingStatus) PGNNumber() uint32               { return 130842 }
func (m *MaretronWindlassOperatingStatus) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronWindlassOperatingStatus) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronWindlassOperatingStatus) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronWindlassOperatingStatus) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronWindlassOperatingStatus) Clone() Message {
	if m == nil {
		return (*MaretronWindlassOperatingStatus)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.WindlassOperatingEvents = clonePointer(m.WindlassOperatingEvents)
	copy.WindlassInstance = clonePointer(m.WindlassInstance)
	copy.WindlassDirectionControl = clonePointer(m.WindlassDirectionControl)
	copy.SpeedControl = clonePointer(m.SpeedControl)
	copy.PowerEnable = clonePointer(m.PowerEnable)
	copy.MechanicalEnable = clonePointer(m.MechanicalEnable)
	copy.AnchorDockingControl = clonePointer(m.AnchorDockingControl)
	copy.DeckAndAnchorWash = clonePointer(m.DeckAndAnchorWash)
	copy.AnchorLight = clonePointer(m.AnchorLight)
	copy.AuxiliaryAControl = clonePointer(m.AuxiliaryAControl)
	copy.AuxiliaryBControl = clonePointer(m.AuxiliaryBControl)
	copy.AuxiliaryCControl = clonePointer(m.AuxiliaryCControl)
	copy.AuxiliaryDControl = clonePointer(m.AuxiliaryDControl)
	return &copy
}

type MaretronWindlassControlCommand struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Data             []uint8     `json:"data,omitempty" n2k:"4"`
}

func (m *MaretronWindlassControlCommand) PGNNumber() uint32               { return 130843 }
func (m *MaretronWindlassControlCommand) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronWindlassControlCommand) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronWindlassControlCommand) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronWindlassControlCommand) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronWindlassControlCommand) Clone() Message {
	if m == nil {
		return (*MaretronWindlassControlCommand)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Data = cloneSlice(m.Data)
	return &copy
}

type MaretronDcEnergy struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Data             []uint8     `json:"data,omitempty" n2k:"4"`
}

func (m *MaretronDcEnergy) PGNNumber() uint32                   { return 130845 }
func (m *MaretronDcEnergy) MessageInfo() MessageInfo            { return m.Info }
func (m *MaretronDcEnergy) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *MaretronDcEnergy) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *MaretronDcEnergy) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronDcEnergy) Clone() Message {
	if m == nil {
		return (*MaretronDcEnergy)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Data = cloneSlice(m.Data)
	return &copy
}

type MaretronBatteryAmpHourRecord struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Data             []uint8     `json:"data,omitempty" n2k:"4"`
}

func (m *MaretronBatteryAmpHourRecord) PGNNumber() uint32               { return 130846 }
func (m *MaretronBatteryAmpHourRecord) MessageInfo() MessageInfo        { return m.Info }
func (m *MaretronBatteryAmpHourRecord) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MaretronBatteryAmpHourRecord) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MaretronBatteryAmpHourRecord) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *MaretronBatteryAmpHourRecord) Clone() Message {
	if m == nil {
		return (*MaretronBatteryAmpHourRecord)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.Data = cloneSlice(m.Data)
	return &copy
}
