// Code generated by PGN generator; DO NOT EDIT.
// Source schema 2.5.0 version 7.1.0.

package pgn

import "math"

type MercuryEngineData struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Data             []uint8     `json:"data,omitempty" n2k:"4"`
}

func (m *MercuryEngineData) PGNNumber() uint32                   { return 65280 }
func (m *MercuryEngineData) MessageInfo() MessageInfo            { return m.Info }
func (m *MercuryEngineData) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *MercuryEngineData) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *MercuryEngineData) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

type MercuryEngineTelemetryLowSpeed struct {
	Info                  MessageInfo `json:"info"`
	ManufacturerCode      *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode          *uint64     `json:"industryCode,omitempty" n2k:"3"`
	EngineInstance        *uint64     `json:"engineInstance,omitempty" n2k:"4"`
	MalfunctionIndicator  *uint64     `json:"malfunctionIndicator,omitempty" n2k:"5"`
	IntakeAirTemperature  *uint64     `json:"intakeAirTemperature,omitempty" n2k:"6"`
	ExhaustGasTemperature *uint64     `json:"exhaustGasTemperature,omitempty" n2k:"7"`
	Gpl                   *uint64     `json:"gpl,omitempty" n2k:"8"`
	EngineState           *uint64     `json:"engineState,omitempty" n2k:"9"`
}

func (m *MercuryEngineTelemetryLowSpeed) PGNNumber() uint32               { return 130822 }
func (m *MercuryEngineTelemetryLowSpeed) MessageInfo() MessageInfo        { return m.Info }
func (m *MercuryEngineTelemetryLowSpeed) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MercuryEngineTelemetryLowSpeed) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MercuryEngineTelemetryLowSpeed) EncodePayload() ([]uint8, error) { return encodeFields(m) }

type MercuryEngineKeyValueData struct {
	Info             MessageInfo                           `json:"info"`
	ManufacturerCode *uint64                               `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64                               `json:"industryCode,omitempty" n2k:"3"`
	Repeating1       []MercuryEngineKeyValueDataRepeating1 `json:"repeating1,omitempty" n2k:"rep1"`
}

type MercuryEngineKeyValueDataRepeating1 struct {
	Key    *uint64 `json:"key,omitempty" n2k:"4"`
	Length *uint64 `json:"length,omitempty" n2k:"5"`
	Value  []uint8 `json:"value,omitempty" n2k:"6"`
}

func (m *MercuryEngineKeyValueData) PGNNumber() uint32               { return 130824 }
func (m *MercuryEngineKeyValueData) MessageInfo() MessageInfo        { return m.Info }
func (m *MercuryEngineKeyValueData) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MercuryEngineKeyValueData) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MercuryEngineKeyValueData) EncodePayload() ([]uint8, error) { return encodeFields(m) }

type MercuryCommandResponse struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Opcode           *uint64     `json:"opcode,omitempty" n2k:"4"`
	Data             []uint8     `json:"data,omitempty" n2k:"5"`
}

func (m *MercuryCommandResponse) PGNNumber() uint32               { return 130825 }
func (m *MercuryCommandResponse) MessageInfo() MessageInfo        { return m.Info }
func (m *MercuryCommandResponse) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MercuryCommandResponse) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MercuryCommandResponse) EncodePayload() ([]uint8, error) { return encodeFields(m) }

type MercuryCruiseControlData struct {
	Info                MessageInfo `json:"info"`
	ManufacturerCode    *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode        *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Opcode              *uint64     `json:"opcode,omitempty" n2k:"4"`
	EngineInstance      *uint64     `json:"engineInstance,omitempty" n2k:"5"`
	CruiseState         *uint64     `json:"cruiseState,omitempty" n2k:"7"`
	CruiseRpmSetpoint   *uint64     `json:"cruiseRpmSetpoint,omitempty" n2k:"8"`
	CruiseSpeedSetpoint *uint64     `json:"cruiseSpeedSetpoint,omitempty" n2k:"9"`
}

func (m *MercuryCruiseControlData) PGNNumber() uint32               { return 130825 }
func (m *MercuryCruiseControlData) MessageInfo() MessageInfo        { return m.Info }
func (m *MercuryCruiseControlData) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MercuryCruiseControlData) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MercuryCruiseControlData) EncodePayload() ([]uint8, error) { return encodeFields(m) }

// CruiseRpmSetpointValue returns CruiseRpmSetpoint as a physical value in rpm (value = raw).
// The bool is false when CruiseRpmSetpoint is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MercuryCruiseControlData) CruiseRpmSetpointValue() (float64, bool) {
	if m.CruiseRpmSetpoint == nil {
		return 0, false
	}
	return float64(*m.CruiseRpmSetpoint), true
}

// SetCruiseRpmSetpointValue sets CruiseRpmSetpoint from a physical value in rpm, rounded to the nearest
// wire tick of 1.
func (m *MercuryCruiseControlData) SetCruiseRpmSetpointValue(v float64) {
	raw := uint64(math.Round(v))
	m.CruiseRpmSetpoint = &raw
}

// CruiseSpeedSetpointValue returns CruiseSpeedSetpoint as a physical value in km/h (value = raw * 0.01).
// The bool is false when CruiseSpeedSetpoint is nil: the wire carried the field's null
// sentinel or the payload ended before the field.
func (m *MercuryCruiseControlData) CruiseSpeedSetpointValue() (float64, bool) {
	if m.CruiseSpeedSetpoint == nil {
		return 0, false
	}
	return float64(*m.CruiseSpeedSetpoint) * 0.01, true
}

// SetCruiseSpeedSetpointValue sets CruiseSpeedSetpoint from a physical value in km/h, rounded to the nearest
// wire tick of 0.01.
func (m *MercuryCruiseControlData) SetCruiseSpeedSetpointValue(v float64) {
	raw := uint64(math.Round(v / 0.01))
	m.CruiseSpeedSetpoint = &raw
}

type MercuryBamDigitalDataProxy struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Type             *uint64     `json:"type,omitempty" n2k:"4"`
	Instance         *uint64     `json:"instance,omitempty" n2k:"5"`
	Field4           *uint64     `json:"field4,omitempty" n2k:"6"`
	Flag             *uint64     `json:"flag,omitempty" n2k:"8"`
	Data             []uint8     `json:"data,omitempty" n2k:"9"`
}

func (m *MercuryBamDigitalDataProxy) PGNNumber() uint32               { return 130826 }
func (m *MercuryBamDigitalDataProxy) MessageInfo() MessageInfo        { return m.Info }
func (m *MercuryBamDigitalDataProxy) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *MercuryBamDigitalDataProxy) DecodePayload(payload []uint8) error {
	return decodeFields(m, payload)
}
func (m *MercuryBamDigitalDataProxy) EncodePayload() ([]uint8, error) { return encodeFields(m) }

type MercuryEngineStatus struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	FieldA           []uint8     `json:"fieldA,omitempty" n2k:"5"`
	SubHelm          []uint8     `json:"subHelm,omitempty" n2k:"6"`
	Helm             []uint8     `json:"helm,omitempty" n2k:"7"`
	Capabilities     []uint8     `json:"capabilities,omitempty" n2k:"8"`
}

func (m *MercuryEngineStatus) PGNNumber() uint32                   { return 130829 }
func (m *MercuryEngineStatus) MessageInfo() MessageInfo            { return m.Info }
func (m *MercuryEngineStatus) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *MercuryEngineStatus) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *MercuryEngineStatus) EncodePayload() ([]uint8, error)     { return encodeFields(m) }
