// Code generated by PGN generator; DO NOT EDIT.
// Source schema 2.4.0 version 7.0.0.

package pgn

type PgnMercuryEngineData struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Data             []uint8     `json:"data,omitempty" n2k:"4"`
}

func (m *PgnMercuryEngineData) PGNNumber() uint32               { return 65280 }
func (m *PgnMercuryEngineData) MessageInfo() MessageInfo        { return m.Info }
func (m *PgnMercuryEngineData) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *PgnMercuryEngineData) DecodePayload(payload []uint8) error {
	return decodeStructPayload(lookupPgnInfo(65280, "Mercury: Engine Data"), m, payload)
}
func (m *PgnMercuryEngineData) EncodePayload() ([]uint8, error) {
	return encodeStructPayload(lookupPgnInfo(65280, "Mercury: Engine Data"), m)
}

type PgnMercuryEngineTelemetryLowSpeed struct {
	Info                  MessageInfo `json:"info"`
	ManufacturerCode      *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode          *uint64     `json:"industryCode,omitempty" n2k:"3"`
	EngineInstance        *uint64     `json:"engineInstance,omitempty" n2k:"4"`
	MalfunctionIndicator  *uint64     `json:"malfunctionIndicator,omitempty" n2k:"5"`
	IntakeAirTemperature  *uint64     `json:"intakeAirTemperature,omitempty" n2k:"6"`
	ExhaustGasTemperature *uint64     `json:"exhaustGasTemperature,omitempty" n2k:"7"`
	Gpl                   *uint64     `json:"gpl,omitempty" n2k:"8"`
	EngineState           *uint64     `json:"engineState,omitempty" n2k:"9"`
}

func (m *PgnMercuryEngineTelemetryLowSpeed) PGNNumber() uint32               { return 130822 }
func (m *PgnMercuryEngineTelemetryLowSpeed) MessageInfo() MessageInfo        { return m.Info }
func (m *PgnMercuryEngineTelemetryLowSpeed) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *PgnMercuryEngineTelemetryLowSpeed) DecodePayload(payload []uint8) error {
	return decodeStructPayload(lookupPgnInfo(130822, "Mercury: Engine Telemetry, Low Speed"), m, payload)
}
func (m *PgnMercuryEngineTelemetryLowSpeed) EncodePayload() ([]uint8, error) {
	return encodeStructPayload(lookupPgnInfo(130822, "Mercury: Engine Telemetry, Low Speed"), m)
}

type PgnMercuryEngineKeyValueData struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Key              *uint64     `json:"key,omitempty" n2k:"4"`
	Length           *uint64     `json:"length,omitempty" n2k:"5"`
	Value            []uint8     `json:"value,omitempty" n2k:"6"`
}

func (m *PgnMercuryEngineKeyValueData) PGNNumber() uint32               { return 130824 }
func (m *PgnMercuryEngineKeyValueData) MessageInfo() MessageInfo        { return m.Info }
func (m *PgnMercuryEngineKeyValueData) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *PgnMercuryEngineKeyValueData) DecodePayload(payload []uint8) error {
	return decodeStructPayload(lookupPgnInfo(130824, "Mercury: Engine Key-Value Data"), m, payload)
}
func (m *PgnMercuryEngineKeyValueData) EncodePayload() ([]uint8, error) {
	return encodeStructPayload(lookupPgnInfo(130824, "Mercury: Engine Key-Value Data"), m)
}

type PgnMercuryCommandResponse struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Opcode           *uint64     `json:"opcode,omitempty" n2k:"4"`
	Data             []uint8     `json:"data,omitempty" n2k:"5"`
}

func (m *PgnMercuryCommandResponse) PGNNumber() uint32               { return 130825 }
func (m *PgnMercuryCommandResponse) MessageInfo() MessageInfo        { return m.Info }
func (m *PgnMercuryCommandResponse) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *PgnMercuryCommandResponse) DecodePayload(payload []uint8) error {
	return decodeStructPayload(lookupPgnInfo(130825, "Mercury: Command/Response"), m, payload)
}
func (m *PgnMercuryCommandResponse) EncodePayload() ([]uint8, error) {
	return encodeStructPayload(lookupPgnInfo(130825, "Mercury: Command/Response"), m)
}

type PgnMercuryCruiseControlData struct {
	Info                MessageInfo `json:"info"`
	ManufacturerCode    *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode        *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Opcode              *uint64     `json:"opcode,omitempty" n2k:"4"`
	EngineInstance      *uint64     `json:"engineInstance,omitempty" n2k:"5"`
	CruiseState         *uint64     `json:"cruiseState,omitempty" n2k:"7"`
	CruiseRpmSetpoint   *uint64     `json:"cruiseRpmSetpoint,omitempty" n2k:"8"`
	CruiseSpeedSetpoint *uint64     `json:"cruiseSpeedSetpoint,omitempty" n2k:"9"`
}

func (m *PgnMercuryCruiseControlData) PGNNumber() uint32               { return 130825 }
func (m *PgnMercuryCruiseControlData) MessageInfo() MessageInfo        { return m.Info }
func (m *PgnMercuryCruiseControlData) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *PgnMercuryCruiseControlData) DecodePayload(payload []uint8) error {
	return decodeStructPayload(lookupPgnInfo(130825, "Mercury: Cruise Control Data"), m, payload)
}
func (m *PgnMercuryCruiseControlData) EncodePayload() ([]uint8, error) {
	return encodeStructPayload(lookupPgnInfo(130825, "Mercury: Cruise Control Data"), m)
}

type PgnMercuryBamDigitalDataProxy struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	Type             *uint64     `json:"type,omitempty" n2k:"4"`
	Instance         *uint64     `json:"instance,omitempty" n2k:"5"`
	Field4           *uint64     `json:"field4,omitempty" n2k:"6"`
	Flag             *uint64     `json:"flag,omitempty" n2k:"8"`
	Data             []uint8     `json:"data,omitempty" n2k:"9"`
}

func (m *PgnMercuryBamDigitalDataProxy) PGNNumber() uint32               { return 130826 }
func (m *PgnMercuryBamDigitalDataProxy) MessageInfo() MessageInfo        { return m.Info }
func (m *PgnMercuryBamDigitalDataProxy) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *PgnMercuryBamDigitalDataProxy) DecodePayload(payload []uint8) error {
	return decodeStructPayload(lookupPgnInfo(130826, "Mercury: BAM Digital-Data Proxy"), m, payload)
}
func (m *PgnMercuryBamDigitalDataProxy) EncodePayload() ([]uint8, error) {
	return encodeStructPayload(lookupPgnInfo(130826, "Mercury: BAM Digital-Data Proxy"), m)
}

type PgnMercuryEngineStatus struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	FieldA           []uint8     `json:"fieldA,omitempty" n2k:"5"`
	SubHelm          []uint8     `json:"subHelm,omitempty" n2k:"6"`
	Helm             []uint8     `json:"helm,omitempty" n2k:"7"`
	Capabilities     []uint8     `json:"capabilities,omitempty" n2k:"8"`
}

func (m *PgnMercuryEngineStatus) PGNNumber() uint32               { return 130829 }
func (m *PgnMercuryEngineStatus) MessageInfo() MessageInfo        { return m.Info }
func (m *PgnMercuryEngineStatus) SetMessageInfo(info MessageInfo) { m.Info = info }
func (m *PgnMercuryEngineStatus) DecodePayload(payload []uint8) error {
	return decodeStructPayload(lookupPgnInfo(130829, "Mercury: Engine Status"), m, payload)
}
func (m *PgnMercuryEngineStatus) EncodePayload() ([]uint8, error) {
	return encodeStructPayload(lookupPgnInfo(130829, "Mercury: Engine Status"), m)
}
