// Code generated by PGN generator; DO NOT EDIT.
// Source schema 2.5.0 version 7.1.0.

package pgn

type VictronVeCanRegister struct {
	Info             MessageInfo `json:"info"`
	ManufacturerCode *uint64     `json:"manufacturerCode,omitempty" n2k:"1"`
	IndustryCode     *uint64     `json:"industryCode,omitempty" n2k:"3"`
	RegisterId       *uint64     `json:"registerId,omitempty" n2k:"4"`
	Value            []uint8     `json:"value,omitempty" n2k:"5"`
}

func (m *VictronVeCanRegister) PGNNumber() uint32                   { return 61184 }
func (m *VictronVeCanRegister) MessageInfo() MessageInfo            { return m.Info }
func (m *VictronVeCanRegister) SetMessageInfo(info MessageInfo)     { m.Info = info }
func (m *VictronVeCanRegister) DecodePayload(payload []uint8) error { return decodeFields(m, payload) }
func (m *VictronVeCanRegister) EncodePayload() ([]uint8, error)     { return encodeFields(m) }

// Clone returns a message owning every mutable field and retained wire byte.
func (m *VictronVeCanRegister) Clone() Message {
	if m == nil {
		return (*VictronVeCanRegister)(nil)
	}
	copy := *m
	copy.Info = m.Info.Clone()
	copy.ManufacturerCode = clonePointer(m.ManufacturerCode)
	copy.IndustryCode = clonePointer(m.IndustryCode)
	copy.RegisterId = clonePointer(m.RegisterId)
	copy.Value = cloneSlice(m.Value)
	return &copy
}
